### ISSUE TITLE
♡♥♧♣  [필독] 이슈를 남기시는 분들께. ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ ♡♥♧♣ 

### ISSUE THREAD

**Issue by thomasJang** [axisj/axisj#368]
~ 여러분의 질문은 저희에게 부담이 아니라 행복입니다. ~

### 질문은 소스와 캡쳐를 꼭 남겨주세요.
> 소스의  경우 \`\`\` 을 넣고 코드를 넣은 다음 \`\`\` 하시면 소스코드가 보기좋게 올라갑니다.
> https://guides.github.com/features/mastering-markdown/ 참조
> 이미지 캡쳐의 경우엔 에디터 아래있는 selecting them를 누르시거나 모던브라우저의 경우 이미지를 드래그 & 드랍할수 있습니다.

### axisj 좋아요 꼭 눌러주세요
![2014-12-21 1 52 30](https://cloud.githubusercontent.com/assets/5884902/5515587/0f94cff0-88b4-11e4-9a6f-5a2f7e0f25be.png)
여기 있는 Star를 해주셔야 합니다.
> 저희는 오픈소스 이고 이런 활동을 해서 경제적 이득을 얻지 않습니다. 여러분의 관심과 사랑을 먹고 사는 거지요. 그외엔 후원을 받고는 있지만 개인 분들이 후원 할 수 있을 거라곤 기대 하지 않습니다. 해주시면 정말 좋구요 ㅜ.ㅜ
https://www.axisj.com/ko/portal/donation
여기로 가시면 작게나마 후원할 수 있는 방법들이 ~ 하지만 꼭 하지 않으셔도 저희는 열심히 답변을 달 수 있습니다.
:+1: 

### 질문을 하실땐 라이브러리 네임을 영문으로 기재해 주세요.
`AXGrid` 메소드명 `setList` 해주시면 보다 정확하고 확실한 답변을 드릴 수 있고 다른 질문을 하는 분께도 도움이 되겠습니다.

**Comment by medianpro** [comment]
항상 응원합니다~
