### ISSUE TITLE
그리드 기능 구현 질문입니다 ~~

### ISSUE THREAD

**Issue by david80** [axisj/axisj#509]
![1](https://cloud.githubusercontent.com/assets/11273651/6958524/40a9da7e-d948-11e4-9e73-7d1501127c05.png)

입차번호에 해당되는 상품이 여러개 붙어져 있는데 머지를 해서 지금처럼 나오고 있습니다.
체크박스를 입차번호에 체크박스를 하나씩 넣고 싶은데 가능한지..

샘플 봐도 그런게 없더라구요~

**Comment by tom-axisj** [comment]
가능한 방법을 고민해서 답변 드리겠습니다.
