### ISSUE TITLE
AX에디트 추가기능 건의입니다.

### ISSUE THREAD

**Issue by david80** [axisj/axisj#511]
테이블 만드는 표가 없던데.. 
추가할 예정인지?? 궁금하네요~

**Comment by hyunjun19** [comment]
답변이 많이 늦어서 죄송합니다.
가끔 저희가 놓치는 질문도 있습니다. ㅠㅠ

일단 답변을 드리자면 에디터는 전면 개편을 할 예정은 있으나 일정은 아직 확실히 잡힌게 없습니다.
따라서 표를 만드는 기능도 아직 예정이 없습니다.
