### ISSUE TITLE
AXTree 질문있어요~

### ISSUE THREAD

**Issue by gurm4dari** [axisj/axisj#513]
Virtualization Scrolling 기능(스크롤에 보여지는 페이지만 실시간 렌더링)은 현재 구현중이라고 밑에 코멘트에 본거 같은데 언제쯤 release예정인지요?

BigData제공하는 Tree기능은 다른 곳에서도 찾기 힘든 유니크기능이라.. 궁금합니다!

**Comment by tom-axisj** [comment]
새 트리가 완성은 되었습니다만 기존 트리가 가진 메소드를 다 적용하지 못해서 공개 못하고 있습니다.
기능이 부족한 트리라도 쓰시겠다면 다음주안에는 오픈이 가능하겠습니다.

**Comment by gurm4dari** [comment]
네 베타버전이라도 공개해주신다면 감사하겠습니다!
