### ISSUE TITLE
fixedColSeq 적용시 정렬 문제

### ISSUE THREAD

**Issue by beginnerkht** [axisj/axisj#515]
var pageID = "ajax";
		var myGrid = new AXGrid();
		var mySearch = new AXSearch();
		var myModal = new AXModal();
		var myUpload = new AXUpload5();

		var fnObj = {
		    pageStart: function(){
		        fnObj.grid.init();
		    },
		    pageResize: function(){

		    },
		    grid: {
				init: function () {
						myGrid.setConfig({
							targetID: "AXGridTarget",
							theme: "AXGrid",
							fixedColSeq:0,
							colGroup: [
								{ key: "regno", label: "개체식별번호", width: "150", align: "center", formatter: "dec" },
								{ key: "BM1824_1", label: "c1", width: "50", align: "center"},
								{ key: "BM1824_2", label: "c2", width: "50", align: "center"},
								{ key: "BM2113_1", label: "c1", width: "50", align: "center"},
								{ key: "BM2113_2", label: "c2", width: "50", align: "center"},
								{ key: "ETH10_1", label: "c1", width: "50", align: "center"},
								{ key: "ETH10_2", label: "c2", width: "50", align: "center"},
								{ key: "ETH225_1", label: "c1", width: "50", align: "center"},
								{ key: "ETH225_2", label: "c2", width: "50", align: "center"},
								{ key: "ETH3_1", label: "c1", width: "50", align: "center"},
								{ key: "ETH3_2", label: "c2", width: "50", align: "center"},
								{ key: "INRA23_1", label: "c1", width: "50", align: "center"},
								{ key: "INRA23_2", label: "c2", width: "50", align: "center"},
								{ key: "SPS115_1", label: "c1", width: "50", align: "center"},
								{ key: "SPS115_2", label: "c2", width: "50", align: "center"},
								{ key: "TGLA122_1", label: "c1", width: "50", align: "center"},
								{ key: "TGLA122_2", label: "c2", width: "50", align: "center"},
								{ key: "TGLA126_1", label: "c1", width: "50", align: "center"},
								{ key: "TGLA126_2", label: "c2", width: "50", align: "center"},
								{ key: "TGLA227_1", label: "c1", width: "50", align: "center"},
								{ key: "TGLA227_2", label: "c2", width: "50", align: "center"},
								{ key: "TGLA53_1", label: "c1", width: "50", align: "center"},
								{ key: "TGLA53_2", label: "c2", width: "50", align: "center"}
							],

							colHead : {
								rows: [
									[
										{colSeq:0, rowspan:2, valign:"middle"},
										{colSeq:null, colspan:2, label:"BM1824", align:"center"},
										{colSeq:null, colspan:2, label:"BM2113", align:"center"},
										{colSeq:null, colspan:2, label:"ETH10", align:"center"},
										{colSeq:null, colspan:2, label:"ETH225", align:"center"},
										{colSeq:null, colspan:2, label:"ETH3", align:"center"},
										{colSeq:null, colspan:2, label:"INRA23", align:"center"},
										{colSeq:null, colspan:2, label:"SPS115", align:"center"},
										{colSeq:null, colspan:2, label:"TGLA122", align:"center"},
										{colSeq:null, colspan:2, label:"TGLA126", align:"center"},
										{colSeq:null, colspan:2, label:"TGLA227", align:"center"},
										{colSeq:null, colspan:2, label:"TGLA53", align:"center"}
									],
									[
										{colSeq:1},
										{colSeq:2},
										{colSeq:3},
										{colSeq:4},
										{colSeq:5},
										{colSeq:6},
										{colSeq:7},
										{colSeq:8},
										{colSeq:9},
										{colSeq:10},
										{colSeq:11},
										{colSeq:12},
										{colSeq:13},
										{colSeq:14},
										{colSeq:15},
										{colSeq:16},
										{colSeq:17},
										{colSeq:18},
										{colSeq:19},
										{colSeq:20},
										{colSeq:21},
										{colSeq:22}
									]
								]
							},

							body: {
								onclick: function () {
								}
							},
							page: {
								paging: true,
								pageNo: 1,
								pageSize: 15,
								status: { formatter: null }
							}
						});
					
			        fnObj.grid.search();
			    },
			    
			    search: function () {
			    	var pars = "regno="+$("#regno").val();
					myGrid.setList({
                        ajaxUrl: "sub02_4_list.html", ajaxPars: ""+pars,
                        onLoad: function(){
                            //myGrid.click(1);
                            myGrid.setFocus(1);
                        }
                    }); //서버에서 받아오는 방식으로 구현할때.
					return;
			    },
				save: function(){
					var f = document.form1;
					if(f.userfile.value == false) {
						alert('파일첨부를 확인하세요.');
						return;
					}
					var url = "sub02_3_cmd.html?mode=mother";
					if(!confirm("저장 하시겠습니까?")) return;
					mask.open();
					loading_view.style.display = "";
					f.action = url;
					f.submit();
				}
			}
	    };
		jQuery(document.body).ready(function() {
			setTimeout("fnObj.pageStart();", 1000);
		});

해당 소스에서 

fixedColSeq 적용한 다음부분인

{ key: "BM1824_1", label: "c1", width: "50", align: "center"}, 

이 부분에서 정렬이 적용되지 않는 문제가 발생하였습니다.

fixedColSeq을 적용하지 않았을 때에는 정상적으로 정렬이 됩니다.

어떠한 문제가 있는건지 답변 부탁드리겠습니다.

**Comment by KimJM** [comment]
올려주신 소스 그대로 적용하니 정상적으로 나옵니다만..
전에 valign 관련 문제 때문에 최신 라이브러리로 받으신걸로 기억하는데 캐시 문제일 수도 있을것 같구요, 
아니면 dev 브랜치로 다시 받으셔서 테스트 해보시기바랍니다.

![screen shot 2015-04-07 at 10 56 48 am](https://cloud.githubusercontent.com/assets/5627281/7015800/dd8fd53a-dd14-11e4-9f16-20e6da524ffc.png)

**Comment by beginnerkht** [comment]
![capture](https://cloud.githubusercontent.com/assets/10544023/7015963/5235f94e-dd17-11e4-9d5f-2d9a027c9c34.jpg)

해당칼럼 클릭시 반응이 없습니다.

확인 부탁드리겠습니다

**Comment by m3rri** [comment]
fixedColSeq 속성 사용했을 때 고정된 열에 인접한 칼럼을 클릭했을 때 정렬되지 않고, resizer가 작동하지 안는 문제 때문에 구글링하다가 이 페이지를 보게되었습니다.
다른 분들은 어떻게 해결하셨는지 모르겠지만 다른 해결방안을 못 찾아서 AXGrid.js 에서 아래와 같이 수정했습니다.
rows가 2개이상일 때 bottom에 해당하는 row에 대해서는 tr을 생성할 때 ghost 속성을 false로 지정했습니다.

> **var ghostYn = false;
                            if(r==0){
                            	ghostGbn = (colCount < (cfg.fixedColSeq + 1));
                            }**

> po.push(getColHeadTd({
  valign: valign,
                                rowspan: rowspan,
                                colspan: colspan,
                                bottomClass: bottomClass,
                                r: r,
                                CHidx: CHidx,
                                align: (cfg.colHeadAlign || CH.align || "left"),
                                colSeq: CH.colSeq,
                                formatter: CH.formatter,
                                formatterLabel: CH.formatterLabel,
                                sort: CH.sort,
                                colHeadTool: CH.colHeadTool,
                                tdHtml: tdHtml,
                                _**ghost: ghostGbn**_ // (colCount < (cfg.fixedColSeq + 1)),
                                tdHeight: (function () {
                                    if (cfg.colHead.heights && cfg.colHead.heights[r]) {
                                        var tdHeight = 0;
                                        for (var i = r; i < r + (CH.rowspan); i++) {
                                            tdHeight += (cfg.colHead.heights[i] || 0);
                                        }
                                        return tdHeight;
                                    }
                                    else {
                                        return _tdHeight * (CH.rowspan || 1) + (CH.rowspan - 1);
                                    }
                                })()
                            }));
