### ISSUE TITLE
grid 넓이 및 높이 동적으로 적용 방법 문의

### ISSUE THREAD

**Issue by ddangggoma** [axisj/axisj#520]
현재 AXGrid를 사용하고자 하여 검토중에 있습니다.
그 중 현재 AXGrid에서 width를 동적으로 적용하기 위하여 "fitToWidth  : true"라는 옵션이 있는것을 확인했는데요, 혹시 height에는 그런 옵션이 존재 하지 않나요? auto로 하면 컨테이너 div에 스크롤이 생겨 가상 리스트도 적용되지 않고 스크롤도 div에 생겨 의도한 바와는 다른것 같습니다.
혹시 width나 height에 100%나 calc(100% - 000px) 과 같은 옵션이 적용 가능한지 문의 드립니다.

**Comment by hyunjun19** [comment]
100%나 calc 기능은 없습니다.
웹에서 컨테이너의 높이에 100% 차게 만드는 일은 간단하지 않고 항상 이슈가 되고 있습니다.
해당 기능은 개인적으로 저도 구현하려고 고민하고 있는 기능입니다만 언제 구현될지 

대신 [여기](https://github.com/axisj-com/axu4j/blob/master/axu4j-egovframe/src/main/webapp/WEB-INF/jsp/split.jsp#L172)를 참고 하시면 도움이 될꺼 같습니다.
