### ISSUE TITLE
샘플 코드 inline-edit.html 에서 버그?

### ISSUE THREAD

**Issue by kkpara** [axisj/axisj#527]
상태칼럼이 안변하는 경우가 있네요

http://dev.axisj.com/samples/AXGrid/inline-edit.html

에서 
String : 수정시 변함
combobox : U 표시가 안됨
date : U 표시가 안됨
money :  U 표시가 안됨
number : U 표시가 안됨
check : 수정시 변경됨

추가 버튼을 누르면 변경 _CUD 값이 반영되고 콘솔로 찍어보면 값은 변해있더군요
버그가 맞는것이려나요?

**Comment by tom-axisj** [comment]
이 현상은 버그는 아니구요.


```
{
       key:"string", label:"String", width:"200",
       editor: {
              type: "text",
              updateWith: ["_CUD"]
       }
,
```

를 보시면 updateWith가 _CUD 컬럼을 업데이트 해주는 데요.
표시가 안되는 컬럼은 이 설정이 없어서 그런 것입니다.

**Comment by kkpara** [comment]
{key:"_CUD", label:"상태", width:"40", align:"center"}, 이런식으로 쓰는 경우는 알려주신것이 동작하는데
예제의
{
                        key:"status", label:"상태", width:"40", align:"center", formatter:function(){
                        if(this.item._CUD == "C"){
                            return "신규";
                        }else if(this.item._CUD == "D"){
                            return "삭제";
                        }else if(this.item._CUD == "U"){
                            return "수정";
                        }
                    }}, 
이런 형태의 쓰임에서는 반영이 안되는군요
값을 변경하고 console.log(myGrid.getList("C,U,D", true)) 로 계속 찍어보면
updateWith 항목을 정의를 안해주더라도 cud 값이 변경된것이 나오고 있고, 표기가 안되는 상태에서도
myGrid.pushList() 해보면 상태값 바뀐게 그리드에 표시 되어서 말이죠

**Comment by hyunjun19** [comment]
`updateWith: ["_CUD", "status"]` 이렇게 해보시겠어요?
이렇게 하면 `_CUD`의 값이 변경되고 그 다으므 `status` 컬럼의 `formatter`메서드도 변경될 껍니다.
`updateWith` 옵션에 변경된 값을 적용하고 싶은 컬럼을 다 지정해 주셔야 합니다.
