### ISSUE TITLE
샘플 코드 inline-edit.html 에서 문의점2

### ISSUE THREAD

**Issue by kkpara** [axisj/axisj#528]
```js
beforeUpdate: function(val){ // 수정이 되기전 value를 처리 할 수 있음.
  // 선택된 값은 
  console.log(val);
  return val;
},
afterUpdate: function(val){ // 수정이 처리된 후
  // 수정이 된 후 액션.
  console.log(this);
}
```
위의 설정에 의하여 샘플을 보면 콘솔에 찍히는데요

상황 :  selectbox 칼럼 선택후 값 변동 없이 취소상황 ( esc키는 이벤트 발생 안함, selectbox 밖의 영역을 눌러 취소 시키는 경우 ) 을 2회 발생시킴

1회차에서는 원래 값이 selectbox 에 선택되어서 나오고 콘솔의 값이 선택된 값으로 나옴
2회차에서는 selectbox 첫번째 값으로 변동되어 표시 되며 콘솔의 데이터 또한 병동되어 나옴

의문점 : 
1.selectbox 변경 없이 다른영역을 선택 했는데 update 이벤트는 발생안하여야 하는것이 아닌가?
2. 2회차에서 optionlist 의 첫번째 값으로 변경되고 그 값이 콘솔에 출력됨 
  이경우 콘솔에 나타난 데이터는 변동이 이루어졌는데 화면상으로는 변동이 안나타나고 있음(selectbox) 선택하여 리스트를 보아야 값이 바뀌어 있는것을 알수 있음

위상황을 피하려면 어떻게 해야 할련지요?

**Comment by hyunjun19** [comment]
@tom-axisj 1번 의도를 알려주세요~
2번은 저희가 재현을 해보려면 좀 더 자세한 설명이 필요합니다. 가능하면 콘솔로그나 스크린샷을 첨부하시면 큰 도움이 됩니다.

@tom-axisj 그리고 https://github.com/axisj-com/axisj/blob/dev/lib/AXGrid.js#L5537 여기는 아래처럼 해야 수정이 되기전 value인거 같습니다. 
```js
//value = CG.editor.beforeUpdate.call(that, value);
value = CG.editor.beforeUpdate.call(that, item[CG.key]);
```
