### ISSUE TITLE
inline-edit 질문입니다.

### ISSUE THREAD

**Issue by solarware-lee** [axisj/axisj#539]
그 저번에 고쳐주신 inline-edit에서 한 컬럼 수정 후 마우스로 다른 컬럼 클릭시 업데이트되는거 약간의 오류가 있어서 문의드립니다.

행이
```
editor: {
   type: "number",
  updateWith: ["status"]
}
```
editor가 있는 행을 클릭시 수정이 되는데
editor가 없는 행을 클릭하면 수정이 안되더라구요. 

확인한번 부탁드리겠습니다.

**Comment by tom-axisj** [comment]
패치 되었습니다.
