### ISSUE TITLE
AXSelect에서 특정 특수문자가 안나오는것 같아요

### ISSUE THREAD

**Issue by Jang7807** [axisj/axisj#542]
![default](https://cloud.githubusercontent.com/assets/8776414/7247110/b13789ec-e840-11e4-8455-d057990cf0ae.png)
AXSelect에서 특수문자 '+' 를 넣으면 나올때가 있고 안되는 경우가 있는데 옵션에 특수 문자 입력시 확인해야 할 사항이 있나요?

**Comment by tom-axisj** [comment]
이 이슈는 문자열 encode, decode에 관련된 이슈 입니다.
내부에서 .enc(), .dec()라는 함수로 문자열을 encoding, decoding 하는데요.
서버쪽에서 문자열을 encoding해서 클라이언트로 넘길때 공백문자와 + 문자가 모두 +로 오게 됩니다.
난감하죠 ㅡㅡ;;

그래서 + 문자를 공백으로 치환하는 작업을 dec()함수에서 하게 됩니다.
그리고 select 내부에서 optionText를 출력할 때 dec를 해주고 있습니다.
만약 이부분이 이해 못하시겠다면

```
String.prototype.dec = function(){
  return decodeURIComponent(this);
}
```

라고 axj.js 파일뒤에 추가 해주시면 변경됩니다.
ajax를 json으로만 처리하신다면 프로토타입 dec를 위와 같이 변경 해버리고 사용하시면 되겠습니다.
