### ISSUE TITLE
inline-edit 관련 질문드립니다. 

### ISSUE THREAD

**Issue by wonder789** [axisj/axisj#550]
var myGrid = new AXGrid(); // instance
var fnObj = {
    pageStart: function(){

        myGrid.setConfig({
            targetID : "example",
            theme : "AXGrid",
            viewMode : 'grid',
            mediaQuery: {
                mx:{min:0, max:600}, dx:{min:600}
            },
            colGroup : [
                {key:"no", label:"No.", width:"40", align:"center", formatter:"money",
                	editor : { type : 'money'}},
                {key:"title", label:"Title", width:"200",editor : { type : 'text'}},
                {key:"writer", label:"Writer", width:"100", align:"center"},
                {key:"date", label:"Date.", width:"100", align:"center"},
                {key:"desc", label:"Etc.", width:"*"}
            ],
            body : {
                onclick: function(){
                   
                }
            },
            page:{
                paging:false
            }
        });

        var list = [
            {
                no:1, title:"AXGrid 첫번째 줄 입니다.AXGrid 첫번째 줄 입니다.", writer:"장기영", img:"img/1.jpg", desc:"많은 글을 담고 있는 내용 입니다. 자연스럽게 줄이 넘어가고 표현되는 것이 관건 입니다.", category:"액시스제이", date:"2014-04-05"
            },
            {
                no:2, title:"AXGrid 두번째 줄 입니다.AXGrid 첫번째 줄 입니다.", writer:"장기영", img:"img/2.jpg", desc:"많은 글을 담고 있는 내용 입니다.", category:"액시스제이", date:"2014-04-07"
            },
            {
                no:3, title:"AXGrid 세번째 줄 입니다.AXGrid 첫번째 줄 입니다.", writer:"장기영", img:"img/3.jpg", desc:"많은 글을 담고 있는 내용 입니다. 자연스럽게...", category:"액시스제이", date:"2014-04-09"
            }
        ];

        //setList
        myGrid.setList(list);
        /* ajax way
        myGrid.setList({
            ajaxUrl:"...",
            ajaxPars:"",
            onLoad:function(){},
            onError:function(){}
        });
        */
    }
};
jQuery(document).ready(fnObj.pageStart.delay(0.1));

홈페이지에 있는 샘플 코드를 받아서 실행해보았는데요
inline-edit 기능이 mobile 에서는 안되는것 같습니다. 
mobile 에서는 원래 지원하지 않는 기능인지 궁금합니다.

**Comment by tom-axisj** [comment]
현재 버전으로 mobile에서 inline-eidt를 지원하지 않습니다. 
modile 을 안쓰려면 mediaQuery 를 제거하세요

**Comment by wonder789** [comment]
mobile 에서 inline-edit 기능이 향후에 추가될 계획이 있는건지 궁금합니다. 빠른답변감사합니다.

**Comment by tom-axisj** [comment]
inline-edit 기능이 안정화 되면 추가할 계획입니다
