### ISSUE TITLE
AXInput:Selector에서 optionValue 값 가지고 오는 방법 문의

### ISSUE THREAD

**Issue by Jang7807** [axisj/axisj#554]
항상 친절한 답변 감사합니다.

jQuery("#AXInputSelector1").val() 으로 하면 optionValue값을 가지고 오는 줄 알았는데 
optionText값만 가지고 오네요.... ㅜㅜ

샘플하고 API 찾아 봤지만 optionValue 값을 간단하게 가지고 올 수 있는 방법을 못찾아서
문의드립다.

**Comment by tom-axisj** [comment]
selector 에서 값을 뽑아내려면 onchange에서 스크립트로 받아써야 합니다.
