### ISSUE TITLE
AXUpload5 에서 질문입니다.

### ISSUE THREAD

**Issue by Jo-Jong-gyun** [axisj/axisj#559]
파일을 업로드 했을때 IE8이나 IE9에서는 브라우저단에서 파일사이즈 체크가 되지 않아
서버에서 error 응답을 해서 처리 하려고 합니다.

서버에서 HTTP 500 에러를 떨궈줘도 AXISJ 에서 파일업로드가 정상 처리가 되는데 어떻게 해야될지 
모르겟습니다. 참고할 수 있는 예제나 혹은 방법이 있는지요...

**Comment by hyunjun19** [comment]
SWFUpload(IE8, IE9) 모드에서 파일 사이즈 초과시 onError 메서드 호출하도록 수정했습니다.
7e56da1f4deb3308803ba1b773ae1fc424293d0d 여기에 dev 브랜치에 반영되어 있습니다.

**Comment by tom-axisj** [comment]
:+1;

**Comment by tom-axisj** [comment]
:+1:

**Comment by hyunjun19** [comment]
테스트 해보시고 이상 없으면 이슈 Close 해주세요.

오른쪽 상단에 스타도 눌러 주시면 개발자들에게 큰 힘이 됩니다. =)

**Comment by jjori-master** [comment]
@hyunjun19 

죄송합니다. 그때는 개념이 없어서 Close 못했네요ㅠㅠ

답변 정말 감사드립니다~~
