### ISSUE TITLE
IE에서 AXUpload5를 사용하는데 드래그앤드랍 파일첨부 안됨

### ISSUE THREAD

**Issue by wann2** [axisj/axisj#573]
안녕하세요.

크롬에서는 작동하는데, IE에서는 AXUpload5에서 영역내로 드래그앤드랍 파일첨부가 작동하지 않고 있습니다.

**Comment by hyunjun19** [comment]
AXUpload5의 D&D 기능은 HTML5 file을 이용한 기능입니다. 따라서 해당 기능을 지원하지 않는 브라우저(IE9 이하)에서는 D&D 기능을 사용할 수 없습니다.

**Comment by wann2** [comment]
버그 증상

1) 구글크롬에서 드래그앤드랍으로 여러사진을 첨부하면 박스에 사진이 업로드된 상태에서 모래시계만 뜨고 중지됩니다. 파일열기창에서 첨부하면 정상적으로 됩니다.

2) IE(버젼11)에서는 드래그앤드랍이 전혀 작동하지 않습니다. 업로드박스에는 "업로드할 파일을 여기에 놓습니다"라는 문구가 보입니다.

**Comment by hyunjun19** [comment]
콘솔창에서 오류메시지가 발생하지 않는지 확인해 주세요.
그냥 안된다고 하시면 답변을 드릴수가 없습니다.

현재 저희 데모 사이트(http://dev.axisj.com/samples/AXUpload5/index.html)에서는 이상없이 작동하고 있습니다.

뭔가 다른 환경때문에 발생하는 문제이기 때문에 최대한 많은 정보를 주셔야 답변을 드릴 수 있습니다.

**Comment by wann2** [comment]
1) 크롬에서는 https 사이트에서 실행할 때 드래그앤드랍으로 여러사진을 첨부하면 박스에 사진이 업로드된 상태에서 모래시계만 뜨고 중지됩니다. http 사이트에서는 정상적으로 작동합니다.

2) IE(버젼 11)에서는 http 사이트에서도 드래그앤드랍을 할 때 포인트커서가 금지아이콘(동그라미에 슬래쉬)으로 변하면서 드래그앤드랍이 안됩니다. 콘솔창에는 아무것도 뜨지 않습니다.
위에서 알려주신 AXUpload5 데모 사이트에서도 안됩니다. 화면첨부합니다.

![axupload5](https://cloud.githubusercontent.com/assets/8732515/7836137/01126600-04b9-11e5-8623-487d64be03fc.gif)

**Comment by hyunjun19** [comment]
1) https는 테스트해볼 수 있는 환경이 없어서 확인해 보기가 난감하네요. ㅠㅠ
2) 현재 IE가 플래시 모드인것 같습니다.
개발자 도구에서 브라우저 모드를 확인해 보세요.
혹시 모르니 콘솔에서 navigator.userAgent 정보를 찍어서 올려주세요.

**Comment by wann2** [comment]
navigator.userAgent 정보
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

![axupload5](https://cloud.githubusercontent.com/assets/8732515/7850936/4740eb32-0523-11e5-9a2d-417aab5ca90c.gif)

해당 스크립트는 아래처럼 했습니다.
myUpload.setConfig({
	targetID: 'AXUpload5',
	targetButtonClass: 'Green',
	uploadFileName: 'fileData',
	fileSelectAutoUpload: true,
	file_types: 'image/*',  //audio/*|video/*|image/*|MIME_type (accept)
	dropBoxID: 'uploadQueueBox',
	queueBoxID: 'uploadQueueBox', // upload queue targetID
	queueBoxAppendType: 'prepend',
	//queueBoxAppendType: '(prepend || append)',
	//openMode: 'view',
	// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도됨
	//flash_url : pageObj.host+'lib/swfupload.swf',
	//flash9_url : pageObj.host+'lib/swfupload_fp9.swf',
	flash_url : '/js/axisj/lib/swfupload.swf',
	flash9_url : '/js/axisj/lib/swfupload_fp9.swf',
	flash_file_types: '*.jpg;*.jpeg;*.gif;*.bmp;*.png',
	flash_file_types_description: 'image',

**Comment by hyunjun19** [comment]
https와 IE11에서 발생하는 D&D 문제는 저희 측에서 재현이 불가능해서 확인이 힘듭니다.
현재 주신 정보로는 이상을 확인할 수가 없습니다. ㅠㅠ

https는 저희가 접속해서 테스트 해볼 수 있다면 해당 url을 알려주세요.
그리고 IE11은 다른 PC에서 테스트 해보시기 바랍니다. 해당 PC의 다른 요소가 영향을 끼치고 있는것 같습니다.

**Comment by wann2** [comment]
넵. 조만간에 테스트 페이지 만들어 문의드리겠습니다.

**Comment by wann2** [comment]
1) korea7st.com/test 접속
2) 로그인 - 네이버/다음/구글 중 하나 선택(OAuth연동) - 일반회원 선택
3) 마이페이지의 매물관리 메뉴 클릭
4) 등록 버튼 클릭
5) 아무 주소나 입력 후 저장
6) 하단의 이미지/동영상 업로드 버튼 클릭
7) AXUpload5 드래그앤드랍 테스트
8) 테스트 후 회원탈퇴 - 모든 기록이 삭제됩니다.

**Comment by tom-axisj** [comment]
매물등록을 하려면 멤버쉽 승인이 필요하답니다.
tom@axisj.com 승인해주세요

**Comment by tom-axisj** [comment]
접속해서 보니 아코디언 식으로 UI를 구성하셨는데요.
display:none 된 상태에서 스크립트 바인딩을 해서 문제가 될 것 같습니다.
slidedown 완료 시에 AXUpload5를 바인딩 해보십시요.

그리고 지금 버전으로 업로를 안 붙여 두신게 아닌가 싶습니다.
업로드 누르면 아무것도 안나옵니다.
![2015-06-23 11 04 41](https://cloud.githubusercontent.com/assets/5884902/8307885/403f3436-19fc-11e5-8839-500b0fd2fb1b.png)

**Comment by wann2** [comment]
맨 처음 상단에서 주소(아무거나 상관없음)를 "저장"해야만 DB key가 생성되고, DB key가 있어야 업로드하는 이미지를 해당 주소의 DB key와 관계된 이미지라는 것을 알 수 있습니다.
그래서 맨 처음 상단의 주소를 "저장"해서 서버로부터 DB키를 받으면 그 때야 비로소 fnObj.pageStart.delay(0.1)을 실행합니다.
