### ISSUE TITLE
AXGrid관련 질문 입니다. 

### ISSUE THREAD

**Issue by leeYongchang** [axisj/axisj#576]
![default](https://cloud.githubusercontent.com/assets/12455168/7697884/c3273c94-fe46-11e4-9ef4-79fb62c4ae43.png)

멀티 그리드 사용 시 key이벤트 관련하여 처리 해 주셔서 고맙습니다. 

위 이미지 처럼 현재 그리드에서 합계를 보여주고 있는데 key이벤트 처리된 소스를 사용하여보니 그림에 아래와 같이 합계 출력이 정상적으로 출력되고 있지 않습니다. 

자꾸 이런 글을 올려 죄송합니다.

**Comment by tom-axisj** [comment]
foot 이 아래에 고정되도록 기능 수정 되었습니다. 
ui 폴더를 업데이트 안하신것으로 보입니다.

**Comment by leeYongchang** [comment]
넵 고맙습니다.
