### ISSUE TITLE
bindPattern관련

### ISSUE THREAD

**Issue by hajinhajin** [axisj/axisj#582]
안녕하세요, AXInput의 Pattern중 시간에 대한 Pattern은 따로 없는지요?

예: 1230 -> 12:30

감사합니다.

**Comment by tom-axisj** [comment]
time 패턴 추가 되었습니다. 감사합니다.

**Comment by hajinhajin** [comment]
안녕하세요, 답변 감사드립니다.

다름이 아니라 혹시 추가된 time패턴은 제가 수정 후 사용하여야하나요? 아니면 추후 릴리즈가 되는 사항인가요?

**Comment by hyunjun19** [comment]
현재 `dev` 브런치에 적용되어 있습니다.
지금 당장 수정이 필요하시면 https://github.com/axisj/axisj/tree/dev 여기에서 소스를 받아서 적용하시면 됩니다.

정식 릴리즈에는 추후 반영됩니다.

오른쪽 상단에 별을 눌러 주시면 개발자들에게 큰 힘이 됩니다. =)
