### ISSUE TITLE
AxGrid inline-Edit의 select 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by manoi83** [axisj/axisj#586]
안녕하세요.  AxGrid 사용중 궁금한 사항이 있어 문의드립니다.

AxGrid 의 inline-Edit 예제에 보면 combobox combobox2 이렇게 2개의 컬럼이 있는데요.

combobox 를 수정하게 되면 그 값과 연관된 값을 combobox2에 뿌려리게 하려는데 

방법을 몰라 가능한지 문의드립니다.

예를들면 아래 combobox 에 "시/도"를 선택하면 combobox2에는 선택한 "시/도"에 해당하는 "구"를 뿌려주고자 합니다.

combobox        |       combobox2
서울(선택 시)   |            강남구
경기도          |            송파구
충청도          |             중구                
전라도          |             노원구
경상도          |

현재는 처음 화면을 로드할때 그리드를 설정하면 추 후에 updateItem을 통해 일반 text는 변경 가능하지만 select 처리된 컬럼에 대해서는 목록에 대해 변경방법을 알수 없어 위 사항이 가능한지 검토 부탁드립니다.

감사합니다.

**Comment by tom-axisj** [comment]
아마도 정확히는 combobox2의 options를 동적으로 변경 하고 싶은신 것 같아요?

**Comment by manoi83** [comment]
맞습니다.^^

combobox 를 선택한 값에 따라 배열값 등을 불러와서 같은 라인의 combobox2 컬럼의 select option을 변경하고 싶습니다.

**Comment by tom-axisj** [comment]
```html
<select name="" class="AXSelect W100" id="ax-select1-01"></select>
&nbsp;
<select name="" class="AXSelect W100" id="ax-select11-02"></select>
```

```js
var parent_code;
var child_data = {
	"1": [
		{optionValue:1, optionText:"중구"},
		{optionValue:2, optionText:"명동"},
		{optionValue:3, optionText:"충무로"},
		{optionValue:4, optionText:"여의도"}
	],
	"2": [
		{optionValue:1, optionText:"수염"},
		{optionValue:2, optionText:"근육"},
		{optionValue:3, optionText:"아버지"},
		{optionValue:4, optionText:"아들"}
	],
	"3": [
		{optionValue:1, optionText:"긴머리"},
		{optionValue:2, optionText:"핸드백"},
		{optionValue:3, optionText:"어머니"},
		{optionValue:4, optionText:"딸"}
	],
	"4": [
		{optionValue:1, optionText:"키보드"},
		{optionValue:2, optionText:"마우스"},
		{optionValue:3, optionText:"모니터"},
		{optionValue:4, optionText:"노트북"}
	]
}


// 예약어 설정 안하고 AXConfig 속성 사용
$("#ax-select1-01").bindSelect({
	isspace: true,
	isspaceTitle: "-- 선택 --",
	options:[
		{optionValue:1, optionText:"서울"},
		{optionValue:2, optionText:"남성"},
		{optionValue:3, optionText:"여성"},
		{optionValue:4, optionText:"컴퓨터"}
	],
	onchange: function(){
		//trace("change : " + Object.toJSON(this));
		parent_code = this.optionValue;
		$("#ax-select11-02").bindSelectUpdateOptions([]);
	}
});

// 예약어 설정
$("#ax-select11-02").bindSelect({
	isspace: true,
	isspaceTitle: "-- 선택 --",
	onexpand: function(callBack){
		callBack({
			options: (parent_code) ? child_data[parent_code] : []
		});
	},
	onchange: function(){
		trace("change : " + Object.toJSON(this));
	}
});
```
http://dev.axisj.com/samples/AXSelect/select-onexpand.html

샘플코드와 기능을 추가했습니다. 
이번에 추가한 설정은 `onexpand` 입니다. 
onexpand는 옵션박스가 활성화 될 때 요청을 하므로 기능 구현이 가능하겠습니다.

**Comment by manoi83** [comment]
답변 주셔서 감사합니다.^^

혹시 위 기능을 AXGrid의 inline-edit 에서도 동일하게 사용 가능한가요?

**Comment by tom-axisj** [comment]
그리그안에 axselect 도 같은 클래스이니까요 되야합니다 ㅎㅎ

**Comment by manoi83** [comment]
새로운 기능을 만들어주시다니...^^;;

알려주신 기능은 적용해보겠습니다.

좋은 소스 제공해주셔서 항상 감사합니다.
