### ISSUE TITLE
dialog 실행시 함수에 데이터 parameter를 어떻게 넘겨주나요?

### ISSUE THREAD

**Issue by llois** [axisj/axisj#588]
```js
$("input[name='orderAccount.AccountChk']").change(function () {
        dialog.push({
            body: '<b>"입금상태"</b> 를 변경 하시겠습니까?', top: 120, type: '', buttons: [
                { buttonValue: '변경', buttonClass: 'Red W100', onClick: $.EditOrderAccountChk, data: '1' },
                { buttonValue: '취소', buttonClass: 'W100', onClick: $.EditOrderAccountChk, data: '0' }
            ]
        });
    });
```

예제에 있는 대로 이런식으로 Confirm창 대신에 dialog를 이용하려고 합니다.

위에 코드에 있는대로 EditOrderAccountChk 라는 함수를 실행시키려고 하는데,

혹시 이 EditOrderAccountChk라는 함수에 별도의 파라메터를 전달 할 수 있나요?

인자가 없는 함수는 실행시켜서 arg가 1일 경우에 그대로 실행시키면 되는데,

EditOrderAccountChk에 EditOrderAccountChk('aa') 이런식으로 인자를 넘기면 됬다가 안됬다가 하는 현상이 발생하는거 같습니다.

항상 감사합니다!

**Comment by hyunjun19** [comment]
`EditOrderAccountChk('aa')` 이런식으로 인자를 넘긴다는게 메서드를 js에서 직접 호출하신다는 이야긴가요? 좀 더 자세한 설명이 필요합니다. =)

**Comment by llois** [comment]
음... 필요한건 dialog에서 특정버튼 (일반적으로 첫번쨰 번튼)을 클릭할 시 Jquery 함수(인자를 포함한)를 실행 시키고 싶습니다.

axisj 사이트에 저렇게 예제가 되어 있어서 저렇게 구현 했는데

다른 방법이 있다면 알려주셔도 감사합니다^^

**Comment by hyunjun19** [comment]
`$.EditOrderAccountChk` 메서드가 어떻게 구현되어 있는지 보여주세요.(민감한 부분은 가리고 보여주세요)

**Comment by llois** [comment]
아 저메서드는 제가 임의로 했던거구요,

작동이 제대로되지 않았던 것은

  $.ProductDelete = function (orderProductID, orderBoxID) {
        if (confirm("제품을 삭제 하시겠습니까?")) {
            $("#AjaxLoading").show();
            $.ajax({
                url: "OrderProductDelete?orderProductID=" + orderProductID,
                type: "GET",
                success: function (data) {
                    $("#OrderProductTr_" + orderProductID).animate({ backgroundColor: 'yellow' }, 400).fadeOut(400, function () { $("#OrderProductTr_" + orderProductID).remove(); });
                    //$("#OrderProductTr_" + orderProductID).remove;

                    $.CalcTotalPrice(); //전체 제품 합계금액 재계산
                    $.CalcBoxPrice(orderBoxID); //박스 제품 합계금액 재계산
                    toast.push("제품삭제 완료"); //완료메세지

                    //$.SuccessFade("#lblOrderStatusType_" + data); //완료효과
                    $("#AjaxLoading").hide();
                },
                error: function (xhr, status) {
                    $("#AjaxLoading").hide();
                    toast.push({ body: '주문삭제 실패', type: 'Warning' }); //실패메세지
                }
            });
        }

이것 입니다.
그냥 일반적인 AJAX입니다.현재 컨펌으로 바꾼 후 잘 사용하고 있습니다.
DIALOG로 꼭 사용하고 싶습니다 ㅠㅠ

**Comment by hyunjun19** [comment]
아래처럼 사용해 보세요.
`axConfirm` 함수는 공용 함수로 만들어 사용하시면 편합니다.

```js
function axConfirm(message, cbConfirm) {
    function fnCallCallback(data) {
        if ($.isFunction(cbConfirm)) {
            cbConfirm.call(this, data);
        }
        mask.close();
    }

    mask.open();
	dialog.push({
		title	: "Confirm",
		type	: "Caution",
		top		: (document.body.clientHeight / 2 - 180),
		body	: message,
		buttons	: [
			{ buttonValue: "예",	buttonClass: "Red W60", data: "Y", onClick: fnCallCallback },
			{ buttonValue: "아니오",buttonClass: "Blue W60", data: "N",onClick: fnCallCallback }
		]
	});
}

$.ProductDelete = function (orderProductID, orderBoxID) {
	axConfirm("제품을 삭제 하시겠습니까?", function(data){
		if (data !== "Y") { return; }
		
		$("#AjaxLoading").show();
		$.ajax({
			url: "OrderProductDelete?orderProductID=" + orderProductID,
			type: "GET",
			success: function (data) {
				$("#OrderProductTr_" + orderProductID).animate({ backgroundColor: 'yellow' }, 400).fadeOut(400, function () { $("#OrderProductTr_" + orderProductID).remove(); });
				//$("#OrderProductTr_" + orderProductID).remove;

				$.CalcTotalPrice(); //전체 제품 합계금액 재계산
				$.CalcBoxPrice(orderBoxID); //박스 제품 합계금액 재계산
				toast.push("제품삭제 완료"); //완료메세지

				//$.SuccessFade("#lblOrderStatusType_" + data); //완료효과
				$("#AjaxLoading").hide();
			},
			error: function (xhr, status) {
				$("#AjaxLoading").hide();
				toast.push({ body: '주문삭제 실패', type: 'Warning' }); //실패메세지
			}
		});
	});
}
```

**Comment by llois** [comment]
으아... 이런 방법이 있군요 ㅠㅠ 혼자 고민 많이 했었는데 ㅠㅠ

감사합니다!  적용 해보고 피드백 남기겠습니다!!

**Comment by tom-axisj** [comment]
:+1:

**Comment by llois** [comment]
너무 잘 됩니다.
감사합니다! 개인적으로 욕심이 있다면

버튼을 여러개 넣을 수 있는 만큼 일반 confirm보다 기능면에서 월등 하지만
답변 달아주신것처럼 별도의 기능과 같이 Axisj에 포함된다면

confirm기능 자체가 워낙 많이 쓰이기 때문에 좋지 않을까 하는 생각입니다^^

감사합니다!

**Comment by tom-axisj** [comment]
```Javascript
{ buttonValue: '변경', buttonClass: 'Red W100', onClick: $.EditOrderAccountChk, data: '1' },
{ buttonValue: '취소', buttonClass: 'W100', onClick: $.EditOrderAccountChk, data: '0' }
```
에서 보시면 data 가 onClick 함수의 인자가 됩니다. 
data: {a:1} 이라면 $.EditOrderAccountChk 의 아규먼트가 {a:1} 이 됩니다.
