### ISSUE TITLE
그리드 헤더 부분의 체크박스를 클릭할경우

### ISSUE THREAD

**Issue by david80** [axisj/axisj#590]
이벤트를 제어 할수 있나요?

이벤트를 제어할수 있다면 전체체크박스를 클릭할경우 이벤트안에서 뭔가 제어를 하고 싶습니다.

예) 전체체크박스를 클릭할경우 그리드의 전체체크된 수량만큼 합산해서 합한수량을 보여줄려고 합니다.

**Comment by tom-axisj** [comment]
```
{
key:"no", label:"번호", width:"50", align:"center", formatter:"checkbox", 
oncheck: function(){
    alert("oncheck");
}
,
```
colGroup > item에 oncheck 추가하세요.
