### ISSUE TITLE
AXGrid - autoHeight 설정 시, 브라우저 스크롤 강제이동문제

### ISSUE THREAD

**Issue by writtenbyme** [axisj/axisj#591]
데이터를 full load 해 놓고 inline-editor를 이용하여 수정하는 그리드를 구현하였습니다.
height: "auto"로 설정해 놓으니, 데이터가 화면의 크기를 넘어가도  브라우저에 스크롤이 생겨 모든 데이터를 쉽게 확인 할 수 있었습니다. 
문제는 수정을 원하는 영역의 editor을 활성화하기 위해 클릭을 하니, 브라우저의 스크롤이 상단으로 이동해 버리는 현상이 발생합니다. 그리드 클릭시 스크롤이 강제로 이동하지 않게 할 방법이 있을까요?

제공해주신 autoHeight 소스를 이용해서 테스트를 해보았으나, 동일한 현상이 발생하였습니다.

**Comment by tom-axisj** [comment]
http://dev.axisj.com/samples/AXGrid/inline-edit-etc.html 에서도 그러신가요?
예상되는 조건으로 셋팅을 해보았는데요. 잘 못찾겠네요

**Comment by writtenbyme** [comment]
우선 빠른 답변 감사드립니다. ^^
그리드의 헤드가 화면에 보이는 상태에서는 발생을 하지 않는 것 같습니다. 
그리드의 height가 한 화면을 넘게 데이터를 추가하고, 헤드가 사라질 정도로 스크롤을 내린 후 그리드를 클릭하면 강제로 헤드가 보이는 위치로 스크롤이 이동하는 현상이 발생합니다.

**Comment by writtenbyme** [comment]
우선 빠른 답변 감사드립니다. ^^
그리드의 헤드가 화면에 보이는 상태에서는 발생을 하지 않는 것 같습니다. 
그리드의 height가 한 화면을 넘게 데이터를 추가하고, 헤드가 사라질 정도로 스크롤을 내린 후 그리드를 클릭하면 강제로 헤드가 보이는 위치로 스크롤이 이동하는 현상이 발생합니다.
아래 부분의 강제로 return 하는 코드를 추가하여서 현상은 막았으나 영향도를 알 수가 없네요 ㅠ
''' //this.target.bind("keydown", this.onKeydown.bind(this));
        //keydown 이벤트 방식 변경
        this.target.bind("click.axgrid", (function(e){
            if (this.editorOpend || this.inline_edit) return;
            var e = e||window.event;
            if(e.target.tagName == "INPUT"||e.target.tagName == "SELECT"||e.target.tagName == "TEXTAREA"||e.target.tagName == "BUTTON") return;
            //추가한부분
            if(cfg.height == 'auto') return;
            this.gridFocus.focus();
        }).bind(this));'''

**Comment by writtenbyme** [comment]
우선 빠른 답변 감사드립니다. ^^
그리드의 헤드가 화면에 보이는 상태에서는 발생을 하지 않는 것 같습니다. 
그리드의 height가 한 화면을 넘게 데이터를 추가하고, 헤드가 사라질 정도로 스크롤을 내린 후 그리드를 클릭하면 강제로 헤드가 보이는 위치로 스크롤이 이동하는 현상이 발생합니다.
아래 부분의 강제로 return 하는 코드를 추가하여서 현상은 막았으나 영향도를 알 수가 없네요 ㅠ
''' javascript
//this.target.bind("keydown", this.onKeydown.bind(this));
 //keydown 이벤트 방식 변경
this.target.bind("click.axgrid", (function(e){
 if (this.editorOpend || this.inline_edit) return;
 var e = e||window.event;
 if(e.target.tagName == "INPUT"||e.target.tagName == "SELECT"||e.target.tagName == "TEXTAREA"||e.target.tagName == "BUTTON") return;
 //추가한부분
if(cfg.height == 'auto') return;
 this.gridFocus.focus();
 }).bind(this));
'''

**Comment by writtenbyme** [comment]
우선 빠른 답변 감사드립니다. ^^
그리드의 헤드가 화면에 보이는 상태에서는 발생을 하지 않는 것 같습니다. 
그리드의 height가 한 화면을 넘게 데이터를 추가하고, 헤드가 사라질 정도로 스크롤을 내린 후 그리드를 클릭하면 강제로 헤드가 보이는 위치로 스크롤이 이동하는 현상이 발생합니다.
아래 부분의 강제로 return 하는 코드를 추가하여서 현상은 막았으나 영향도를 알 수가 없네요 ㅠ
```javascript
//keydown 이벤트 방식 변경
this.target.bind("click.axgrid", (function(e){
 if (this.editorOpend || this.inline_edit) return;
 var e = e||window.event;
 if(e.target.tagName == "INPUT"||e.target.tagName == "SELECT"||e.target.tagName == "TEXTAREA"||e.target.tagName == "BUTTON") return;
 //추가한부분
if(cfg.height == 'auto') return;
 this.gridFocus.focus();
 }).bind(this));
```
