### ISSUE TITLE
IE9에서 파일업로드할 때 파일첨부클릭 작동 안함

### ISSUE THREAD

**Issue by wann2** [axisj/axisj#596]
안녕하세요
IE9에서 파일업로드할 때 파일첨부버튼을 클릭하면 팝업창이 뜨지 않습니다.

< link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" / >

< ! - - [ if lt IE 9 ] >
< script src="/_jquery/jquery-1.11.1.min.js" > < / script >
< ! [ endif ] -- >
< ! - - [ if gte IE 9 ] > < ! - - >
< script src="/_jquery/jquery-2.1.4.min.js" > < / script >
< ! [ endif ] - - >
< ! - - [ if lt IE 9 ] >
< script src="/js/util/jquery.placeholder.js" > < / script >
< script src="/js/util/ie8.js" >< / script >
< script src="/js/util/respond.min.js" >
< script src="/js/util/html5.js" >< / script >
< ! [endif] -- >

< script src="/_bootstrap-3.3.4/js/bootstrap.min.js" >< / script >
< link rel="stylesheet" href="/_axisj/ui/arongi/AXJ.min.css" >

< script src="/_axisj/dist/AXJ.min.js" >< / script >
< script src="/_axisj/lib/AXCore.js" >< / script >
< script src="/_axisj/lib/AXInputPro.js" >< / script >
< script src="/_axisj/lib/AXUpload5.js" >< / script >
< / head >

소스 헤더는 위와 같은데 잘못된 스크립트첨부가 있는지요?

**Comment by hyunjun19** [comment]
콘솔에는 아무 로그도 안찍히나요?

그리고 bootstrap이랑은 CSS 충돌이 발생할 수도 있으니 bootstrap.min.css를 주석처리한 후 테스트 해보세요.

**Comment by wann2** [comment]
IE9에서 로그에 아래메시지가 나옵니다.
errorType === 'html5Support' 

그런데 IE9에서 http://dev.axisj.com/samples/AXUpload5/index.html 을 접속하면
파일올리기 버튼이 제대로 작동합니다.

제 소스에서는 모두 부트스트랩을 사용하여 현재는 제거할 수 없는 상황입니다.
IE9에서 파일올리기 버튼이 작동하도록 할 수는 없는건가요?

**Comment by hyunjun19** [comment]
`errorType === 'html5Support'` 이 오류는 HTML5의 file API를 지원하지 않는 브라우저에서 발생합니다.
`플래시 플레이어`를 설치하시거나 `브라우저 모드`를 확인해 보세요.

**Comment by tom-axisj** [comment]
브라우저 호환성 보기 모드가 작동하는것 같습니다.
웹페이지 헤더에 

`<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />`
를 넣어 IE가 최신모드가 되게 해야겠습니다.

**Comment by wann2** [comment]
meta 태그를 넣어도 안되는 군요

플래시 플레이어를 사용하려면 어떻게 해야 하나요?

var myUpload = new AXUpload5();

var fnObj = {
	pageStart: function() {
		fnObj.upload.init();
	},
	upload: {
		init: function() {
			myUpload.setConfig({
				targetID: 'AXUpload5',
				targetButtonClass: 'Green',
				uploadFileName: 'fileData',
				fileSelectAutoUpload: true,
				file_types: 'image/*',  //audio/*|video/*|image/*|MIME_type (accept)
				dropBoxID: 'uploadQueueBox',
				queueBoxID: 'uploadQueueBox', // upload queue targetID
				queueBoxAppendType: 'prepend',
				//queueBoxAppendType: '(prepend || append)',
				//openMode: 'view',
				// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
				//flash_url : pageObj.host+'lib/swfupload.swf',
				//flash9_url : pageObj.host+'lib/swfupload_fp9.swf',
				flash_url : '/_axisj/lib/swfupload.swf',
				flash9_url : '/_axisj/lib/swfupload_fp9.swf',
 				flash_file_types: '*.jpg;*.jpeg;*.gif;*.bmp;*.png',
				flash_file_types_description: 'image',
				// --------- e
				onClickUploadedItem: function() { // 업로드된 목록을 클릭했을 때.
					//trace(this);
					window.open(this.uploadedPath.dec() + this.saveName.dec(), 'K7_houseImg', 'width=500,height=300');
				},
				
				uploadMaxFileSize: (4*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈이며 서버에서 설정되는 값이 아닙니다.)
				uploadMaxFileCount: 10, // 업로드될 파일갯수 제한 0 은 무제한
				uploadUrl: '/Gen/house/imgUpload',
				uploadPars: {
					houseId: $('#houseId').val()
				},
				deleteUrl: '/Gen/house/imgDel',
				deletePars: {
					houseId: $('#houseId').val()
				},

				buttonTxt: '사진 첨부',
				
				fileKeys: { // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
					imgId: 'imgId',
					name: 'name',
					type: 'type',
					saveName: 'saveName',
					fileSize: 'fileSize',
					uploadedPath: 'uploadedPath',
					thumbPath: 'thumbUrl' // 서버에서 키값을 다르게 설정 할 수 있다는 것을 확인 하기 위해 이름을 다르게 처리한 예제 입니다.
				},
				
				onbeforeFileSelect: function() {
					//trace(this);
					return true;
				},
				
				onUpload: function() {
					//trace(this);
					//trace(myUpload.uploadedList); //업로드 json을 볼 수 있음
					//trace("onUpload");
				},
				onComplete: function() {
					//trace(this);
					//trace("onComplete");
					//$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
				},
				onStart: function() {
					trace(this);
					//trace("onStart");
					//$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
				},
				onDelete: function() {
					//trace(this);
					//trace("onDelete");
				},
				onError: function(errorType, extData) {
					if (errorType === 'html5Support') {
						dialog.push('귀하의 익스플로러 브라우져는 보안에 취약한 옛날버젼입니다.\n최신 버젼으로 업그레이드 하거나,\n또는 구글 크롬 브라우져를 사용을 권장합니다.\n\n익스플로러 업데이트방법:\nF10키-상단메뉴-도구-Windows 업데이트 메뉴\n구글크롬브라우져: www.google.com/chrome');
					} else if (errorType === 'fileSize') {
						//trace(extData);
						dialog.push('파일사이즈(4M)가 초과된 파일은 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n(' + extData.name + ' : ' + extData.size.byte() + ')');
					} else if (errorType === 'fileCount') {
						dialog.push('업로드 갯수(10장)를 초과한 파일은 업로드 되지 않습니다.');
					}
				}
			});
		},
		printMethodReturn: function(method, type) {
			var list = myUpload[method](type);
			//trace(list);
			toast.push(Object.toJSON(list));
		}
	},
	pageList: function() {
		var url = '/imgList';
		//var pars = 'dummy='+axf.timekey();
		new AXReq(url, {
			pars: 'houseId='+$('#houseId').val(), 
			onsucc: function(res) {
				if (!res.error) {
					myUpload.setUploadedList(res);
				} else {
					dialog.push(res.msg.dec());
				}
			}
		});
	}
};

**Comment by hyunjun19** [comment]
플레시 플레이어는 HTML5를 사용할 수 없는 경우 자동으로 사용됩니다.

지금 올려주신 스크립트에서 `uploadUrl: /imgUpload',` 여기는 수정하다가 실수하신거죠?

그리고 가능하시다면 저희가 볼수 있도록 해당 페이지 접근 URL을 열어주시는게 제일 확실합니다.
저희도 추측으로 체크해 볼 수 있는 사항은 거의 다 체크해 본거 같네요.

**Comment by wann2** [comment]
조만간에 별도의 페이지를 만들어서 URL을 알려드릴께요

**Comment by wann2** [comment]
1) korea7st.com/test 접속
2) 로그인 - 네이버/다음/구글 중 하나 선택(OAuth연동) - 일반회원 선택
3) 마이페이지의 매물관리 메뉴 클릭
4) 등록 버튼 클릭
5) 아무 주소나 입력 후 저장
6) 하단의 이미지/동영상 업로드 버튼 클릭
7) AXUpload5 파일첨부 테스트
8) IE9에서 errorType === 'html5Support'인 경우 현재 메시지만 뿌리게 했습니다.
9) 테스트 후 회원탈퇴 - 모든 기록이 삭제됩니다.

**Comment by hyunjun19** [comment]
네이티브 IE9는 지금 환경이 없어서 일단 IE10에서 IE9 모드로 테스트해봤는데 파일첨부버튼과 D&D도 잘 되네요.

혹시 증상이 나타나는 분 계신가요?

![image](https://cloud.githubusercontent.com/assets/421863/8320415/9433bad6-1a55-11e5-99c9-0ce0f4217d55.png)

![image](https://cloud.githubusercontent.com/assets/421863/8320403/62d6ac96-1a55-11e5-81a4-9d2f038bf86a.png)
