### ISSUE TITLE
AxGrid Header Label Change

### ISSUE THREAD

**Issue by FusionPark** [axisj/axisj#599]
안녕하세요... 현재 저희 회사에서 진행하는 프로젝트에 악수를 반영하기 위해서 프로토 타입을 만들어 보고 있습니다.. 먼저 이렇게 좋은 오픈소스를 있게 해주신것에 대해서 심심한 감사의 말씀을 드리며..

![20150605_112855](https://cloud.githubusercontent.com/assets/3162833/7998371/13b78b00-0b76-11e5-8644-9de10c17990f.png)
위에 조회 구분을 바꿀때마다 그리드의 첫번째 헤더가 일자/시간/요일/월간 이렇게 바뀌어야 합니다.

어떤 함수를 써야 할가요?

**Comment by groovedk** [comment]
아직 함수로 제공되는 내용은 없고 
해당 엘리먼트를 잡아서 텍스트를 변경하시면 될거같네요.

**Comment by tom-axisj** [comment]
조건이 바뀌면 변경되어야 할 그리드를 재 구성 해야 합니다.
setConfig를 다시 하거나 숨김레이어로 두개의 그리드를 만들고 show/hide 할 수 있겠습니다.
한두개로 끝날 상황이 아니면 setConfig 를 다시 하게 만들면 됩니다.
