### ISSUE TITLE
AXGrid row에서 button을 만들어서 사용할때

### ISSUE THREAD

**Issue by davidwin3** [axisj/axisj#600]
formatter : function(){
  return "\<button type=button onclick="fn.config('a','b')"\>설정\</button\>"
}
이런식으로 사용할때요

원래 body에서 사용하는것처럼 formatter에서 해당 row의 data를 가져와서 사용할 순 없을까요?
body : onclick : function(){
  fn.configObj(this.item);
}

**Comment by groovedk** [comment]
formatter 에서도 this.item이 사용가능합니다.

**Comment by davidwin3** [comment]
아 질문을 좀 잘못드릴거 같습니다 ㅠ
formatter에서 생성된 버튼에서 this.item을 함수의 파라미터로 넘길수 있는지가 질문입니다..
잘 안되는거 같은데요..

**Comment by hyunjun19** [comment]
아래처럼 인덱스만 넘기셔도 item을 가져올 수 있습니다.

```js
formatter : function(){
    return "<button type=button onclick="fnDoSomething(" + this.index + ")">설정</button>"
}
...

function fnDoSomething(index){
   console.log('fnDoSomething', myGrid.list[index]);
}
``

**Comment by davidwin3** [comment]
아 그렇게 하면 되겠군요^^;; 정말 감사합니다~
