### ISSUE TITLE
그리드 드래그 선택 문의드립니다

### ISSUE THREAD

**Issue by rioald** [axisj/axisj#602]
그리드의 셀들을 드래그해서 선택하는 기능은 없을까요?

dhtmlx grid 처럼 cell 을 엑셀처럼 드래그하여 copy 하는 기능이 필요한데
API 나 Demo 를 모두 뒤져보아도 없는거 같아서 문의 드립니다

**Comment by hyunjun19** [comment]
현재 그런 기능은 없습니다.
개별적으로 구현하셔야 할꺼 같습니다.
