### ISSUE TITLE
새창에서 그리드 스크롤 움직일시 에러 발생

### ISSUE THREAD

**Issue by david80** [axisj/axisj#603]
newopen 해서 스크롤을 움직일때 이런 스크립트 에러가 납니다.
이전버젼에서는 에러가 안났습니다. 최신으로 받고 테스트 해본결과...

![default](https://cloud.githubusercontent.com/assets/11273651/8056576/9312f2c4-0ee4-11e5-9285-d334824d22cf.png)
![_this](https://cloud.githubusercontent.com/assets/11273651/8056577/933d67ca-0ee4-11e5-98a3-8f04ea5f7ca5.png)

**Comment by tom-axisj** [comment]
버그 픽스 되었습니다. 감사합니다.
