### ISSUE TITLE
AXUpload5 페이지 내에 큐 박스 여러 개 적용 시 파일 로드 문제

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj/axisj#607]
AXUpload5 컴포넌트를 페이지 내에 여러 개 삽입 시 파일을 로드할때 문제가 발생하는 것 같습니다.
현재 다른 부분은 전부 정상 작동을 하고 있지만 파일 로드 부분에서 문제가 생겨 문의드립니다.
파일 로드시 아래와 같은 형식으로 로드하게 해 놓았습니다.
desc값은 제각각이며  저 값으로 업로드 컴포넌트를 구분하게 해 놓았지만 로드부분에서 아래와 같이 적용해 본 결과
$(document).ready(function(){
		<%=desc%>fnObj.pageStart();
		var <%=desc%>fileList = <%=returnValue%>;
		<%=desc%>FileUpload.setUploadedList(<%=desc%>fileList);

if($.isArray(<%=desc%>fileList)){
			for( var i = 0; i < <%=desc%>fileList.length; i++ ){
				var file = <%=desc%>fileList[i];
				$("form:eq(0)").append("<input type='text' name='delocIds' id='delocIds' value='"+file.delocId+"' />");
			}
		}
	});
하단의 배열인지 구분하고 text박스를 추가하는 부분에서는 정상적으로 값이 추가되는데
큐박스에서 추가하는 부분이 정상적으로 추가되지 않고 있습니다.
<%=desc%>FileUpload.getUploadedList("object");
를 받아 출력해 보면 값들이 정상적으로 들어가 있는 것이 확인되지만
큐박스에 추가가 되지 않아 아래와 같이 표시됩니다.
![default](https://cloud.githubusercontent.com/assets/8294689/8085948/dfd6c560-0fcd-11e5-9a55-086b205bb0aa.JPG)
문서 로드가 완료된 후 동시에 파일 추가 처리를 하면서 뭔가 문제가 발생한 것 같습니다.

**Comment by tom-axisj** [comment]
이런 경우엔 JSP 코드 보단 브라우저에 출력된 HTML 소스를 보여주시는 것이 
문제를 해결 하는데 도움이 되겠습니다.

**Comment by DaeHyeon-Kim** [comment]
HTML 소스입니다.

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>AXUpload5 - AXISJ</title>
    
    <link rel="stylesheet" type="text/css" href="/Windchill/jsp/axisj/ui/bulldog/page.css">
    <link rel="stylesheet" type="text/css" href="/Windchill/jsp/axisj/ui/bulldog/AXJ.min.css">
    <link rel="stylesheet" type="text/css" href="/Windchill/jsp/axisj/ui/bulldog/AXUpload5.css">
    <script type="text/javascript" src="/Windchill/jsp/axisj/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/Windchill/jsp/axisj/dist/AXJ.min.js"></script>
</head>


<body>
	<form name="createDocForm" id="createDocForm" method="post" action="/Windchill/jsp/DocAction.jsp">
		<input type="hidden" name="cmd" id="cmd" value="update" />
		<input type="hidden" name="oid" id="oid" value="VR:wt.doc.WTDocument:122128" />
		<input type="text" name="docName" id="docName" size="100" value="SADASD"/><p/>
		<textarea name="docContent" id="docContent" cols="100" rows="10">ASD</textarea>
	</form>
<input type="button" value="등록"  id="docCreateBtn" class="AXButton"  />

<div class="title"><h1>첨부파일</h1></div>
<div class="AXUpload5" id="UploadBtn" ></div>

<iframe id="downloadFrame" name="downloadFrame" ></iframe>
<script>
	
	/**
	 * Require Files for AXISJ UI Component...
	 * Based		: jQuery
	 * Javascript 	: AXJ.js, AXUpload5.js
	 * CSS			: AXJ.css, AXButton.css, AXUpload5.css
	 */
	$("#downloadFrame").hide();	
	var FileUpload = new AXUpload5();
	var fnObj = {
			pageStart: function(){
				fnObj.upload.init();
			},
			upload: {
				init: function(){
					FileUpload.setConfig({
						isSingleUpload:true, // 싱글 모드
						targetID:"UploadBtn",
						targetButtonClass:"Green",
						uploadFileName:"primary",
						crossDomain:true,
						//file_types:"image/*",  //audio/*|video/*|image/*|MIME_type (accept)
						
						//queueBoxAppendType:"(prepend || append)",
						// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
						flash_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload.swf",
						flash9_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload_fp9.swf",
						/* flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
						flash_file_types_description:"image",  */
						// --------- e
						onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
							//trace(this);
							//Download 링크
							var fileLink = "http://dsdev.dsec.co.kr/Windchill/jsp/FileDownload.jsp?fileName="+ this.saveName.dec()+"&originFileName="+this.name.dec();
							
							if(this.cacheId.dec() == ""){
								fileLink = location.protocol + "//" + location.host+"/Windchill/"+this.uploadedPath.dec();
							}
							
							var agent = navigator.userAgent.toLowerCase();		//브라우저 버전 정보
							//IE버전인지 아닌지 확인
							var isIE =  (navigator.appName == 'Netscape' && navigator.userAgent.search('Trident') != -1) || (agent.indexOf("msie") != -1);
							//IE일 경우 창으로 다운로드 아닐경우 프레임 다운로드
							if (isIE) {
								window.open(fileLink, "_blank", "width=500,height=500");
							}else{
								//window.open(fileLink, "_blank", "width=500,height=500");
								$("#downloadFrame").attr("src",fileLink);
							}
						},

						uploadMaxFileSize:(200000*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈이며 서버에서 설정되는 값이 아닙니다.)
						uploadMaxFileCount:10, // 업로드될 파일갯수 제한 0 은 무제한
						uploadUrl: "http://dsdev.dsec.co.kr/Windchill/jsp/FileUpload.jsp",
						uploadPars:{
							masterHost : location.protocol + "//" + location.host+"/Windchill/", 
							userId:'wcadmin', 
							userName:'administrator', 
							roleType : 'primary',
						},
						deleteUrl:  "/Windchill/jsp/FileDelete.jsp",
						deletePars:{UID:'tom', userName:'액시스'},

						buttonTxt:"파일올리기",

						fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
							name:"name",
							type:"type",
							saveName:"saveName",
							fileSize:"fileSize",
							uploadedPath:"uploadedPath",
							thumbPath:"thumbUrl",
							roleType : "roleType",
							delocId : "delocId",
							cacheId : "cacheId",
							desc : "desc"
						},

						onbeforeFileSelect: function(){
							trace(this);
							return true;
						},
						onUpload: function(file){
							//trace(this);
							//trace(secondaryUpload.uploadedList);
							//trace("onUpload");
							
							$("form:eq(0)").append("<input type='text' name='"+file.roleType+"' id='"+file.roleType+"' value='"+file.cacheId+"/"+file.name+"/' />");
						},
						onComplete: function(){

							//$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
							//var list = secondaryUpload.getUploadedList("json");
						},
						onStart: function(){
							//trace(this);
							//trace("onStart");
							//$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
						},
						onDelete: function(file){
							//trace(this);
							//trace("onDelete");
							$("input[name='"+file.roleType+"']:input[value='"+file.cacheId+"/"+file.name+"/']").remove();
							$("input[name='delocIds']:input[value='"+file.delocId+"']").remove();
						},
						onError: function(errorType, extData){
							
							if(errorType == "html5Support"){
								
								//dialog.push('The File APIs are not fully supported in this browser.');
							}else if(errorType == "fileSize"){
								//trace(extData);
								alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
							}else if(errorType == "fileCount"){
								alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
							}else if(errorType == "-200"){
								alert("서버오류가 발생하여 파일업로드를 실패했습니다.");
								secondaryUpload.cancelUpload();
							}
						}
					});
				}
			}
	};

	
	$(document).ready(function(){
		
		fnObj.pageStart();
		
			var fileList = {id : 'AXUpload_Single', name : 'icon.png', type : '', saveName : 'icon.png', fileSize : '1404', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122133&role=primary', thumbUrl : '', roleType : 'primary', delocId : 'wt.content.ApplicationData:122133', desc : '', cacheId : '' };
			FileUpload.setUploadedList(fileList);
			
			if($.isArray(fileList)){
				for( var i = 0; i < fileList.length; i++ ){
					var file = fileList[i];
					$("form:eq(0)").append("<input type='text' name='delocIds' id='delocIds' value='"+file.delocId+"' />");
				}
			}
		
		
	});
</script>



<div class="title"><h1>첨부파일</h1></div>
<div class="AXUpload5" id="desc1UploadBtn" ></div>

<div class="H10"></div>
<div id="desc1uploadQueueBox" class="AXUpload5QueueBox_list" style="height:150px;width:500px;"></div>
<div class="H10"></div>

<iframe id="desc1downloadFrame" name="desc1downloadFrame" ></iframe>
<script>
	
	/**
	 * Require Files for AXISJ UI Component...
	 * Based		: jQuery
	 * Javascript 	: AXJ.js, AXUpload5.js
	 * CSS			: AXJ.css, AXButton.css, AXUpload5.css
	 */
	$("#desc1downloadFrame").hide();	
	var desc1FileUpload = new AXUpload5();
	var desc1fnObj = {
			pageStart: function(){
				desc1fnObj.upload.init();
			},
			upload: {
				init: function(){
					desc1FileUpload.setConfig({
						isSingleUpload:false, // 싱글 모드
						targetID:"desc1UploadBtn",
						targetButtonClass:"Green",
						uploadFileName:"secondary",
						crossDomain:true,
						//file_types:"image/*",  //audio/*|video/*|image/*|MIME_type (accept)
						
						dropBoxID:"desc1uploadQueueBox",
						queueBoxID:"desc1uploadQueueBox", // upload queue targetID
						
						//queueBoxAppendType:"(prepend || append)",
						// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
						flash_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload.swf",
						flash9_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload_fp9.swf",
						/* flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
						flash_file_types_description:"image",  */
						// --------- e
						onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
							//trace(this);
							//Download 링크
							var fileLink = "http://dsdev.dsec.co.kr/Windchill/jsp/FileDownload.jsp?fileName="+ this.saveName.dec()+"&originFileName="+this.name.dec();
							
							if(this.cacheId.dec() == ""){
								fileLink = location.protocol + "//" + location.host+"/Windchill/"+this.uploadedPath.dec();
							}
							
							var agent = navigator.userAgent.toLowerCase();		//브라우저 버전 정보
							//IE버전인지 아닌지 확인
							var isIE =  (navigator.appName == 'Netscape' && navigator.userAgent.search('Trident') != -1) || (agent.indexOf("msie") != -1);
							//IE일 경우 창으로 다운로드 아닐경우 프레임 다운로드
							if (isIE) {
								window.open(fileLink, "_blank", "width=500,height=500");
							}else{
								//window.open(fileLink, "_blank", "width=500,height=500");
								$("#desc1downloadFrame").attr("src",fileLink);
							}
						},

						uploadMaxFileSize:(200000*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈이며 서버에서 설정되는 값이 아닙니다.)
						uploadMaxFileCount:10, // 업로드될 파일갯수 제한 0 은 무제한
						uploadUrl: "http://dsdev.dsec.co.kr/Windchill/jsp/FileUpload.jsp",
						uploadPars:{
							masterHost : location.protocol + "//" + location.host+"/Windchill/", 
							userId:'wcadmin', 
							userName:'administrator', 
							roleType : 'secondary',
						},
						deleteUrl:  "/Windchill/jsp/FileDelete.jsp",
						deletePars:{UID:'tom', userName:'액시스'},

						buttonTxt:"파일올리기",

						fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
							name:"name",
							type:"type",
							saveName:"saveName",
							fileSize:"fileSize",
							uploadedPath:"uploadedPath",
							thumbPath:"thumbUrl",
							roleType : "roleType",
							delocId : "delocId",
							cacheId : "cacheId",
							desc : "desc"
						},

						onbeforeFileSelect: function(){
							trace(this);
							return true;
						},
						onUpload: function(file){
							//trace(this);
							//trace(secondaryUpload.uploadedList);
							//trace("onUpload");
							
							$("form:eq(0)").append("<input type='text' name='"+file.roleType+"' id='"+file.roleType+"' value='"+file.cacheId+"/"+file.name+"/desc1' />");
						},
						onComplete: function(){

							//$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
							//var list = secondaryUpload.getUploadedList("json");
						},
						onStart: function(){
							//trace(this);
							//trace("onStart");
							//$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
						},
						onDelete: function(file){
							//trace(this);
							//trace("onDelete");
							$("input[name='"+file.roleType+"']:input[value='"+file.cacheId+"/"+file.name+"/desc1']").remove();
							$("input[name='delocIds']:input[value='"+file.delocId+"']").remove();
						},
						onError: function(errorType, extData){
							
							if(errorType == "html5Support"){
								
								//dialog.push('The File APIs are not fully supported in this browser.');
							}else if(errorType == "fileSize"){
								//trace(extData);
								alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
							}else if(errorType == "fileCount"){
								alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
							}else if(errorType == "-200"){
								alert("서버오류가 발생하여 파일업로드를 실패했습니다.");
								secondaryUpload.cancelUpload();
							}
						}
					});
				}
			}
	};

	
	$(document).ready(function(){
		
		desc1fnObj.pageStart();
		
			var desc1fileList = [{id : 'AXUpload_AX_0', name : 'sqlcli', type : '', saveName : 'sqlcli', fileSize : '835', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122137&role=secondary', thumbUrl : '', roleType : 'secondary', delocId : 'wt.content.ApplicationData:122137', desc : 'desc1', cacheId : '' },{id : 'AXUpload_AX_1', name : 'readme.html', type : '', saveName : 'readme.html', fileSize : '23580', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122135&role=secondary', thumbUrl : '', roleType : 'secondary', delocId : 'wt.content.ApplicationData:122135', desc : 'desc1', cacheId : '' }];
			desc1FileUpload.setUploadedList(desc1fileList);
			
			if($.isArray(desc1fileList)){
				for( var i = 0; i < desc1fileList.length; i++ ){
					var file = desc1fileList[i];
					$("form:eq(0)").append("<input type='text' name='delocIds' id='delocIds' value='"+file.delocId+"' />");
				}
			}
		
		
	});
</script>


<div class="title"><h1>첨부파일</h1></div>
<div class="AXUpload5" id="desc2UploadBtn" ></div>

<div class="H10"></div>
<div id="desc2uploadQueueBox" class="AXUpload5QueueBox_list" style="height:150px;width:500px;"></div>
<div class="H10"></div>

<iframe id="desc2downloadFrame" name="desc2downloadFrame" ></iframe>
<script>
	
	/**
	 * Require Files for AXISJ UI Component...
	 * Based		: jQuery
	 * Javascript 	: AXJ.js, AXUpload5.js
	 * CSS			: AXJ.css, AXButton.css, AXUpload5.css
	 */
	$("#desc2downloadFrame").hide();	
	var desc2FileUpload = new AXUpload5();
	var desc2fnObj = {
			pageStart: function(){
				desc2fnObj.upload.init();
			},
			upload: {
				init: function(){
					desc2FileUpload.setConfig({
						isSingleUpload:false, // 싱글 모드
						targetID:"desc2UploadBtn",
						targetButtonClass:"Green",
						uploadFileName:"secondary",
						crossDomain:true,
						//file_types:"image/*",  //audio/*|video/*|image/*|MIME_type (accept)
						
						dropBoxID:"desc2uploadQueueBox",
						queueBoxID:"desc2uploadQueueBox", // upload queue targetID
						
						//queueBoxAppendType:"(prepend || append)",
						// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
						flash_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload.swf",
						flash9_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload_fp9.swf",
						/* flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
						flash_file_types_description:"image",  */
						// --------- e
						onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
							//trace(this);
							//Download 링크
							var fileLink = "http://dsdev.dsec.co.kr/Windchill/jsp/FileDownload.jsp?fileName="+ this.saveName.dec()+"&originFileName="+this.name.dec();
							
							if(this.cacheId.dec() == ""){
								fileLink = location.protocol + "//" + location.host+"/Windchill/"+this.uploadedPath.dec();
							}
							
							var agent = navigator.userAgent.toLowerCase();		//브라우저 버전 정보
							//IE버전인지 아닌지 확인
							var isIE =  (navigator.appName == 'Netscape' && navigator.userAgent.search('Trident') != -1) || (agent.indexOf("msie") != -1);
							//IE일 경우 창으로 다운로드 아닐경우 프레임 다운로드
							if (isIE) {
								window.open(fileLink, "_blank", "width=500,height=500");
							}else{
								//window.open(fileLink, "_blank", "width=500,height=500");
								$("#desc2downloadFrame").attr("src",fileLink);
							}
						},

						uploadMaxFileSize:(200000*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈이며 서버에서 설정되는 값이 아닙니다.)
						uploadMaxFileCount:10, // 업로드될 파일갯수 제한 0 은 무제한
						uploadUrl: "http://dsdev.dsec.co.kr/Windchill/jsp/FileUpload.jsp",
						uploadPars:{
							masterHost : location.protocol + "//" + location.host+"/Windchill/", 
							userId:'wcadmin', 
							userName:'administrator', 
							roleType : 'secondary',
						},
						deleteUrl:  "/Windchill/jsp/FileDelete.jsp",
						deletePars:{UID:'tom', userName:'액시스'},

						buttonTxt:"파일올리기",

						fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
							name:"name",
							type:"type",
							saveName:"saveName",
							fileSize:"fileSize",
							uploadedPath:"uploadedPath",
							thumbPath:"thumbUrl",
							roleType : "roleType",
							delocId : "delocId",
							cacheId : "cacheId",
							desc : "desc"
						},

						onbeforeFileSelect: function(){
							trace(this);
							return true;
						},
						onUpload: function(file){
							//trace(this);
							//trace(secondaryUpload.uploadedList);
							//trace("onUpload");
							
							$("form:eq(0)").append("<input type='text' name='"+file.roleType+"' id='"+file.roleType+"' value='"+file.cacheId+"/"+file.name+"/desc2' />");
						},
						onComplete: function(){

							//$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
							//var list = secondaryUpload.getUploadedList("json");
						},
						onStart: function(){
							//trace(this);
							//trace("onStart");
							//$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
						},
						onDelete: function(file){
							//trace(this);
							//trace("onDelete");
							$("input[name='"+file.roleType+"']:input[value='"+file.cacheId+"/"+file.name+"/desc2']").remove();
							$("input[name='delocIds']:input[value='"+file.delocId+"']").remove();
						},
						onError: function(errorType, extData){
							
							if(errorType == "html5Support"){
								
								//dialog.push('The File APIs are not fully supported in this browser.');
							}else if(errorType == "fileSize"){
								//trace(extData);
								alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
							}else if(errorType == "fileCount"){
								alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
							}else if(errorType == "-200"){
								alert("서버오류가 발생하여 파일업로드를 실패했습니다.");
								secondaryUpload.cancelUpload();
							}
						}
					});
				}
			}
	};

	
	$(document).ready(function(){
		
		desc2fnObj.pageStart();
		
			var desc2fileList = [{id : 'AXUpload_AX_0', name : 'sqldeveloper.sh', type : '', saveName : 'sqldeveloper.sh', fileSize : '71', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122139&role=secondary', thumbUrl : '', roleType : 'secondary', delocId : 'wt.content.ApplicationData:122139', desc : 'desc2', cacheId : '' }];
			desc2FileUpload.setUploadedList(desc2fileList);
			
			if($.isArray(desc2fileList)){
				for( var i = 0; i < desc2fileList.length; i++ ){
					var file = desc2fileList[i];
					$("form:eq(0)").append("<input type='text' name='delocIds' id='delocIds' value='"+file.delocId+"' />");
				}
			}
		
		
	});
</script>




<div class="title"><h1>첨부파일</h1></div>
<div class="AXUpload5" id="desc3UploadBtn" ></div>

<div class="H10"></div>
<div id="desc3uploadQueueBox" class="AXUpload5QueueBox_list" style="height:150px;width:500px;"></div>
<div class="H10"></div>

<iframe id="desc3downloadFrame" name="desc3downloadFrame" ></iframe>
<script>
	
	/**
	 * Require Files for AXISJ UI Component...
	 * Based		: jQuery
	 * Javascript 	: AXJ.js, AXUpload5.js
	 * CSS			: AXJ.css, AXButton.css, AXUpload5.css
	 */
	$("#desc3downloadFrame").hide();	
	var desc3FileUpload = new AXUpload5();
	var desc3fnObj = {
			pageStart: function(){
				desc3fnObj.upload.init();
			},
			upload: {
				init: function(){
					desc3FileUpload.setConfig({
						isSingleUpload:false, // 싱글 모드
						targetID:"desc3UploadBtn",
						targetButtonClass:"Green",
						uploadFileName:"secondary",
						crossDomain:true,
						//file_types:"image/*",  //audio/*|video/*|image/*|MIME_type (accept)
						
						dropBoxID:"desc3uploadQueueBox",
						queueBoxID:"desc3uploadQueueBox", // upload queue targetID
						
						//queueBoxAppendType:"(prepend || append)",
						// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
						flash_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload.swf",
						flash9_url : "http://dsdev.dsec.co.kr/Windchill/jsp/axisj/lib/swfupload_fp9.swf",
						/* flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
						flash_file_types_description:"image",  */
						// --------- e
						onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
							//trace(this);
							//Download 링크
							var fileLink = "http://dsdev.dsec.co.kr/Windchill/jsp/FileDownload.jsp?fileName="+ this.saveName.dec()+"&originFileName="+this.name.dec();
							
							if(this.cacheId.dec() == ""){
								fileLink = location.protocol + "//" + location.host+"/Windchill/"+this.uploadedPath.dec();
							}
							
							var agent = navigator.userAgent.toLowerCase();		//브라우저 버전 정보
							//IE버전인지 아닌지 확인
							var isIE =  (navigator.appName == 'Netscape' && navigator.userAgent.search('Trident') != -1) || (agent.indexOf("msie") != -1);
							//IE일 경우 창으로 다운로드 아닐경우 프레임 다운로드
							if (isIE) {
								window.open(fileLink, "_blank", "width=500,height=500");
							}else{
								//window.open(fileLink, "_blank", "width=500,height=500");
								$("#desc3downloadFrame").attr("src",fileLink);
							}
						},

						uploadMaxFileSize:(200000*1024*1024), // 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈이며 서버에서 설정되는 값이 아닙니다.)
						uploadMaxFileCount:10, // 업로드될 파일갯수 제한 0 은 무제한
						uploadUrl: "http://dsdev.dsec.co.kr/Windchill/jsp/FileUpload.jsp",
						uploadPars:{
							masterHost : location.protocol + "//" + location.host+"/Windchill/", 
							userId:'wcadmin', 
							userName:'administrator', 
							roleType : 'secondary',
						},
						deleteUrl:  "/Windchill/jsp/FileDelete.jsp",
						deletePars:{UID:'tom', userName:'액시스'},

						buttonTxt:"파일올리기",

						fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
							name:"name",
							type:"type",
							saveName:"saveName",
							fileSize:"fileSize",
							uploadedPath:"uploadedPath",
							thumbPath:"thumbUrl",
							roleType : "roleType",
							delocId : "delocId",
							cacheId : "cacheId",
							desc : "desc"
						},

						onbeforeFileSelect: function(){
							trace(this);
							return true;
						},
						onUpload: function(file){
							//trace(this);
							//trace(secondaryUpload.uploadedList);
							//trace("onUpload");
							
							$("form:eq(0)").append("<input type='text' name='"+file.roleType+"' id='"+file.roleType+"' value='"+file.cacheId+"/"+file.name+"/desc3' />");
						},
						onComplete: function(){

							//$("#uploadCancelBtn").get(0).disabled = true; // 전송중지 버튼 제어
							//var list = secondaryUpload.getUploadedList("json");
						},
						onStart: function(){
							//trace(this);
							//trace("onStart");
							//$("#uploadCancelBtn").get(0).disabled = false; // 전송중지 버튼 제어
						},
						onDelete: function(file){
							//trace(this);
							//trace("onDelete");
							$("input[name='"+file.roleType+"']:input[value='"+file.cacheId+"/"+file.name+"/desc3']").remove();
							$("input[name='delocIds']:input[value='"+file.delocId+"']").remove();
						},
						onError: function(errorType, extData){
							
							if(errorType == "html5Support"){
								
								//dialog.push('The File APIs are not fully supported in this browser.');
							}else if(errorType == "fileSize"){
								//trace(extData);
								alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
							}else if(errorType == "fileCount"){
								alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
							}else if(errorType == "-200"){
								alert("서버오류가 발생하여 파일업로드를 실패했습니다.");
								secondaryUpload.cancelUpload();
							}
						}
					});
				}
			}
	};

	
	$(document).ready(function(){
		
		desc3fnObj.pageStart();
		
			var desc3fileList = [{id : 'AXUpload_AX_0', name : 'view-source-paths.lis', type : '', saveName : 'view-source-paths.lis', fileSize : '6426', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122141&role=secondary', thumbUrl : '', roleType : 'secondary', delocId : 'wt.content.ApplicationData:122141', desc : 'desc3', cacheId : '' }];
			desc3FileUpload.setUploadedList(desc3fileList);
			
			if($.isArray(desc3fileList)){
				for( var i = 0; i < desc3fileList.length; i++ ){
					var file = desc3fileList[i];
					$("form:eq(0)").append("<input type='text' name='delocIds' id='delocIds' value='"+file.delocId+"' />");
				}
			}
		
		
	});
</script>


<script>	
	$(document).ready(function(){
		$("#docCreateBtn").click(function(){
			$("#createDocForm").submit();
		});
	});
</script>
</body>
</html>

**Comment by tom-axisj** [comment]
```
var desc3fileList = [{id : 'AXUpload_AX_0', name : 'view-source-paths.lis', type : '', saveName : 'view-source-paths.lis', fileSize : '6426', uploadedPath : 'servlet/AttachmentsDownloadDirectionServlet?oid=VR:wt.doc.WTDocument:122128&cioids=wt.content.ApplicationData:122141&role=secondary', thumbUrl : '', roleType : 'secondary', delocId : 'wt.content.ApplicationData:122141', desc : 'desc3', cacheId : '' }];
            desc3FileUpload.setUploadedList(desc3fileList);
```
이 부분을 보시면 id 가 `AXUpload_AX_0` 인데요. 내부에서 이 id로 엘리먼트를 만들다 보니 충돌이 나는 것으로 생각됩니다. id를 다르게 해서 해보세요.

**Comment by DaeHyeon-Kim** [comment]
되는군요. 빠른 답변 감사합니다.
