### ISSUE TITLE
!! 액시스제이 티셔츠 판매합니다.

### ISSUE THREAD

**Issue by thomasJang** [axisj/axisj#611]
http://blog.axisj.com/archives/483
AXISJ 티셔츠 판매합니다.
한정수량입니다. 
AXISJ 개발자들은 놓칠 수 없는 잇 아이템.!!
위 링크를 따라가시면 자세한 정보를 얻을 수 있습니다.
(주의 : 사이즈별 수량이 제한되어 있어 조기 품절 될 수 있습니다.)

![img_0546](https://cloud.githubusercontent.com/assets/5884902/8203375/525900be-151c-11e5-8f78-c96e535fd96c.jpg)

**Comment by panic910** [comment]
범상치 않은 거대한  체구로 인해 포기 합니다. ㅠㅠ

**Comment by tom-axisj** [comment]
ㅠ.ㅠ :cry:

**Comment by hyunjun19** [comment]
:+1:
