### ISSUE TITLE
셀렉터 입력시 포함된 글자 찾는 기능문의

### ISSUE THREAD

**Issue by david80** [axisj/axisj#612]
셀렉터 입력시 포함된 글자 찾는 기능문의

(창원 이라는 값이 있는 옵션값에서
입력박스에 원이라고 입력했을때 포함된 옵션들로 갔으면 합니다..

필터기능이 필요합니다..

![1](https://cloud.githubusercontent.com/assets/11273651/8225041/ae822358-15ca-11e5-93dd-41a51e39250e.png)

**Comment by tom-axisj** [comment]
selector는 첫글자부터 검색하는 방식이기 때문에 포커스 처리가 안되고 있습니다.
