### ISSUE TITLE
셀릭트 박스 포커스가 갔는지 안갔는지 판별을 할수가 없는데..

### ISSUE THREAD

**Issue by david80** [axisj/axisj#613]
![2](https://cloud.githubusercontent.com/assets/11273651/8226535/ad4a6684-15da-11e5-8bdb-cb68ebc7d533.png)

셀렉트 박스에 포커스가 갔을경우 뭔가 표시되어질 만한것이 있나요?

포커스가 갔는지 안갔는지 모르겠습니다..

**Comment by hyunjun19** [comment]
포커스가 가는 경우 뭔가 표시를 해야겠네요.
