### ISSUE TITLE
AXGrid 내 에디터- 유효성 검사 관련 문의

### ISSUE THREAD

**Issue by AnSoHyun** [axisj/axisj#614]
안녕하세요. 날씨가 더운데 고생이 많으십니다.
 

다름이 아니가 AXGrid 내 유효성 검사 시 툴팁을 넣고 싶습니다.

API를 찾아봤으나 구현법을 찾을 수 없네요. 못 찾는건지.

 

방법이 있으면 알려주셨으면 합니다.

 

현재 구현상태입니다.

----------------

{colSeq:0, key:"test_key", label:"test_label", width:"100", align:"right", formatter:"dec", 
    form: { type: "text"
    , value: function() { return this.value.dec(); }
    , validate: function() {
         if (this.value == "") {
             alert("입력값이 없습니다.");// 아닌 툴팁으로..
             return false;
         }
    }}
    , AXBind: { type: "text", config : {}} 
},

----------------

 

항상 감사의 말씀을 드립니다.

**Comment by tom-axisj** [comment]
툴팁은 구현이 어려울 것 같구요.
toast를 써보시는 걸 권장 드리고 싶네요
