### ISSUE TITLE
AXEditor.getContent()에 대하여 질문드립니다.

### ISSUE THREAD

**Issue by bewoo** [axisj/axisj#615]
안녕하세요, 작년부터 axisj를 정말 잘 사용하고 있는 개발자입니다. 

AXEditor이용중 궁금한점이 있어 질문드립니다.

API문서(http://jdoc.axisj.com/AXEditor.html#getContent)의 8번째줄 보면 
"POST 전송할때 짤림현상 방지를 위해서는 content를 잘라서 보내야 합니다"
라고 되어 있는데 그 이유가 무엇인지 궁금합니다.

아 그리고 substr(0, 102399)의 102399란 숫자의 의미도 궁금하네요 

해보니 진짜로 잘리네요...;

더운날씨에 고생많으십니다.

**Comment by tom-axisj** [comment]
http 스펙에 하나의 키에 값이 102499 이상 전달할 수 없기 때문입니다.
