### ISSUE TITLE
페이징처리에서 pageSize를 dynamic하게 할수없나요?

### ISSUE THREAD

**Issue by showaging** [axisj/axisj#616]
page:{
                    paging:true,
                    pageNo:1,
                    pageSize:100,
                    status:{formatter: null}
                }

샘플에는 pageSize가 100으로 고정되어있는데  select박스로 값을 받아와서 처리할 방법은 없나요?ㅠ

**Comment by tom-axisj** [comment]
현재 개발되어 있지 않습니다. 별도 입력을 해서 처리 해야 합니다.

**Comment by blueleeky** [comment]
제가 처리 하는 방식입니다. 참조 하세요
AxSearch 부분에.. select(key:pageUnit) 박스를 이용하여 페이지 크기를 선택 하게 한 후
grid.search(){
  // 페이지 사이즈 값을 지정한후
  grid.page.pageSize = $("#"+mySearch.getItemId("pageUnit")).val();
  grid.setList({.....});
}
서버 호출전에 pageSize값을 설정 한후에.. 검색을 하면 됩니다.
