### ISSUE TITLE
date/datetime translations.

### ISSUE THREAD

**Issue by Cantuares** [axisj/axisj#620]
I have some doubt, first, sorry for my bad english,
i don't know if here is the best place for ask, well, this library is awesome, but i can't translate the date names and i can't change the format the dates like this 22/06/2015, i can only change the separator, i read the API and I couldn't find nothing related, someone can help me with this question?thank you.

**Comment by InSeoHwang** [comment]
oh. i like to here from you.

i will make it your request. as soon as possible

i will let you know. when i am done with it.

**Comment by InSeoHwang** [comment]
@tom-axisj  please check this issue.

**Comment by Cantuares** [comment]
@InSeoHwang Thank you so much for your answer, if possible make the json or one javascript file for translate the form validation too, i can collaborate with the translation in my language, thank you.

**Comment by tom-axisj** [comment]
(new Date()).print("dd/mm/yyyy");

**Comment by tom-axisj** [comment]
http://jdoc.axisj.com/Date.html#print

**Comment by Cantuares** [comment]
Thank you very much for your answer @tom-axisj, for the form validation translation ? exist something like this too?

**Comment by tom-axisj** [comment]
Do you want to check input value of date type?

**Comment by tom-axisj** [comment]
Show me your code

**Comment by Cantuares** [comment]
@tom-axisj @tom-axisj example, when i validate my field called "nome", is returned the message:
"[nome](은)는 필수입력 사항입니다."
But, i want to translate for:
"[nome] é um campo de preenchimento obrigatório."
i can change this inside the code, but i will need change always when one new release is launched, but if exists one external file that i can manage, would help so much.
Thank you for your answer.

**Comment by tom-axisj** [comment]
Ok next day i will answer for you. See you

**Comment by Cantuares** [comment]
Thank you very much @tom-axisj and nSeoHwang, you doing a excelent work.

**Comment by tom-axisj** [comment]
@Cantuares 

first you need change new version AXISJ. here https://github.com/axisj/axisj/tree/dev

and

```html
<form name="myForm" method="post">
	<input type="text" name="userID" id="userID" placeholder="ID" value="" class="AXInput W200 av-required" />
	<!-- placeholder or title is a label of validator -->
</form>

<script>
	AXConfig.AXValidator.validateErrMessage.required = "[{label}] is required";
	// extend object 'AXConfig.AXValidator' to new source 
	var myValidator = new AXValidator(); // Validator 선언
	myValidator.setConfig({
		targetFormName : "myForm"
	});

	// validate form
	var validateResult = myValidator.validate();
	if (!validateResult) {
		var msg = myValidator.getErrorMessage();
		AXUtil.alert(msg);
		myValidator.getErrorElement().focus();
		return false;
	}else{
		alert(	validateResult );
	}
</script>
```

you can reset Object `AXConfig.AXValidator`
like this 
Caution reset Object before `var myValidator = new AXValidator(); `
```
AXValidator.validateErrMessage = {
	required: "[{label}](은)는 필수입력 사항입니다.",
	requiredstring: "반드시 {required}(으)로 입력하셔야 하는 사항입니다.",
	match: "[{label}](은)는 입력된 내용이 일치하지 않습니다.",
	invalid: "[{label}](은)는 입력된 내용이 올바르지 않습니다.",
	min: "[{label}](은)는 {min} 이상의 값을 입력해주세요.",
	max: "[{label}](은)는 {max} 이하의 값을 입력해주세요.",
	minbyte: "[{label}]의 입력된 내용의 길이가 {minbyte}Byte 이상이어야 합니다.",
	maxbyte: "[{label}]의 입력된 내용의 길이가 {maxbyte}Byte를 초과할 수 없습니다.",
	minlength: "[{label}]의 입력된 내용의 length가 {minlength} 이상이어야 합니다.",
	maxlength: "[{label}]의 입력된 내용의 length가 {maxlength}을 초과할 수 없습니다.",

	number: "숫자로만 입력하셔야 합니다.",
	email: "이메일 형식이 올바르지 않습니다.",
	hangul: "한글로만 입력하셔야 합니다.",
	engonly: "영문으로만 입력하셔야 합니다.",
	residentno: "주민등록번호 형식이 올바르지 않습니다.",
	foreignerno: "외국인등록번호 형식이 올바르지 않습니다.",
	bizno: "사업자등록번호 형식이 올바르지 않습니다.",
	phone: "전화번호 형식이 올바르지 않습니다.",
	isdate: "날짜 형식이 올바르지 않습니다.",
	zip: "우편번호 형식이 올바르지 않습니다.",
	money: "화폐형식으로만 입력하셔야 합니다.",
	earlierThan: "[{label}] 보다 빠른 날짜를 입력해야 합니다.",
	laterThan: "[{label}] 보다 느린 날짜를 입력해야 합니다.",

	exception: "not found errmessage"
};
```
