### ISSUE TITLE
AXUpload5에서 대표이미지 저장 문의

### ISSUE THREAD

**Issue by wann2** [axisj/axisj#622]
안녕하세요.

AXUpload5에서 대표이미지를 설정한 뒤 나중에 서버에 올려진 파일을 불러올 때 대표이미지로 설정했던 이미지를 대표이미지로 선택되었다는 것을 표시해주려면 어떻게 해야 하나요?
즉, 서버에 이미지들을 저장시킬 때 해당 이미지가 대표이미지라는 것을 알기 위해 어떤 값을 지정을 해줘야 하나요? 
setMainImage로 대표이지미를 설정하지만, 이를 서버에 올린 뒤 나중에 올려진 파일들을 불러올 때 설정했던 특정이미지가 대표이미지라는 것을 표시해주려고 합니다.

**Comment by tom-axisj** [comment]
```json
[{"id":"AXA230624582_AX_0", "name":"cal.png", "type":"png", "saveName":"AX_6813852492.png", "fileSize":"3619", "uploadedPath":"/samples/AXUpload5/files/", "thumbUrl":"files%2FAX_6813852492.png", "mainImage":true}, {"id":"AXA230624588_AX_1", "name":"ontrack-logo.png", "type":"png", "saveName":"AX_4765024790.png", "fileSize":"33753", "uploadedPath":"/samples/AXUpload5/files/", "thumbUrl":"files%2FAX_4765024790.png", "mainImage":""}, {"id":"AXA230624591_AX_2", "name":"ontrack.png", "type":"png", "saveName":"AX_3440198224.png", "fileSize":"12559", "uploadedPath":"/samples/AXUpload5/files/", "thumbUrl":"files%2FAX_3440198224.png", "mainImage":""}]
```

이건 업로드된 후 getObject롤 데이터를 가져온 것인데요. `"mainImage":true` 가 보입니다. 잘 보면
setUploadedList 할때에도 마찬가지로 `"mainImage":true` 이면 됩니다.

**Comment by wann2** [comment]
대표이미지버튼을 클릭해서 대표이미지를 체크해주고 서버에도 해당이미지의 mainImage field에 true를 저장했습니다. 그리고 아래처럼 다시 불러올때도 대표이미지에 "mainImage": true 값을 넣어 서버에서 받았습니다.

pageList: function() {
	var url = '/Agen/house/imgList';
	new AXReq(url, {
		pars: 'houseId='+$('#houseId').val(), 
		onsucc: function(res) {
			if (!res.error) {
console.log(res);
				myUpload.setUploadedList(res);
			} else {
				dialog.push(res.msg.dec());
			}
		}
	});
}
아래 콘솔창 메시지처럼 "mainImage": true 을 서버에서 보내주는데도 
AXUpload5QueueBox에 뿌려지는 이미지에는 대표이미지라는 것을 체크해주는 것이 보이지 않습니다.

[Object, Object]
0: Object
	fileSize: "204553"
	id: "IMG5"
	imgId: "5589fea056c7b20d14333480"
	mainImage: true
	name: "2.jpg"
	saveName: "upload_1b368df7b81fdb12cc5922b3c37202a0.jpg"
	thumbUrl: "imgView_1b368df7b81fdb12cc5922b3c37202a0.jpg"
	type: "jpg"
	uploadedPath: "/upload/"
	__proto__: Object
1: Object
	fileSize: "281025"
	id: "IMG3"
	imgId: "5589fa8b0d2b750012806483"
	mainImage: ""
	name: "9.jpg"
	saveName: "upload_af0dc2aff05d816d3a4d228bf4826d0e.jpg"
	thumbUrl: "imgView_af0dc2aff05d816d3a4d228bf4826d0e.jpg"
	type: "jpg"
	uploadedPath: "/upload/"
	__proto__: Object
	
대표이미지라는 것을 표시해주기 위해 또다른 설정이 필요한가요?

**Comment by tom-axisj** [comment]
https://github.com/axisj/axisj/blob/master/samples/AXUpload5/selectMainImage.html#L78 여기를 확인 하셔야 할 것 같습니다.

**Comment by wann2** [comment]
formatter: function(f){
	var po = [];
	po.push("<div id='"+this.id+"_AXUploadLabel_mainImageFile' class='AXUploadMainImage' >mainImage</div>");
	return po.join('');						
},

위 로직을 소스에 기재해도 서버에서 불러온 이미지들 중에 메인이미지라는 것을 체크하지 못하고 있습니다.
좀더 자세하게 설명해주시면 감사하겠습니다.

**Comment by wann2** [comment]
myUpload.setUploadedList(res);
$.each(res, function(idx, x) {
	if (x.mainImage === true) $('#'+x.id+'_AXUploadLabel_mainImageFile').show();
});
이렇게 하니 대표이미지가 선택이 되더군요. 
^^
