### ISSUE TITLE
axisj 사용법 및 초기 Error 관련 문의

### ISSUE THREAD

**Issue by dsjeong** [axisj/axisj#624]
안녕하세요.

axisj 라이브러리 사용에 관련하여 문의 드립니다.

저는 http://www.egovframe.go.kr/에서 제공하는
Eclipse Tool(eGovFrame 3.1)에서 웹 개발을 하고 있습니다.
기 개발된 Web Project에서 axisj 라이브러리를 추가 시 아래와 같이 초기 Error가 발생하여 해결 방법을 문의하고자 합니다. 

ㅁ axisj 사용법 및 초기 Error
    - https://github.com/에서 axisj-1.0.16을 다운 받아 \src\main\webapp 하위로 위치시킴
    - 초기 Syntax error가 다수 발생
       1) axisj-1.0.16\dist
           Syntax error on token "else", { expected
       2) axisj-1.0.16\lib
           Multiple markers at this line
           	- The global variable i is not explicitly declared.
           	- Type mismatch: cannot convert from any[] to any
           	- Missing semicolon
           	- Missing semicolon
           .......
ㅁ 문의내용
      단순 폴더 복사 후 초기 Syntax Error가 발생하였는데, 손수 수정하기에는 너무 많은데,
     해결할 수 있는 방법이 무엇인지 문의드립니다.
     혹, 확인이 필요한 것들(version, source code 호환성 등...)이 있는지요?

이상입니다.

감사합니다.

**Comment by hyunjun19** [comment]
사용하는데 문제는 없습니다.
다만 보기에는 좀 거슬릴수도 있으니 js validation을 끄시면 에러 메시지가 없어질껍니다.

**Comment by dsjeong** [comment]
조치가 되었습니다.
답변 감사합니다^^

**Comment by hyunjun19** [comment]
해결되었다니 다행입니다.

우측 상단의 `Star`를 클릭해 주시면 개발자들에게 큰 힘이 됩니다.
