### ISSUE TITLE
웹에디터 버그 작동안됩니다.

### ISSUE THREAD

**Issue by david80** [axisj/axisj#625]
```
SCRIPT5007: 정의되지 않음 또는 null 참조인 'type' 속성을 가져올 수 없습니다.
파일: AXJ.min.js, 줄: 5, 열: 20698
```
![2](https://cloud.githubusercontent.com/assets/11273651/8344384/f5e74e5c-1b1b-11e5-8306-06f5f09ca269.png)

익스플로러11에서 이모티콘을 비롯하여 작동안되는 기능들이 많습니다.

![default](https://cloud.githubusercontent.com/assets/11273651/8344376/d275a324-1b1b-11e5-8915-6b25d0bb863f.png)

**Comment by tom-axisj** [comment]
수정된 버전으로 확인해보시기 바람니다.

**Comment by david80** [comment]
잘작동되네요
