### ISSUE TITLE
dialog.push 및 AXSearch 관련 문의드립니다.

### ISSUE THREAD

**Issue by showaging** [axisj/axisj#627]
매일 번거롭게 문의드려서 죄송합니다.

첫번째는 dialog.push() alert창의 가로 사이즈를 조절가능한지 문의드립니다.
![2015-06-25 18 20 22](https://cloud.githubusercontent.com/assets/12963877/8351276/08cdac28-1b67-11e5-8b4a-01dc8c30ea37.PNG)

두번째는 AXSearch()에서 input박스에 값을 입력 후 엔터키를 누르면 검색결과가 그리드에 뿌려지는데
날짜input박스가 검색조건으로 있는 상태에서 input박스에 값을 입력하고 엔터키를 누르면 이벤트가 작동을 안합니다. 저만 그런건지 문의드립니다.
![2015-06-25 18 21 10](https://cloud.githubusercontent.com/assets/12963877/8351300/45a41f60-1b67-11e5-899e-804ecddd98bb.PNG)

**Comment by tom-axisj** [comment]
첫번째는 CSS를 재정의 하는 방식으로 해결 하셔야 할 것 같구요.
두번째는 search안에 button이 submit 타입으로 있을 때만 엔터키입력시 서브밋이 작동되게 됩니다.
이는 form에서도 마찬가지 입니다.

**Comment by tom-axisj** [comment]
```css
.AXNotificationTrayDialog .AXNotification{
    width: 400px;
}
```

처럼 하시면 너비 조정가능합니다.
