### ISSUE TITLE
AXTree 버그

### ISSUE THREAD

**Issue by webdes83** [axisj/axisj#629]
http://dev.axisj.com/samples/AXTree/control.html

추가 2번 이상 생성후 
추가요소 삭제후 순서 변경시
삭제된 아이템이 순서 잡아먹음

**Comment by tom-axisj** [comment]
버그 수정되었습니다. dev브랜치에 커밋되었으니 소스 변경을 원하시면 dev 브랜치를 받으셔야 합니다.
감사합니다.
