### ISSUE TITLE
AXGrid 아이템 개수관련 문의

### ISSUE THREAD

**Issue by AnSoHyun** [axisj/axisj#630]
안녕하세요.
아래 유효성 검사에 대한 답변은 잘 보았습니다.
감사드리며, 해당 부분은 toast 처리를 했는데 그리드 내 벨리데이션의 경우
각각 걸리기 때문에 예를 들어

이름/생년월일/점수가 필수값이라면,
toast가 이름을 입력해 주세요/생년월일을 입력해 주세요/점수를 입력해 주세요.
각각 발생하기 때문에 불편하더군요. 우선순위를 지정해 줄 수 있으면 좋겠습니다.
(이렇게 안되면 respanse에서 한꺼번에 잡아줘야되서요.)

그리고 이번 질문 사항은 아래와 같습니다.

작업을 하다보면 그리드 내 아이템 
전체 4개의 목록이 있습니다.
4 Items

--> 이렇게 두 종류를 보게 되는데 가끔 아이템 개수가 제대로 나오지 않는
현상이 발생합니다. 차이점을 말씀해 주시면 감사하겠습니다.

항상 감사의 말씀드립니다. 고맙습니다.

**Comment by hyunjun19** [comment]
두 종류를 캡쳐해서 올려주세요. 어느 부분을 말하시는 건지 잘 모르겠습니다. ^^;;

**Comment by hyunjun19** [comment]
#650 으로 이동됨
