### ISSUE TITLE
setFocus로 포커스 이동시 스크롤은 고정인 상황

### ISSUE THREAD

**Issue by guddhrdl** [axisj/axisj#631]
```js
myGrid.setList({
	ajaxUrl  : contextPath + path + "/getServiceList.json",
	ajaxPars : "net_Dscd=" + net_Dscd,
	onLoad   : function() {
		dataList = this.list;
				
		myGrid.setFocus(dataList.length - 1);
	}
});

selectList : function(){
		myGrid.setList({
			ajaxUrl  : contextPath + path + "/getServiceList.json",
			ajaxPars : "net_Dscd=" + net_Dscd,
			onLoad   : function() {
				dataList = this.list;
				
				myGrid.setFocus(dataList.length - 1);
			}
		});
	}
```
위와 같이 onLoad시에 setFocus가 실행되도록 작성했습니다.
하단에 포커스는 잘 되는데 스크롤은 상단에 고정되어 있습니다..

데이터 수정시에는 selectlList를 사용하게 되어 있는데,
그때는 포커스와 스크롤은 원하는 위치에 잘 있습니다.

기타 등등 다른곳에서 setFocus를 사용하면 이상없이 잘 됩니다...무슨 문제일까요?

**Comment by hyunjun19** [comment]
버그인거 같습니다.
조만간 패치하겠습니다.

**Comment by hyunjun19** [comment]
패치되었습니다.
정식 릴리즈에 반영되려면 시간이 좀 걸립니다.
급하시면 88d824fbd3259af217efd2e01003d5660f7cb1d8 여기를 확인해 주세요.

**Comment by guddhrdl** [comment]
@hyunjun19 빠른 수정 감사합니다^^

**Comment by hyunjun19** [comment]
버그 리포트 감사합니다.
오른쪽 상단에 `Star`를 눌러 주시면 개발자에게 큰 힘이 됩니다. =)
