### ISSUE TITLE
div 팝업에서 셀렉트박스를 마우스 클릭했을경우 선택이 안되어짐.

### ISSUE THREAD

**Issue by david80** [axisj/axisj#632]
div 팝업에서 셀렉트박스를 마우스 클릭했을경우 선택이 안되어짐.

이번 셀렉트박스 업데이트 된 후로 나오는 현상인듯..

**Comment by hyunjun19** [comment]
현재 dev 브랜치에 있는 AXSelect.js v1.9.8 소스로 `AXModal.openDiv`와 `jQueryExtends.bindSelect`로 테스트를 해보았는데 재현이 안됩니다.

지금 사용하시는 버전이 몇 버전이신가요?
좀 더 자세한 정보를 주세요.

※ 매번 버그리포트와 피드백 감사합니다. =)

**Comment by david80** [comment]
![localhost_20150629_140526](https://cloud.githubusercontent.com/assets/11273651/8401324/efb395a0-1e67-11e5-8e2e-da235b999e54.jpg)
마우스로 위처럼 과세를 클릭하면 과세선택이 안됩니다. 키보드로 선택하고 엔터치면 선택이 되어지구요. 
AXSelect.js v1.9.8 이구요 근데 전 axj.min.js만 사용했습니다.

**Comment by hyunjun19** [comment]
b70e8d642abc9a7f8518d7fd2d41d977f48dbed8

수정완료했습니다. 제가 테스트가 부족했네요. =)

**Comment by tom-axisj** [comment]
:+1:

**Comment by david80** [comment]
잘됩니다. Close!!
