### ISSUE TITLE
bindSelector 관련 건의 드립니다.

### ISSUE THREAD

**Issue by iuui6980** [axisj/axisj#634]
안녕하세요.

bindSelector를 쓰다가 자동완성 기능이 있는걸 발견했는데요.

글자 순서대로 검사 후 결과 찾기를 하는 방법 같은데

혹시 예를 들어 '강아지와 고양이'를 검색하기 위해 '고양이' 작성하면 가져오는 방법이 없을까요?

없다면 혹시 개선해 주실수 있으신지...

**Comment by hyunjun19** [comment]
http://jdoc.axisj.com/jQueryExtends.html#bindSelector `onsearch` 함수를 구현하시면 될꺼 같습니다.
