### ISSUE TITLE
AXbind 관련 문의(radio, check)

### ISSUE THREAD

**Issue by kingwhale** [axisj/axisj#635]
안녕하세요?

1번의 Select Box 처럼 데이터를 가져와 2번에 Radio Box와 Check Box에 바인딩 시키고 싶은데,
API와 샘플코드, js 파일을 찾아봐도 정확한 정보를 얻지를 못했네요..

관련 방법좀 알려주시면 감사하겠습니다.

1.
 ![img01](https://cloud.githubusercontent.com/assets/12793072/8401558/2f4e919e-1e6b-11e5-9243-405b686a2ad3.png)
2.
 ![img02](https://cloud.githubusercontent.com/assets/12793072/8401559/2f4eac9c-1e6b-11e5-9cef-f841d58b17fb.png)

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXSelect/select-onexpand.html 혹시 이 예제도 보셨나요?
