### ISSUE TITLE
AXGrid 내 AxContextMenu 지정할때 마우스 오른쪽 클릭으로 활성화 하는 방법

### ISSUE THREAD

**Issue by achiz** [axisj/axisj#640]
안녕하세요.

AXGrid 내 Body 부분에 클릭이벤트로 AxContextMenu 를 디스플레이 하였습니다.

마우스 오른쪽버튼으로 AxContextMenu로 디스플레이 하고싶은데요.

$("#com-context-default-target").on("contextmenu", function(e){
		var pos = $("#com-context-default-open").offset();
		AXContextMenu.open({id:"myContextMenuTree"}, pos);
		return false;
	});

위에는 버튼에 마우스 오른쪽 클릭시 컨텍스트 메뉴가 활성화 되는 부분을 API 에서 참고하였는데

그리드 안에는 on 이벤트를 제공하지 않고 onclick. ondbclick 등만 지원하는것 같습니다.

조언을 기다립니다.

**Comment by hyunjun19** [comment]
AXGrid 자체에 `contextMenu` 옵션이 있는데 별도로 구현하신 이유가 있으신가요?
http://jdoc.axisj.com/AXGrid.html#setConfig -> `contextMenu: {} // API와 예제를 참고하세요. API) http://jdoc.axisj.com/AXContextMenu.html 예제) http://dev.axisj.com/samples/AXCore/AXContextMenu.html`

**Comment by achiz** [comment]
네 말씀하신대로 저 API 는 참고했습니다.
다만 마우스 왼쪽을 클릭해야만 ContextMenu 가 나오는데
저는 오른쪽을 클릭시 나오게 하고싶어서 질문을 드렸습니다.

그럴려면 제가 질의 했던 부분에서 contextmenu 에 이벤트를 걸어줘야 하는데
AxGrid Row 에 이벤트를 어떻게 걸어줘야 하는지 궁금해서 그렇습니다.

제가 잘못 이해한건지요,,?

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXGrid/editor.html 이 예제에서 `contextMenu` 이 부분을 참고해 주세요.
정상적으로 구현되었으면 오른쪽 클릭에 나오게 됩니다.

**Comment by achiz** [comment]
제가 제대로 못봤군요 감사합니다.

**Comment by hyunjun19** [comment]
잘 해결되었나보군요. =)

오른쪽 상단의 `Star`를 클릭해 주시면 개발자에게 큰 힘이 됩니다.

**Comment by achiz** [comment]
늦은시간 까지 피드백 감사합니다 :) Star!
