### ISSUE TITLE
에디터에서 유효성 검사후 값이 넘어가지 않는 상태

### ISSUE THREAD

**Issue by guddhrdl** [axisj/axisj#642]
```js
{key : "itn_Net_Ip"    , align : "center"	, valign : "middle",
								form : {
                                    type  : "text",
                                    value : "itemValue",
                                    validate : function(){
										// 빈칸일 경우 '%'를 입력하겠냐고 물어본다
										if(this.value.dec() == ""){
											g_Msg = "'접속IP'가 빈칸일 경우 '% (모든IP)'를 입력합니다.\n진행 하시겠습니까?";
if(confirm(g_Msg)){
												myGrid.setEditorForm({
													key:"itn_Net_Ip",
												    position:[0, 3],
												    value:"%"
												});
												
												return true;
											}
											else{
												myGrid.focusEditorForm("itn_Net_Ip");
												myGrid.setEditorForm({
													key:"itn_Net_Ip",
												    position:[0, 3],
												    value:""
												});
												
												return false;
											}
										}
										// 빈칸이 아닐경우 그냥 둔다
										else{
											// IP유효성검사
											if(ipFilter(this.value.dec())){
												return true;
											}
											else{
												g_Msg = "올바르지 않은 IP값 입니다. 다시 입력하세요";
												alert(g_Msg);
												
												return false;
											}
										}
                                    }
                                }
							}
```
위 소스와 같이 빈칸일경우
setEditorForm을 통해 %를 넣은 다음, return true 하는 방식인데
값이 response 부터 나오지 않습니다....ㅠ_ㅠ

**Comment by hyunjun19** [comment]
grid.setConfig 구문을 다 올려주세요.
지금 소스만 가지고는 원인을 추정하기가 어렵습니다.

**Comment by guddhrdl** [comment]
/* Config */
			myGrid.setConfig({
				targetID    : "AXGridTarget",
				theme       : "AXGrid",
				sort        : true,				// 정렬
				fitToWidth  : false,			// 너비에 자동 맞춤

				passiveMode : true,             // passiveMode

				colGroup     : getColGroup(),
				colHeadTool  : false,           // 컬럼 display 여부를 설정 합니다. 이 설정은 colGroup의 colHeadTool 보다 우선적으로 적용됩니다.
				colHeadAlign : "center",		// 헤드의 기본 정렬 값 ( colHeadAlign 을 지정하면 colGroup 에서 정의한 정렬이 무시되고,
											    // colHeadAlign : false 이거나 없으면 colGroup 에서 정의한 속성이 적용됩니다.
				fixedRowSeq  :"0" ,
				emptyListMSG : "데이터가 없습니다.",
				colHead : {
                    rows : [
                               [
                                   {colSeq:0   , rowspan:2                                }, // No
                                   {colSeq:1   , rowspan:2                                }, // 사용자명
                                   {colSeq:2   , rowspan:2                                }, // ID
                                   {colSeq:3   , rowspan:2                                }, // 접속IP
                                   {colSeq:4   , rowspan:2                                }, // 이메일
                                   {colSeq:5   , rowspan:2                                }, // 권한
                                   {colSeq:null, colspan:3, label:"로그인", align:"center"}, // 오류건수, 잠김일시, 유효기간을 묶는다
                                   {colSeq:9   , rowspan:2                                }, // 사용여부
                                   {colSeq:10  , rowspan:2                                }, // 변경일자
                                   {colSeq:11  , rowspan:2                                }  // 비밀번호
                               ],
                               [
								   {colSeq:6                                              }, // 오류건수
								   {colSeq:7                                              }, // 잠김일시
								   {colSeq:8                                              }  // 유효기간
                               ]
                    ]
                },
				body : {
					onclick:function() {
						// 계정잠금해제
						if(this.c == 7){
							if(this.item.login_Lck_Dtm != ""){
								userUnlock(this.item.usr_Nm, this.item.usr_Login_Id);
							}
							// 계정이 잠기지 않았을때는 수정할 수 있게 editor를 열어줌
							else{
								myGrid.config.editor.rows[0][2].form.type = "readonly";
								mode = "edt";
								
								// 원래 ID 저장
								update_Usr_Login_Id = this.item.usr_Login_Id;
								myGrid.setEditor(this.item, this.index);
							}
						}
						// 계정 비활성화
						else if(this.c == 9){
							userUse_Yn(this.item.usr_Nm, this.item.usr_Login_Id, this.item.us_Yn);
						}
						// 비밀번호 초기화 버튼 클릭
						else if(this.c == 11){
							pwInit(this.item.usr_Nm, this.item.usr_Login_Id);
						}
						// 계정수정
						else{
							myGrid.config.editor.rows[0][2].form.type = "readonly";
							mode = "edt";
							
							// 원래 ID 저장
							update_Usr_Login_Id = this.item.usr_Login_Id;
							myGrid.setEditor(this.item, this.index);
						}
					},
					addClass: function(){
						// red, green, blue, yellow, white, gray
						if(this.index % 2 == 0){
							return "gray";
						}else{
							return "white";
						}
					}
				},
				page: {
					paging: false,
				},
                editor: {
                    rows: [
                           [
                            // No
                            {key : "no"            , align : "center"	, valign : "middle"},
                            // 사용자명
                            {key : "usr_Nm"        , align : "center"	, valign : "middle",
								form : {
                                    type  : "text",
                                    value : "itemValue",
                                    validate : function(){
										if(this.value == ""){
											g_Msg = "'사용자명'은 필수 입력 항목 입니다.";

											// 토스트 출력
											toast.push({
												body : g_Msg,
												type : 'Warning'
											});
											
											return false;
										} else {
											return true;
										}
									}
                                }
							},
                            // ID
                            {key : "usr_Login_Id"  , align : "center"	, valign : "middle",
								form : {
                                    type  : "text",
                                    value : "itemValue",
                                    validate : function(){
                                    	var value = this.value.dec();
                                    	
                                    	// 등록상태
                                    	if(mode == "new"){
                                    		if(value == ""){
                                    			g_Msg = "'ID'는 필수 입력 항목 입니다.";
                                    			
                                    			// 토스트 출력
                                    			toast.push({
                                    				body : g_Msg,
                                    				type : 'Warning'
                                    			});
                                    			
                                    			return false;
                                    		}
                                    		else{
                                    			// 입력된 ID는 2 < value < 21 범위 안에 들어와야함
                                    			if(value.length < 3 || value.length > 20){
                                    				g_Msg = "ID는 3자 이상 20자 입력해야 합니다.";
                                					
                                					// 토스트 출력
                                        			toast.push({
                                        				body : g_Msg,
                                        				type : 'Warning'
                                        			});

                                					return false;
                                    			}
                                    			else{
                                    				var list = myGrid.getList(true);
                                					
                                					// ID 중복체크
                                					for(var i = 0 ; i < list.length ; i++){
                                						if(value.toLowerCase() == list[i].usr_Login_Id.toLowerCase()){
                                							g_Msg = "&quot;" + value + "&quot;는 사용중인 ID 입니다.\n다른 ID를 입력하세요.";
                                							
                                							// 토스트 출력
                                							toast.push({
                                								body : g_Msg,
                                								type : 'Warning'
                                							});
                                							
                                							return false;
                                						}
                                					}
                                					
                                					return true;
                                    				
//                                    				// ID유효성검사 (알파벳, 숫자만 허용)
//                                    				if(idFilter(value)){
//                                    					
//                                    				}
//                                    				else{
//                                    					g_Msg = "ID는 알파벳과 숫자만 사용할 수 있습니다.";
//                            							
//                            							// 토스트 출력
//                            							toast.push({
//                            								body : g_Msg,
//                            								type : 'Warning'
//                            							});
//                                    					
//                                    					return false;
//                                    				}
                                    			}
                                    		}
                                    	}
                                    	// 수정상태
                                    	else{
                                    		return true;
                                    	}
									}
                                }
							},
                            // 접속IP
                            {key : "itn_Net_Ip"    , align : "center"	, valign : "middle",
								form : {
                                    type  : "text",
                                    value : "itemValue",
                                    validate : function(){
										// 빈칸일 경우 '%'를 입력하겠냐고 물어본다
										if(this.value.dec() == ""){
											g_Msg = "'접속IP'가 빈칸일 경우 '% (모든IP)'를 입력합니다.\n진행 하시겠습니까?";
											
											if(confirm(g_Msg)){
												myGrid.setEditorForm({
													key:"itn_Net_Ip",
												    position:[0, 3],
												    value:"%"
												});
												
												return true;
											}
											else{
												myGrid.focusEditorForm("itn_Net_Ip");
												myGrid.setEditorForm({
													key:"itn_Net_Ip",
												    position:[0, 3],
												    value:""
												});
												
												return false;
											}
										}
										// 빈칸이 아닐경우 그냥 둔다
										else{
											// IP유효성검사
											if(ipFilter(this.value.dec())){
												return true;
											}
											else{
												g_Msg = "올바르지 않은 IP값 입니다. 다시 입력하세요";
												
												// 토스트 출력
                                    			toast.push({
                                    				body : g_Msg,
                                    				type : 'Warning'
                                    			});
												
												return false;
											}
										}
                                    }
                                }
							},
                            // 이메일
                            {key : "eml"           , align : "center"	, valign : "middle",
								form : {
                                    type  : "text",
                                    value : "itemValue",
                                    validate : function(){
										if(this.value == ""){
											g_Msg = "'이메일'은 필수 입력 항목 입니다.";

											// 토스트 출력
											toast.push({
												body : g_Msg,
												type : 'Warning'
											});
											
											return false;
										} else {
											return true;
										}
									}
                                }
							},
                            // 권한
                            {key : "usr_Auth"      , align : "center"	, valign : "middle",
								form   : {
									type  : "text",
									value : "itemText",
									validate : function(){
										if(this.value == ""){
											g_Msg = "'권한'은 필수 선택 항목 입니다.";
		
											// 토스트 출력
											toast.push({
												body : g_Msg,
												type : 'Warning'
											});
											
											return false;
										} else {
											return true;
										}
									}
								},
                            	AXBind : {
                            		type     : "selector",
                            		config : {
                                        appendable : false,
                                        ajaxUrl    : contextPath + "/M00/getCode.json",
                                        ajaxPars   : "cd_Grp_Enm=USR_AUTH"
                                    }
                            	}
							},
                            // 오류건수
                            {key : "login_Err_Cnt" , align : "center"	, valign : "middle"},
                            // 잠김일시
                            {key : "login_Lck_Dtm" , align : "center"	, valign : "middle"},
                            // 유효기간
                            {key : "login_Vld_Perd", align : "center"	, valign : "middle"},
                            // 사용여부
                            {key : "us_Yn"         , align : "center"	, valign : "middle"},
                            // 변경일자
                            {key : "fnl_Edt_Dtm"   , align : "center"	, valign : "middle"},
                            // 비밀번호
                            {key : "usr_Pwd"       , align : "center"	, valign : "middle"}
                        ]
                    ],
                    response: function(){
                    	var pushItem = this.res.item;
                    	
                    	// 200라인 에서 "%"값을 입력했음에도 불구하고 null이 나오는것으로 보아 버그인듯함
                    	// 임시로 ""일때는 강제로 "%"을 주도록 설정하였음
                    	if(pushItem.itn_Net_Ip == ""){
                    		pushItem["itn_Net_Ip"] = "%";
                    	}
                    	
                    	// 추가할 것인지 물어봄
                    	if(this.index == null){
                    		g_Msg = "추가하시겠습니까?";
                    	}
                    	// 수정할 것인지 물어봄
                    	else{
                    		g_Msg = "수정하시겠습니까?";
                    	}
                    	
                    	if(confirm(g_Msg)){
                    		pushItem["update_Usr_Login_Id"] = update_Usr_Login_Id;
                    		update_Usr_Login_Id = null;
                    		
	                    	// 추가
	                    	if(this.index == null){
	                    		var url     = contextPath + path + "/insertUserItem.json";
	                    		var params  = pushItem;
	                    		var success = function(jsonData){
	                    			var result = jsonData.result;
	                    			
	                    			// result != 1 (실패)
	                    			if(result != 1){
	                    				g_Msg = "추가에 실패했습니다. 관리자에게 문의하세요(" + jsonData.errorMsg + ")";
	                    			}
	                    			// result == 1 (성공)
	                    			else{
	                    				g_Msg = "추가되었습니다.";
	                    					
	                   					fnObj.selectList();
	                    			}
	                    			
									alert(g_Msg);
	                    		};

	                    		// Ajax 호출
	                    		ajaxRequest(url, params, success);
	                    	}
	                    	// 수정
	                    	else{
	                    		var url     = contextPath + path + "/updateUserItem.json";
	                    		var params  = pushItem;
	                    		var success = function(jsonData){
	                    			var result = jsonData.result;
	                    			
	                    			// result != 1 (실패)
	                    			if(result != 1){
	                    				g_Msg = "수정에 실패했습니다. 관리자에게 문의하세요(" + jsonData.errorMsg + ")";
	                    			}
	                    			// result == 1 (성공)
	                    			else{
	                    				g_Msg = "수정되었습니다.";

	                    				fnObj.selectList();
	                    			}
	                    			
	                    			alert(g_Msg);
	                    		};

	                    		// Ajax 호출
	                    		ajaxRequest(url, params, success);
	                    	}
                    	}else{
                    		return false;
                    	}
                    }
                }
			});

**Comment by hyunjun19** [comment]
현재 올려주신 일부 소스로는 재현이 불가능 합니다.
여러 기능을 같이 사용한 경우 재현이 가능한 환경이 아니면 답변을 드리기가 어렵습니다.
재현이 가능한 URL을 오픈해 주시거나 나머지 일부 소스(특히 `getColGroup()`)도 올려 주세요.
