### ISSUE TITLE
grid 리스트에 뿌려진 데이터를 엑셀로 다운받을수있는지 문의

### ISSUE THREAD

**Issue by showaging** [axisj/axisj#644]
안녕하세요 고생많으십니다.ㅠㅠ

이번에 궁금한 사항은 grid리스트에 뿌려진 데이터를 엑셀로 변환하여 다운받을 수있는

기능이 있는지 문의드립니다.

항상 감사드립니다.

**Comment by hyunjun19** [comment]
액시스제이만 가지고는 바로 엑셀로 다운받을 수는 없습니다.

http://dev.axisj.com/samples/AXGrid/index.html 여기를 보시면 `forExcel HTML`과 `forExcel JSON` 부분의 데이터를 참고하셔서 구현하시면 될 것 같습니다.

HTML5를 지원하는 브라우저를 사용하신다면 `html5 excel download` 키워드로 검색해보세요.
만약 HTML5를 지원하지 않는 브라우저라면 서버단을 다녀와야 할꺼 같습니다.

**Comment by gaedong2** [comment]
얼마전에 구현을 하였습니다.
방법은 엑시스제이를 이용하여 특정 DIV 에다가 엑셀로 만들어진 테이블로 넣어주고 
그안의 내용을 엑셀로 출력하는 방법을 사용했습니다.

다만 문제점은 이 방법은 오픈브라우져에서만 동작하는 단점이 있습니다.
익스플로러에서 하려고 하니 스크립트 오류가 많이나와서 
그건 POI 라는 툴을 이용해서 엑셀로 내려야 합니다.
