### ISSUE TITLE
AXReq - Before 이벤트는 없나요?

### ISSUE THREAD

**Issue by achiz** [axisj/axisj#645]
안녕하세요 또 질문드립니다.

AXReq 비동기 호출할 시점에 로딩중인 Circle 을 삽입하고 싶은데요.

AxModal 에서 페이지 로딩과 같은 방식으로 처리 하고싶은데.

ApI에서는 onsucc , onerr 이벤트 만 표시되어있는것 같습니다.

조언을 기다립니다.

**Comment by hyunjun19** [comment]
네 현재 별도의 before 이벤트는 없습니다.
jQuery를 이용하시거나 https://api.jquery.com/category/ajax/global-ajax-event-handlers/
AXReq 메서드를 감싸서 별도의 메서드를 만들어서 활용하시는 방법을 추천합니다.
