### ISSUE TITLE
[재질문]AXbind 관련 문의(radio, check)

### ISSUE THREAD

**Issue by kingwhale** [axisj/axisj#646]
bindSelect()를 통해 ajax로 가져온 데이터를 selectbox로 바인드 시키는것처럼
radiobox와 checkbox도 가져온 데이터로 editor 내에 바인드 시키고 싶습니다.

#635 글을 통해 답변을 한번 받긴했는데 잘 이해가 안되서요..

도움 부탁드립니다.

**Comment by hyunjun19** [comment]
제가 질문을 잘못 이해하고 답변을 드린거 같네요.

현재 질문은 AXGrid의 [editor](http://dev.axisj.com/samples/AXGrid/editor.html) 기능을 이용하고 있는데 radiobox와 checkbox도 에디터가 활성화 될 때 ajax로 가져온 데이터를 사용하고 싶으신거죠?

그리고 코드도 같이 올려주시면 답변을 달아 드리는데 많은 도움이 됩니다.
