### ISSUE TITLE
AXCore Date bug 인가요?

### ISSUE THREAD

**Issue by webdes83** [axisj/axisj#648]
시간이 12시로 ..생성..
'1983-06-01'.date().add(0)

23:59으로 생성
'1983-06-01'.date().print('yyyy-mm-dd hh:mi')

diff도 0 으로나와요 훔 24시간이 차이나야 1으로 나오나요?
"2015-07-06 23:59".date().diff("2015-07-07 00:02".date())

**Comment by hyunjun19** [comment]
`diff` 메서드는 단위가 날짜 입니다.
값이 0.12 같이 소수점이 나와도 소수점은 버려버리기 때문에 0이 나옵니다.

만약 좀 더 정교한 날짜 계산이 필요하시다면 개인적으로 [momentjs](http://momentjs.com/)를 추천합니다.
