### ISSUE TITLE
AXGrid 아이템 개수 관련 재문의

### ISSUE THREAD

**Issue by AnSoHyun** [axisj/axisj#650]
안녕하세요. 장마때문에 날씨가 습한데 고생이 많으십니다.
지난번에 문의드린 내용에 대해 재문의합니다.

![image](https://cloud.githubusercontent.com/assets/12961575/8560574/32222fc6-2554-11e5-944e-9e7373a1ffa1.png)

>> 그리고 pushList를 써서 아이템을 추가할 때 아래처럼 실시간으로 아이템 개수가
늘어나지 않을 때가 있습니다. 
![3](https://cloud.githubusercontent.com/assets/12961575/8560624/c9bbf704-2554-11e5-8c25-5790c4b445e1.png)

확인 부탁드리겠습니다. 감사합니다.

**Comment by hyunjun19** [comment]
`전체 n개의 목록이 있습니다.`와 `n Items`는 기본 설정의 차이입니다. [API](http://jdoc.axisj.com/AXConfig.html#AXGrid)에서 설정을 확인해 주세요.

그리고 `pushList` 메서드는 [샘플](http://dev.axisj.com/samples/AXGrid/misc.html)에서 테스트 해봐도 재현이 되지 않고 있습니다. 해당 버그가 나타나는 환경이나 기타 정보가 좀 더 필요합니다. 또는 해당 메서드 사용시 오류가 발새하지 않았는지 확인 부탁드립니다.
