### ISSUE TITLE
modal 에서 axselect 사용시 위치 깨짐 현상.. 

### ISSUE THREAD

**Issue by narsisya** [axisj/axisj#652]
전에 pannel에서 collapse 사용할때는 $(window).resize()를 호출해서 해결햇는대요. 

modal에서 axselect를 사용하고 modal show를 하면 select 박스가 엉뚱한 곳에 생기네요 ㅠㅠ

**Comment by lhslive** [comment]
modal을 open 하신 다음 axselect를 bind 해 주세요.

**Comment by narsisya** [comment]
''	$('#modal').modal('show');
	$("#select_id1").bindSelect();''
이런 간단 소스인데. 위치는 바뀌긴 햇는대 dialog의 젤 왼쪽 에 위치하네요 
window.resize()도 안되구요 ㅠㅠ

![axselect](https://cloud.githubusercontent.com/assets/11439990/8607295/f79f28f2-26cc-11e5-9082-3f1c7b720bd0.png)

**Comment by lhslive** [comment]
...bootstrap사용중 이신가요? 모달을 저런형태로 호출을 하신거 보니 맞는듯 한데요..
axisj는 bootstrap과는 연관이 없습니다..

document.ready에 아래의 트리거를 등록해서 쓰세요

```
		$('#modal').on('shown.bs.modal', function (event) {
			$("#select_id1").bindSelect();
		})
```
