### ISSUE TITLE
Axtree 머지 문의드립니다

### ISSUE THREAD

**Issue by tmdckd86** [axisj/axisj#657]
트리 사용시에 셀머지가능한가요?
시험해보니 머지가안되네요
사진파일첨부하려는데 휴대폰으론안되나요? 매뉴가없네요

**Comment by thomasJang** [comment]
트리에서는 셀머지를 지원하지 않고 있습니다.
그리드에서 트리기능을 추가지원하는 기능을 준비중이니 
http://dev.axisj.com/samples/AXGridtree/index.html 이 샘플에서 가능한지 검토해보시구요.
셀머지가 되어도 트리에서는 제한적으로 사용하셔야 하니 주의 하셔야 겠습니다.
