### ISSUE TITLE
AXSearch 크기 조정에 대해서 문의 드립니다.

### ISSUE THREAD

**Issue by achiz** [axisj/axisj#658]
![div](https://cloud.githubusercontent.com/assets/2038117/8689342/6d7d1f08-2ae1-11e5-8aa8-889d077c9dba.PNG)

안녕하세요.

위의 그림처럼 AXSearch 를 이용하여 항목을 3줄 만들었습니다.

질문은 input padding 값과 div height 를 조절하여 크기를 변경하고싶습니다.

개발자도구를 이용하여 클래스가 'searchGroup ' 으로 된  div 속성값을 변경했는데  깨지는 현상이 

발생하네요. 

마진이나 패딩 값 변경이 깨지지 않고 수정이 가능할까요?

조언 기다리겠습니다. 감사합니다.

**Comment by thomasJang** [comment]
`style` 태그를 이용하여 css를 수정하셔야 제대로 수정이 가능할 것같습니다.
