### ISSUE TITLE
ax그리드 페이징 처리되는 박스 하단에 선이 안나오는현상

### ISSUE THREAD

**Issue by guddhrdl** [axisj/axisj#661]
![default](https://cloud.githubusercontent.com/assets/13061207/8717718/e811386a-2bd8-11e5-8d4d-5b052adfe9fa.png)

다음 그림과 같이 페이징 되는쪽 하단에 선이 안나옵니다.
사용하고 있는 api는 제이쿼리, 부트스트랩 입니다.

**Comment by thomasJang** [comment]
부트스트랩이 모든 엘리먼트의 box-sizing 속성을 border-box로 변경 해버려서 생기는 문제입니다.
해당부분의 CSS를 content-box로 수정해야 하는데요.
저희 테마파일에서 수정을 해서 커밋을 하도록 하겠습니다.

**Comment by guddhrdl** [comment]
빠른 피드백 감사합니다^^
