### ISSUE TITLE
AXSearch 포커스와 AXgrid와 연결시..

### ISSUE THREAD

**Issue by Happy2You** [axisj/axisj#662]
일반 제이쿼리로 된걸 AXISJ로 코드를 변환해보려고 합니다.
그런데 원래 구현이 안되는건지 메뉴얼에 없는건지.. 너무 헤메고 있어서 많은 고수 분들께 문의를 드려봅니다.

* 전체 구현을 하려고 하는 모델은 일반 코드로 진행 하기 쉬운 방법인데.. 여기선 너무 어렵습니다. ㅠㅠ
(1) AXSearch 에서 바코드 입력 바코드라서 마지막에 키값 13번이 오기때문에 13 이벤트 눌러지면
(2) AJAX로 DB에 추가 
(3) AJAX로 새로고침 없이 AXGrid 에서 이를 불러옴

* AXSearch 선수 소개 (상태)
```<script>
	var pageID = "RWD";
	var mySearch = new AXSearch();	
	var fnObj = {
		pageStart: function(){
			mySearch.setConfig({
				targetID:"AXSearchTarget",
				theme : "AXSearch",
                mediaQuery: {
                    mx:{min:0, max:676}, dx:{min:676}
                },
				onsubmit: function(){
					fnObj.search1(); 
				},
				rows:[				
					{display:true, addClass:"gray", style:"", list:[
						{label:"바코드", labelWidth:"100", type:"inputText", width:"200", key:"barcode", addClass:"", valueBoxStyle:"", value:"", title:"바코드",
							onChange: function(changedValue){
								toast.push(changedValue);
								}							
			  		    }												
					]},					
				]
			});
		},
		search1: function(){
			var pars = mySearch.getParam();
			toast.push(pars);
		}	
	};
	jQuery(document).ready(fnObj.pageStart.delay(0.1));
	</script>
```
* AXSearch 문제점
(1) AXSearch 에서 바코드 입력란에 Onload시 반복적으로 포커스가 와야 하는데.. 포커스가 오지 않습니다.  단순히  $('#barcode').focus(); 라고 해도 먹히지 않는걸 보면 ASGrid 처럼 어딘가에 온로드 이벤트에 추가를 해야 할것 같은데.. 어디에 포커스를 추가해야 할까요?

(2)  바코드 란에 바코드를 찍으면 포스트로 값을 DB에 추가합니다.
```
$('#barcode').keydown(function(event) {	
   if (event.keyCode==13) {
     $.post('barcode_test_exe.asp',$('#searchForm').serialize(),function(data) { });	 
     }	
});
```
그런데 AXSearch에 보면 keydown 이벤트를 지원을 않하는건지.. Change 만 동작을 하는것 같습니다.

(3)  이제 그리드에서 해당 JSON으로 가져오면 되는데.. 위에 AXSearch 가 잘 안되니까 , 일단  그냥 INPUT박스로 입력을 해서 AXGrid로 JSON 을 가져오면 화면이 깜빡이는 현상이 나옵니다. 
```
            myGrid.setList({
                ajaxUrl : "loadGrid_BARCODE_TEST.asp",
                ajaxPars: {
                    "param1": "",
                    "param2": ""
                },				
                onLoad  : function(){
                               myGrid.setFocus(0);
                }				
            }); 
```

AXISJ가 어려워서 포기하고.. 또 해보고.. 포기하고 또 해보고..  이제 삼수째인대도..
여전히 어렵네요 ㅠㅠ
하려는 기능은 죄다 안되고..  
힌트라도 받을수 있을까 하는 희망을 갖고 문의를 드려봅니다.

**Comment by thomasJang** [comment]
AXSearch안에 추가한 아이템은 key값이 아이디가 아닙니다.
내부에서 아이디를 생성하기 때문에

http://jdoc.axisj.com/AXSearch.html#getItemId
으로 엘리먼트 아이디를 구하셔야 합니다.

**Comment by Happy2You** [comment]
감사합니다.
