### ISSUE TITLE
간단한 질문 있습니다.

### ISSUE THREAD

**Issue by rlaxodnd89** [axisj/axisj#663]
![33](https://cloud.githubusercontent.com/assets/13363245/8719616/f9cc89c4-2be7-11e5-81b0-24d5177f9036.PNG)

![44](https://cloud.githubusercontent.com/assets/13363245/8719621/09f44dd2-2be8-11e5-85e6-c0cd1c5e03ff.PNG)

배럭스 테마를 이용해서 개발을 하고있습니다.
로그인 화면에서 익스플로러 가로 길이를 일정 이상 늘리면 화면이 다시 줄어들더라고요 어디를 수정해야 이 현상을 제가 원하는대로 변경할 수 있을까요?

**Comment by thomasJang** [comment]
https://github.com/axisj/axu/blob/master/theme/Barracks/admin/ui/cocker/admin.less#L1010
여기를 보시면 미디어 쿼리를 사용하여 해당상황에 맞는 CSS를 정의 해주고 있는데요.
이걸 이해 하시려면 less를 컴파일 할 수 있어야 하고 CSS에 대한 이해가 있어야 합니다.
less컴파일이 가능하다면 https://github.com/axisj/axu/blob/master/theme/Barracks/admin/ui/cocker/admin.less#L31 여기에서 모바일 적용 너비값만 간단히 수정하고 끝낼수도 있겠습니다.
