### ISSUE TITLE
dialog.push 사용 시, z-index 관련 이슈

### ISSUE THREAD

**Issue by socketbear** [axisj/axisj#664]
안녕하십니까?

`div-Modal`과 `dialog.push`를 사용함에 있어서,
2개의 다른 Grid가 포함된 `div-Modal`있다고 가정 시, 첫번째 `div-Modal`에서 `dialog.push`를 호출할 때는 문제 없이  `div-Modal`의 **앞에** 출력됩니다.
이후, 두번째 `div-Modal`에서 `dialog.push`를 출력하면, `div-Modal`의 **뒤에** 출력되어 버튼 등을 조작하기 힘들게 됩니다.

따로 `dialog.push` 출력 시, z-index항목을 부여할 수 있는 지 알고 싶습니다.
확인바라겠습니다.

**Comment by thomasJang** [comment]
스크립트에서는 직접 제어할수 없는 상황입니다.
CSS를 강제 변경해야 처리가 가능합니다.
