### ISSUE TITLE
그리드 목록에서 한글깨짐 현상

### ISSUE THREAD

**Issue by dnzh** [axisj/axisj#670]
안녕하세요.
목록에서 한글 데이터를 불러왔을때 한글이 ????? 로 나옵니다.
JAVA 단에서 UTF-8로 변환하면 일단 한글은 깨지지 않으나
띄어쓰기가 +로 변환되어 나오네요..
똑같은 상황을 겪으신분 있으신가요??

**Comment by hyunjun19** [comment]
fiddler나 크롬 개발자 도구를 이용해서 넘어오는 JSON 데이터를 먼저 확인해 보세요.

**Comment by dnzh** [comment]
아... 데이터가 넘어올때부터 이미 깨져있었나보네요 ^^;;
제대로 확인도 안하고 질문해서 죄송합니다^^;;

**Comment by hyunjun19** [comment]
원인을 찾으셨다니 다행이네요. =)

오른쪽 상단에 Star를 눌러 주시면 개발자에게 큰 힘이 됩니다.
