### ISSUE TITLE
inline-editor 의 이벤트 설정 방법이 궁금합니다.

### ISSUE THREAD

**Issue by seonghyun** [axisj/axisj#672]
이번에 그리드를 변경해 보고자 이리저리 알아보다 알게 되었습니다.

다름이 아니라 그리드 컨피그 설정의 컬럼 설정시 editor 를 설정 할수 있던데...
해당 editor 에 autocomplete 를 적용 하고 싶습니다.

아래의 코드는 인라인에디터 예제에서 text타입 에디터의 설정 내용입니다.
아래 설정 내용 이외의 추가적인 설정이 가능한 옵션 또는 프로퍼티나 오버라이딩 가능한 이벤트가 
있나요?
api문서를 뒤져도 해당 내용을 찾을 수가 없어서요..
```js
key:"string", label:"String", width:"200",
	editor: {
		type: "text",
		maxLength: 5,
		updateWith: ["_CUD"]
	}
```

**Comment by hyunjun19** [comment]
`inline-editor`는 최근에 추가되고 있는 기능이라서 아직 API에 반영되지 않았습니다.
추후에 꼭 API에 꼭 반영하겠습니다.

일단 아래 내용을 참고해 주세요.
해당 API의 config 내용이 `editor.config`와 동일한 내용입니다.
number: http://jdoc.axisj.com/jQueryExtends.html#bindNumber
money: http://jdoc.axisj.com/jQueryExtends.html#bindMoney
calendar: http://jdoc.axisj.com/jQueryExtends.html#bindDate
AXSelect: http://jdoc.axisj.com/jQueryExtends.html#bindSelect

만약 text 처럼 config가 없는 경우는 아래처럼 직접 이벤트를 걸어 주세요.
```js
$('#' + gridId).on('change', '#' + gridId + '_inline_editor', function(e){
    console.log(e.target);
});
```
