### ISSUE TITLE
AXGrid fixedColSeq IE8 버그 발견

### ISSUE THREAD

**Issue by aaboo** [axisj/axisj#675]
늘 저희들 때문에 수고가 많으십니다.
개발자 사이트에서 발견하였습니다.
http://dev.axisj.com/samples/AXGrid/fixedColSeq.html 

![-1](https://cloud.githubusercontent.com/assets/3850967/8947820/e8b2b72e-35da-11e5-8b4b-b58c09811855.gif)

**Comment by thomasJang** [comment]
감사합니다. 체크해보겠습니다.
