### ISSUE TITLE
safari 버전 8.0.7(10600.7.12)에서 AXModal.openNew() 사용시 문제점을 발견 했습니다.

### ISSUE THREAD

**Issue by seokwangseok** [axisj/axisj#676]
사파리에서 모달창을 열었을 때 최초 open시에는 parameter가 정상적으로 전달 되나 window.location.reload()
실행 시에는 location.href에 parameter가 유실된 채로 reload가 되더라구요.

크롬이나 기타 다른 브라우저에서는 별 문제가 없고 사파리에서 나오는 버그인건지 브라우저가 의도한 건지는 잘 모르겠습니다.

**Comment by thomasJang** [comment]
사파리에서 체크 해보겠습니다.

**Comment by thomasJang** [comment]
location.reload가 정상적이지 않다면 
```html
<form name="reloadform" style="display:none">
<input type="hidden" name="key" value="value" />
</form>
<script>
document.reloadform.submit();
</script>
```
으로 대체하여 사용하셔야 하겠습니다.
