### ISSUE TITLE
AXAddress 예제에서의 공공웹서비스 사용

### ISSUE THREAD

**Issue by karfca** [axisj/axisj#677]
이번에 우편번호가 바뀌어서 AXAddress를 이용해서 공공 웹서비스 링크 걸어주신 곳을 이용해 가져올려고 하는데요, 제공되는것이 XML로 제공되네요. 

그리드로 불러와서 페이징 하려고 하는데요, 
Json으로 변환이 만만치가 않습니다. 

그냥 Json 객체 만들어서 XML 노드 돌리면서 하나씩 넣어주는것이 답인가요?
아니면 좀 다른 방법이 있을까요? 

힌트좀 주세요 ^*^
감사합니다.

**Comment by thomasJang** [comment]
요즘은 http://postcode.map.daum.net/guide 이걸 쓰셔야 할겁니다.
고민하지 말고 이걸 적용하세요.

**Comment by karfca** [comment]
감사합니다. 곧바로 적용해보겠습니다^*^
