### ISSUE TITLE
AXUpload5 관련질문이요..

### ISSUE THREAD

**Issue by manuraju** [axisj/axisj#679]
jsp 연동 관련한 쏘스는 없나요??? 
다른 게시판에 질문 올려놨는데 답변이 없네요...
파일 속성 프로퍼티 정의 해놓은 asp 나 php 쏘스에 보면
_FILE_ 이라고 선언되어진 부분과
$file 에서 name 속성 가지고 오는 부분에 대한 설명이 전혀 없는데
어떻게 java에 적용 시킬수가 있나요???
전자정부프레임을 사용중입니다.
혹시나 관련 오픈소스는 없는지???

**Comment by hyunjun19** [comment]
http://open.egovframe.go.kr/cop/bbs/selectProjectArticle.do?projId=8&projTyCode=PROJ01

`AXUpload5`에 맞춰져 있지는 않지만 위 프로젝트의 소스를 참고하시면 될꺼 같습니다.

**Comment by thomasJang** [comment]
https://github.com/axisj/axisj/blob/master/samples/AXUpload5/index.html#L49 
이 값을 바꾸면 됩니다.

**Comment by manuraju** [comment]
1.uploadFileName를 바꾼면 된다고 하시는게 값을 변경했을때 어떻게 자바단에서 받아야 하는건가요?
  ex) param , model 
2.uploadFileName는 파라미터 변수로 선언된건 가요?  아니면 우측의 값이 변수로 선언되는 건가요?

3.우측의 값이 실제 업로드 되는 파일명이라고 한다면 업로드시 그 파일의 명칭을 어떻게 바꿀수 있나요?

4. 설정포맷을 가지고 있는 파일인 uploadUrl에서는 이미 업로드가 되어진 파일을 읽어야 하는 부분인가요? 아니면 업로드 할 부분에 대한 설명만 주어진것인가요???

5.진짜 궁금한건 실제로 읽은 파일에 대한 기본값들을 어떻게 파일에서 인식 시킬수 있나요?
   도통 모르겠음....팝업창에서 업로드 할 파일을 3개 선택해서 올리게 되는 순간에
  어떻게 그 파일명이랑 경로랑 싸이즈랑 jsp페이지로 불러 올수 있나요???

uploadUrl : '/sample/component/fileUpload.do' <<------- 이렇게 사용해서 jsp에서 java로 넘겨야하는데
어떻게 파일정보를 인식해서 xxxxxxxx.do로 넘겨야 할지 알수가 없네요.....
미치겠슴돠....도와주셈....나중에 기부하거나 여기 업체에 말해서 정식 서폿요청 하거나 할께요.
일단 요부분이 자바랑 호환 확인이 되야 할것 같해요....

**Comment by manuraju** [comment]
https://github.com/axisj/axisj/blob/master/samples/AXUpload5/index.html#L49 
이 값을 바꾸면 됩니다.

그값이 뜻하는게 뭔가요???
uploadFileName <---- 이게 변수인가요?
fileData <---- 이게 실제 업로드 될 파일이라는 말씀이신지???

만약 fileData가 파일정보를 가지고 있는 값이라고 한다면
.do를 통해서 자바에서 어떻게 부를수가 있습니까???
parameter로 호출해보았으나 null 이 나오고
model로 불러 보아도 null이 나옵니다.

fileData를 변경하는 방법자체도 이해가 안갑니다.
왜냐면 fileData라는 것을 변경처리 할려면 뭔가 상위에 스크립트라던지
또는 추가적인 로직이 필요할텐데 어디서 추가적인 로직을 생성을 해야 할지 이해가 안됩니다.

uploadUrl 이라는 곳에서 처리되어져서 나오는 값은 실제로 업로드 된 후에
그 값을 읽을때 사용하는 것인데....해당 값들자체를 어떻게 읽어 들이는 지도 
설명이 필요할 것 같습니다.

**Comment by manuraju** [comment]
fileData 부분이 실제 업로드 될 값이 셋팅되어야 할것 같은데
어떻게 셋팅하나요????
셋팅방법관련해서 좀 알려주세요...
uploadFileName
