### ISSUE TITLE
이슈 적어 둔 글 삭제 처리했어요?

### ISSUE THREAD

**Issue by manuraju** [axisj/axisj#681]
흠.....
왜 없어졌지?

**Comment by thomasJang** [comment]
https://github.com/axisj/axisj/issues/679 님께서 close 하셨네요

**Comment by manuraju** [comment]
네 그렇쿤요.....AXUpload5에서 파일정보를 가져와서  onStart 호출 직전에 queue로 담을때 정보가 사라져버리더군요.
바로직전까지는 파일에 대한 정보를 추적할수가 있엇는데 ...
이게 정상적인것인지 아니면 개발환경 셋팅이 잘못된건지 판단을 할수가 없네요.
수고하세요....

**Comment by thomasJang** [comment]
도와 드리고 싶은데 지금처럼 문의 하시면 도와드릴수가 없어요.
조금 더 샘플코드를 보고 연구를 해보시는게 좋을 것 같습니다.

**Comment by thomasJang** [comment]
https://github.com/axisj/axisj/issues/368 이글 참고하시구요

**Comment by manuraju** [comment]
아 그게 ... 여기가 인터넷이 연결이 안되있거든요.
대외적으로 연결이 안된 내부망이라서 캡쳐 및 소스코드를 보여드리고 싶은데도  
그럴수 있는 환경이 아니에요.
간략하게 글로 표현할수 밖에 없네요..
