### ISSUE TITLE
AXSelect의 바인딩시에 문제점 발생

### ISSUE THREAD

**Issue by karfca** [axisj/axisj#682]
AXSelect를 Ajax로 바인딩해서 사용중인데요, 

제가 Tab 을 사용한 페이지에서 계속 SelectBox가 렌더링이 이상한듯해서 이래저래 살피다가 일단
그 문제를 해결하고 보니, SelectBox가 선택이 잘 안되는 겁니다. 

이래저래 Tab 문제라고 생각하고 계속 고민고민하다가 
일단 현재는 포기한 상태인데요...

증상은 SelectBox를 Ajax로 대략 5개 정도 셋팅하고 데이터값을 BindSelectSetValue 하려고 하면 
어느것은 선택이 되는데 어느것은 선택이 안되는듯합니다. 

하는수없이 현재는 DB에서 가져오지 않고 하드코딩으로 넣어서 대부분 가져오고 
꼭 DB에서 가져와야 하는 SelectBox만 2개 가져오는 중입니다. 

혹시 이런 현상 해결방법이 있을까요?

Ajax를 모두 Async = false로 해도 결과는 마찬가지 인듯하네요.

오랜만에 코딩을 잡아보는지라 액시스제이 공부하면서 시간가는줄 모르고 있는데, 
정말 재미있네요..

훌륭한 프레임워크 감사드려요.

**Comment by thomasJang** [comment]
http://dev.axisj.com/samples/AXSelect/select-test.html 테스트를 해보았는데. 별다른 문제를 찾을 수가 없습니다.

**Comment by karfca** [comment]
답변 감사드립니다.

좀더 상세히 설명을 드렸어야 하는데...

1. SelectBox에 Ajax 로딩은 문제가 없었습니다. 5개 모두 정상 리스트가 나타났습니다. 
2. 모두 나타난다음에 Ajax로 사용자 정보 데이터를 가져온 후에 SelectBox에 해당하는 값들을 
BindSelectSetValue() 하는데 이때 선택값이 선택이 안되는 현상입니다. 
3. 이 상태에서 버튼을 만들어서 설정해보면 정상적으로 선택이됩니다. 
단지, SelectBox를 모두 가져와서 설정하고 그 이후 데이터를 가져와서 SelectBox들을 초기값 선택할때
초기값이 설정이 안되는 상황입니다. 

그러므로, 예제에서 버튼 이벤트가 아니라 Ajax로 가져와서 자동으로 초기값들을 설정하는 것으로 테스트
해봐주시면 감사하겠습니다. 

저같은 경우에는 첫번째 SelectBox값은 설정이 되는데 총 5개 중에 3번째것들부터 설정이 안되기 시작했습니다. 

감사합니다

**Comment by suromind** [comment]
혹시 onLoad에서 값을 선택하셧나요? 버튼을 만들어서 선택하면 된다고 하는걸 보니
리스트가 덜 불러와졌는데 값을 선택하신것 같네여

**Comment by gaedong2** [comment]
ajax 로 디비를 갔다오는 시간이 
프로그램 셋팅시간보다 느려서 그런겁니다..

하드코딩으로 진행해보시면 될꺼에요 ..

이벤트를 순차적으로 발생시켜야 할듯합니다.

**Comment by karfca** [comment]
다른분들의 답변 감사드립니다. 
일단, 2개는 Ajax로 가져오고 나머지 3개는 하드코딩으로 동작시키니 정상적으로 설정이 되었습니다. 

설정은 Start에서 맨 마지막에 진행하긴 했는데, 그래도 첫부분것은 되고 다른 것은 안되거나 하는 등의 문제가 있는것으로 봐서 아무래도 로딩시 문제라고 보는게 맞을듯하네요. 

Async 옵션만으로는 해결이 안되는가보네요? ^*^ 

일단 내용설명은 어느정도된거 같고, 답변 의견주신 분들도 시간차이때문이라고 보시는것이니
특별히 더 끌지 않고 이정도 선에서 Close하는게 좋지 않을까합니다^*^ 

ㄳ합니다. ^*^
