### ISSUE TITLE
인라인에디팅시 +포함되어 있을때의 버그 문의

### ISSUE THREAD

**Issue by saladbar** [axisj/axisj#685]
기존 인라인에디팅시 input에 "+"가 포함되어 있을 경우
수정시에 "+"가 사라지는 버그가 있어 임시로 아래와 같이 사용하고 있었습니다.(v1.0.15)
String.prototype.dec = function(){
 return decodeURIComponent(this);
}
위의코드 사용시 "%"가 있을 경우 decodeURIComponent()에서 에러 발생하여 수정이 필요한 상황입니다.

최신버전받아 테스트해보니 
            if (Object.isString(obj.ajaxPars)) {
                formPars.push(obj.ajaxPars);
obj is not defined 에러가 발생하고 있습니다.

버그 수정 부탁드립니다.

**Comment by thomasJang** [comment]
```
if (Object.isString(obj.ajaxPars)) {
formPars.push(obj.ajaxPars);
```
이 구문이 어디에 있는건지 알려주세요.

그리고 %관련한 에러는 서버사이드에서 리턴하는 json의 mime Type을 알아야 해결이 가능합니다.

**Comment by thomasJang** [comment]
```js
String.prototype.dec = function(){
  return decodeURIComponent(this.replace(/%/g, encodeURIComponent("%")));
}
```

**Comment by thomasJang** [comment]
```js
String.prototype.dec = function(){
		var result;
		try {
			result = decodeURIComponent(this);
		}
		catch (e) {
			result =  unescape(this);
		}
		return result;
}
```
