### ISSUE TITLE
안녕하세요 AXReq에 관해서 질문 드립니다. 

### ISSUE THREAD

**Issue by fakejolie** [axisj/axisj#687]
안녕하세요 AXReq에 관해서 질문 드립니다.
아직 Ajax와 자바스크립트에 익숙하지 않은데, AXISJ로 덜컥 개발업무를 맡게된 신입입니다.

springMVC와 mySql을 연동하여 사용하고 있습니다. 

그리드 삭제기능을 만들고 있는데요. AXReq 부분에서 질문이 생겨서 글 남깁니다. 

                                       remove: function(){
					var checkedList = myGrid.getCheckedList(0);
					if(checkedList.length == 0){
						alert("선택된 목록이 없습니다. 삭제하시려는 목록을 체크하세요");	
						return;
					}
					if(!confirm("정말 삭제 하시겠습니까?")) return;
					var id=checkedList[0].id;
					mask.open();
					var url = "/userList/"+id;
				/* 	var pas = [];
					$.each(checkedList, function(){
						pas.push("id="+id);
					}); 
					var pars = pas.join("&") + "&method=D"  */
			 		new AXReq(url,  {debug:false,  /* pars:pars,*/  
			 			
			 			onsucc:function(res){
						//console.info("res",res.result);
							if(res.result == AXUtil.ajaxOkCode){
								//alert("삭제완료");
								fnObj.grid.search();
								toast.push("삭제 되었습니다.");
							mask.close();
							
							}else{
								AXUtil.alert(res);
							}
						onerr:
							alert("에러발생");
						},
					});

삭제 부분 함수인데요, AXReq 부분에서 oncc:함수와 onerr: 함수가 둘다 실행이 되질 않습니다.
혹시 통신의 문제인가 하고 봤는데..컨트롤러는 타고 있어요..고로 삭제는 되고있는데 
AXReq 안에 모든 함수가 실행이 안되고 있습니다. 무엇이 문제인지..파악이 잘 안되서요..

 그리고 res가 response 값인거 같은데 맞나요? 

ㅠㅠ 저 res값이 무엇인지도 잘모르겠고..

이런 초짜의 질문도 받아주시나요.. ㅠ_ㅠ 질문할 곳을 찾다 찾다 여기다 남겨봅니다..

**Comment by thomasJang** [comment]
AXReq보다 jquery.AJAX를 먼저 보셔야 할 것 같구요.
그보다 AJAX가 무엇인지 보셔야 할 것 같습니다.

그리고 브라우저 콘솔 사용법을 익히셔서 network 탭을 보셔야 합니다. 실마리가 안풀리면 다시 질문 하세요

**Comment by fakejolie** [comment]
음...삭제버튼을 누르고서 network 탭을 봤는데요. 에러 없이 전부 200으로 ok가 나왔어요.  
onsucc 라는 부분이 통신이 성공하면 실행이 되는 부분 아닌가요...?

제가 컨트롤러에서 redirect 를 시켜주고 있는데 이거와 관련된 문제인건지..
ㅠ_ㅠ

**Comment by thomasJang** [comment]
200이면 response값이 무엇인지 보세요. json을 뿌려줘야 해결이 됩니다.
