### ISSUE TITLE
Tree 겟체크드 리스트 값이 콘솔에 안찍히네요(버그인듯..)

### ISSUE THREAD

**Issue by david80** [axisj/axisj#688]
http://dev.axisj.com/samples/AXTree/treeCheckbox.html

체크박스를 하고 나서 getCheckedList(0) 값을 못가져 오는것 같습니다..

최근에 패치된후에 안되는듯해요

버그인듯..

**Comment by hyunjun19** [comment]
기능개선하면서 생긴 버그였네요,
버그리포트 감사합니다. =)
