### ISSUE TITLE
버그.. 트리그리드컨트롤에서 창크기를 변경하니까 체크한게 사라지네요.

### ISSUE THREAD

**Issue by david80** [axisj/axisj#691]
http://dev.axisj.com/samples/AXTree/treeCheckbox.html

체크했던 게 창크기 변경할때 사라집니다..

**Comment by hyunjun19** [comment]
창크기가 변경될 때 트리를 다시 그리는데 체크 정보가 날아가네요.
요즘 바빠서 고치는데 시간이 좀 걸릴거 같습니다. =(

**Comment by thomasJang** [comment]
수정되었습니다.

**Comment by hyunjun19** [comment]
:+1:
