### ISSUE TITLE
AXGrid에 editor모드 에서 select 문의 드립니다.

### ISSUE THREAD

**Issue by netmagic** [axisj/axisj#695]
AXGrid에서 editor모드로 항목 수정시 select의 선택에 관한 문의 드립니다.

![1](https://cloud.githubusercontent.com/assets/9062461/9540568/2ae52de8-4d9b-11e5-8dee-3747626e9f37.png)

위의 그림처럼 수정을 위해 항목을 클릭하면 사용여부의 select 옵션은 ajax로 정보를 받아 보여주고 있습니다.

그런데, 예를들어 12번 항목을 수정하기 위해 클릭하면 select가 1001Y가 기본 선택되어야 하는데 첫번째 항목이 기본 선택되어 있습니다.(1001$)
ajax가 아닌 options로 정보를 입력하면 정상동작 합니다. 제가 잘못한건지 확인 부탁드립니다.
<pre>
{
	colSeq: 8, align: "left", valign: "top",
	form: {
	    type: "select",
	    value: function () {
	        return this.value.dec();
	    },
	    validate: function () {
	        return true;
	    },
	    options:[ // 테스트를 위해 axbind삭제후 아래 값을 입력, 정상 동작 확인
	        {value:'1001$', text:"1001$"},
	        {value:'1001Y', text:"1001Y"},
	        {value:'1001N', text:"1001N"}
	    ]
	},
	AXBind: { // form.options 제거 후 axbind 추가. 항목은 잘 표시되나 첫번째 항목이 기본선택됨
	    type: "select", config: {
	        ajaxUrl: "/system/globalcode/minorcodes",
	        ajaxPars: "major_code=1001",
	        reserveKeys: {
	            optionValue: "code",
	            optionText: "code"
	        },
	        onchange: function () {
	        }
	    }
	}
},
</pre>

/system/globalcode/minorcodes 호출시 리턴되는 json 데이터
<pre>
{"result":"ok",
 "options":[
      {"code":"1001$","majorCode":"1001","minorCode":"$"},       
      {"code":"1001Y","majorCode":"1001","minorCode":"Y"}, 
      {"code":"1001N","majorCode":"1001","minorCode":"N"}
  ]
}
</pre>

라이브러리 매우 잘 사용하고 있습니다. 감사합니다.

**Comment by hyunjun19** [comment]
AXGrid 버전이 어떻게 되나요?
가능하시면 최신버전으로 업데이트 후 테스트 부탁드립니다.

그리고 소스 버전을 올리지 않고 해결하시려만 아래 방법대로 하시면 될꺼에요.
http://dev.axisj.com/samples/AXGrid/inline-edit.html 이 예제 소스에서 combobox2 처럼 포멧터를 추가해주세요.

이렇게요.
```js
{
    colSeq: 8, align: "left", valign: "top",
    form: {
        type: "select",
        value: function () {
            return this.value.dec();
        },
        validate: function () {
            return true;
        },
	formatter: function(val){
		if(Object.isObject(this.value)){
			return this.value.code;
		}else{
			return this.value;
		}
	},
    },
    AXBind: { // form.options 제거 후 axbind 추가. 항목은 잘 표시되나 첫번째 항목이 기본선택됨
        type: "select", config: {
            ajaxUrl: "/system/globalcode/minorcodes",
            ajaxPars: "major_code=1001",
            reserveKeys: {
                optionValue: "code",
                optionText: "code"
            },
            onchange: function () {
            }
        }
    }
},
```

**Comment by netmagic** [comment]
답변 감사드립니다. 

제가 헷갈려서 질문에 오류가 있네요. passiveMode에서 생기는 문제입니다.

라인 단위로 DB를 업데이트 하기위해서 inline-edit이 아니라 passive로 작성을 한거구요,

말씀하신 formatter를 추가했으나 console로 val을 찍어보니 아예 호출을 안하는것 같습니다.

AXGrid는 소스 보니 4.3.6 버전이며 전체를 bower로 설치한 상태입니다. 
CDN버전으로 변경해도 그대로네요.
