### ISSUE TITLE
새로 열린 모달창에서 부모창의 AXSearch inputText 에 포커스를 주는 방법??

### ISSUE THREAD

**Issue by Happy2You** [axisj/axisj#696]
```
  window.open(url ,"pop1", "toolbar=no, width=900, height=580"); 
```
1) 위와 같은 방법으로 열린 모달창에서 부모창의 AXSearch barcode라는 inputText에 포커스를 주려고 합니다. 일반 객체의 경우 
그냥  아래처럼 포커스를 줬는데요. 
```
$("#barcode", opener.document).focus();
```

AXSearch에서는 아래처럼 줘봤는데.. 역시 안되고 있습니다.
어떻게 해야 하나요? 
```
$(axdom("#" + mySearch.getItemId("barcode")), opener.document).val(this.item.plu_name);
```

**Comment by hyunjun19** [comment]
$("#barcode", opener.document).focus();
이 구문이 맞는거 같은데요. 혹시 "#barcode" 아이디가 맞는지 확인해 보세요.

**Comment by Happy2You** [comment]
네.. 다른 일반 DOM은 값을 잘 가져오고 포커스도 잘 됩니다. 
또 모달창이 아닌 부모창내에서는 axdom("#" + mySearch.getItemId("barcode")) 형태로 접근이나 사용이 잘 됩니다. 
다만.. 모달에서 부모창의 AXSearch inputText에 접근이 안된다는 거죠.. 
문법이 틀린건지.. 답답합니다. 

지금은 부모창에 히든객체를 만들어서 거쳐서 사용을 하고 있습니다. ㅠㅠ

**Comment by hyunjun19** [comment]
제 예상으로는 barcode 아이디 때문인거 같습니다.
팝업창에서 아래처럼 호출해 보세요.
```js
$("#" + opener.mySearch.getItemId("barcode"), opener.document).focus();
```

**Comment by Happy2You** [comment]
아~ 잘됩니다. ^^ 
답변 감사드립니다.~~~
