### ISSUE TITLE
ax그리드 thead 부분이 첫 화면에서는 보이지 않으나 창 사이즈를 늘리거나 줄이면 보이는 현상

### ISSUE THREAD

**Issue by ws84** [axisj/axisj#699]
첫화면에서는 이렇게 보이나 
![image](https://cloud.githubusercontent.com/assets/14065353/9594750/27cb1b7a-509a-11e5-92a2-bc671cf90a29.png)

창 사이즈를 조절하면
![image](https://cloud.githubusercontent.com/assets/14065353/9594758/59e29d18-509a-11e5-835a-3977f0fb4020.png)
정상적으로 나오게 되는데

thead부분의 height값이 0이였다 값을 가졌다 하는 현상이 생기는데 수정하려면 어떻게 해야 하나요?

**Comment by hyunjun19** [comment]
증상을 재현하려면 어떻게 해야 하나요?
AXModal에서 iframe을 호출하신건가요?
모든 브라우저에서 동일하게 보이나요?

일단 임시방편을 알려드리자면 아래처럼 해보세요.
```js
$(function(){
    setTimeout(myGrid.redraw, 100);
});
```

**Comment by thomasJang** [comment]
display:none 인 엘리먼트에 그리드를 추가한 경우로 판단됩니다.
$(window).resize()를 호출해주면 살아나는데요.
가능하다면 display:none이 엘리먼트에 그리드를 추가하세요
