### ISSUE TITLE
그리드 데이타 ajax로 edit후 myGrid.redrawGrid(); 시에 스크롤 문제 인데요..

### ISSUE THREAD

**Issue by yoohyunseok** [axisj/axisj#700]
![untitled-1_02](https://cloud.githubusercontent.com/assets/14068120/9597441/a809f758-50bc-11e5-84b0-f1385f681aa9.jpg)
![untitled-1_03](https://cloud.githubusercontent.com/assets/14068120/9597457/c8cf5c76-50bc-11e5-91d8-5b8838f5fdd8.jpg)

에디트후에 그리드의 값을 재정렬해주면서 방금 수정햇던 라인에 스크롤이 멈춰있게 하고 싶은데 잘안되네요.;;
myGrid.redrawGrid();  하면 상단으로 가버려서요.
이미지에 보이지는 금액부분은 json으로 가져온 값을 화면에서 계산해서 뿌리는 부분이라서 myGrid.redrawGrid(); 가필요한데요.

contentScrollContentSync 함수도 써보앗지만 스크롤은 이동하나 내용은 처음 화면에 내용이 보이구요..
혹시 해결방법이 있을가요?

**Comment by hyunjun19** [comment]
`myGrid.printList()` 메서드를 사용해보세요. 스크롤이 완전히 같은 위치에 있지는 않지만 그래도 포커스는 유지될껍니다.

그런데 혹시 값의 계산을 `formatter`로 하시나요? `formatter`로 계산하시면 가상 스크롤 때문에 계산값에 버그가 있을 수 있으니 꼭 myGrid.list의 값을 업데이트 하시는 방법을 사용하세요.

**Comment by yoohyunseok** [comment]
답변 감사합니다.
계산은 푸터부분에서 for문돌려서 넣어주고 있어서 금액에 계산값은 틀리지 않고있습니다.
myGrid.printList() 를 써보았는데 역시나 스크롤 이동이 생겨서요 ㅎㅎ..

일단 임시방편으로 
success : function(json){
var gridScroll = Number($("#grid_AX_scrollYHandle").css("top").replace(/\px/g,''));
var gridScroll2 = Number($("#grid_AX_scrollContent").css("top").replace(/\px/g,''));
myGrid.redrawGrid(); 
$("#grid_AX_scrollYHandle").css("top",gridScroll);
$("#grid_AX_scrollContent").css("top",gridScroll2);
}
ajax 후 이런식으로 위치 잡아주는걸로 해결 되었습니다.
