### ISSUE TITLE
수고하십니다. 질문을 올려도 되나 모르겠네요??

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#703]
국산 UI 라이브러니 중에 이렇게 좋은게 있는줄 얼마전에 알았습니다.

새로시작하는 프로젝트에 사용해 볼까하는데 참 좋네요~

한가지 기능을 못찾아서 헤매고 있는데요.

axgrid에서 헤더는 높이 사이즈는 지정할수 있는데 본문도 가능한지요??

그럼 수고하세요~

![2015-09-02 10 23 48](https://cloud.githubusercontent.com/assets/12386521/9621072/eb86c6dc-515c-11e5-82f9-965f7c521261.jpg)

**Comment by groovedk** [comment]
따로 지정할 수 있는 옵션은 없으나 css 로 수정 할 수 있습니다. 
하지만 높이를 늘릴경우 기존의 그라데이션이 들어간  css경우 깨져보일 수 있습니다.

**Comment by cococl** [comment]
AXGrid.css 를 추가하고 높이는 지정해주니까 되는군요 감사합니다.
