### ISSUE TITLE
파일 첨부에서 삭제버튼이 사라지는 현상

### ISSUE THREAD

**Issue by kane815** [axisj/axisj#707]
안녕하세요 파일첨부 관련해서 삭제버튼이 사라지는 현상이 있어서 문의드립니다.

![1](https://cloud.githubusercontent.com/assets/14118685/9674447/23b97bb8-52ec-11e5-8f7d-fa5ba6f98623.png)

그림과 같이 처음 로딩될때는 첨부파일들이 잘 불러와 지는데요.
하나를 삭제하고 나면

![2](https://cloud.githubusercontent.com/assets/14118685/9674463/47b97536-52ec-11e5-870e-7ab5f60e3aa4.png)

다음과 같이 다른 삭제(x)버튼들이 사라지는 현상이 있습니다.
이 상태에서 파일올리기를 하여 첨부파일을 추가하면

![3](https://cloud.githubusercontent.com/assets/14118685/9674473/6539630a-52ec-11e5-8a0a-3791338bbd76.png)

다음과 같이 추가한 파일에 대해서는 삭제버튼이 정상적으로 생깁니다.
이 상태에서 새로 추가한 파일을 삭제하면

![4](https://cloud.githubusercontent.com/assets/14118685/9674483/7c21ee7a-52ec-11e5-8b54-7e709b8fa68a.png)

추가한 파일에 대해서는 삭제버튼이 정상적으로 남아있는데요.

이 상태에 대한 원인과 해결책을 좀 알고 싶은데요.

저만 이런 증상인지도 궁금하기도 합니다.

**Comment by hyunjun19** [comment]
http://dev.axisj.com/samples/AXUpload5/listType.html 여기에서 테스트 해본 결과 해당 현상이 없는거 같은데요.

이런 경우 관련 코드를 전부 보여주시거나 저희가 테스트해 볼 수 있는 링크를 하나 열어주시는게(이 방법이 가장 확실해요) 가장 빠른 해결책입니다.

**Comment by kane815** [comment]
//jsp 소스입니다. 사진첨부관련 소스부분을 위주로 발췌한 본입니다.

	var fnObj = {
		
		pageStart:function(){
			var parntsSprtr = "TN_RELATE_PRSN_" + $("#prsn_sn").val();
			fileObj.upload.init(parntsSprtr);
						//변경사항 저장
			save: function(){
				                
                var url = "/specialistInfoEdit.json";
              	var pars = "";
              	
              	var po = [];
                var file_list = fileObj.upload.printMethodReturn('getUploadedList', 'object');
                var po_file = [];
                
                $('#orginl_photo_file_nm').val('');
    			
                $.each(file_list , function(){
                	var form = document.commonBbs;
                	//부모구분자(테이블명_key_key_...)
                	var parntsSprtr = "TN_RELATE_PRSN_";
                	var file_data = (this.fileSn||"").dec() + "*" +(this.fileCours||"").dec() + "*" + (this.orginlFileNm||"").dec()+ "*" + (this.fileNm||"").dec() + "*" + (this.fileExtsn||"").dec() + "*" + (this.fileMg||"").dec() + "*" + parntsSprtr;
                	po_file.push("file_data="+file_data);
                	$('#orginl_photo_file_nm').val((this.fileCours||"").dec());
                	 
                });
                if(po_file.length > 1){
                	alert("[필수] 사진첨부는 1개만 가능합니다");
                	return false;
                }
                
    			po.push(axdom(document["commonBbs"]).serialize());   
    			pars = po.join("&")+ "&" +po_file.join("&");
    			if(!confirm("저장하시겠습니까?")) return false;
                new AXReq(url, 
                    {
                        pars:pars,
                        onsucc:function(res){
                            if(res.result.isOK){
                        		alert("정상적으로 저장되었습니다.");
                                $('#commonBbs').attr("action","/specialistInfo.do").attr('method','post').submit();
                            }else{
                            	//TODO:확인하삼
                        		alert("[실패]");
                            	AXUtil.alert(res);
                                //trace(res);
                            }
                        },
                        onerr:function(res){
                        	alert(res);
                    	}

                    }
                );
                return false;                
			}
		}
	}

//파일 업로드 js 부분입니다.

var myUpload = new AXUpload5();

var fileObj = {
	fileManager: {
		list:function(renderID,parntsSprtr){
			
			var url = "/cmm/file/selectFileInfs.json";
			var pars = "parntsSprtr=" + parntsSprtr;
			
            new AXReq(url, {pars: pars, onsucc: function(res) {
                var hasfile = false;
                
                if (!res.error) {
                    var po = [];
                    var items = res.fileList;
                    
                    if (items != "") {
                        $.each(items, function(di, dobj) {
                            po.push("<span onclick=\"fileObj.fileManager.down('" + dobj.fileCours.enc() + "','" + dobj.orginlFileNm + "');\" style=\"border-top:none; cursor:pointer; border-bottom:1px solid #a0a0a0;\">" + dobj.orginlFileNm.dec() + "</span>");
                            po.push("<br/>");
                            
                            hasfile = true;
                        });
                    }
                    $("#" + renderID).html(po.join(''));
                }
                if (!hasfile) $("#" + renderID).html('첨부파일이 없습니다.');
            }
            });
		},
		down:function(fileCours,orginlFileNm){	//경로와 원본파일파일 이름
			var url = encodeURI("/cmm/file/FileDown.do?fileCours="+fileCours.dec() + "&orginlFileNm=" + orginlFileNm.enc());			
			location.href= url;
		}	
	},
    upload: {
    	post: function(){ return this.target; },	
			init: function(parntsSprtr){
			myUpload.setConfig({
				targetID:"AXUpload5",
				targetButtonClass:"Green",		//업로드 버튼에 추가될 CSS
				//openMode:"view",				//삭제 버튼을 숨김
				uploadFileName:"files",		//서버에 전송될 파일 파라미터 키이름
				file_types:"image/*",  		//audio/*|video/*|image/*|MIME_type (accept)
				dropBoxID:"uploadQueueBox",
				queueBoxID:"uploadQueueBox", // upload queue targetID
				//queueBoxAppendType:"(prepend || append)",
				// html 5를 지원하지 않는 브라우저를 위한 swf upload 설정 원치 않는 경우엔 선언 하지 않아도 됩니다. ------- s
				flash_url : "/plugins/axisj/lib/swfupload.swf",
				flash9_url : "/plugins/axisj/lib/swfupload_fp9.swf",
				flash_file_types:"*.jpg;*.jpeg;*.gif;*.bmp;*.png",
				flash_file_types_description:"image",
				// --------- e
				onClickUploadedItem: function(){ // 업로드된 목록을 클릭했을 때.
						var url = encodeURI("/cmm/file/FileDown.do?fileSn="+this.fileSn.dec() + "&fileCours=" + this.fileCours.dec() + "&fileNm=" + this.fileNm.dec() + "&orginlFileNm=" + this.orginlFileNm.enc());
					location.href= url;
    			},
		        					
				uploadMaxFileSize:(200000*1024*1024), 		// 업로드될 개별 파일 사이즈 (클라이언트에서 제한하는 사이즈 이지 서버에서 설정되는 값이 아닙니다.)
				uploadMaxFileCount:1, 						// 업로드될 파일갯수 제한 0 은 무제한
				//uploadUrl:"/cmm/file/selectFileInfsForUpdate.do" ,					// 서버전송 
				uploadUrl:"/singlePhotoUpload.do" ,					// 서버전송

				uploadPars:{updateCond:"N"},
				
				// 서버전송 url 파라미터
				deleteUrl:"/cmm/file/deleteFileInfs.json",
				
				/* deletePars:{userID:'tom', userName:'액시스'}, */
				deletePars:{},
				
				buttonTxt:"파일올리기",

				fileKeys:{ // 서버에서 리턴하는 json key 정의 (id는 예약어 사용할 수 없음)
						id:"fileSn",		
						name:"orginlFileNm",
						type:"fileExtsn",
						saveName:"fileNm",
						fileSize:"fileMg",
						uploadedPath:"fileCours",
						thumbPath:"fileCours",
						atchmnflSn:"atchmnflSn"
						// 서버에서 키값을 다르게 설정 할 수 있다는 것을 확인 하기 위해 이름을 다르게 처리한 예제 입니다.
				},

				onbeforeFileSelect: function(){
					return true;
				},

				onUpload: function(){
					
				},
				onComplete: function(){
					
				},
				onStart: function(){
					
				},
				onDelete: function(){
					trace("this " , this.file);
				},
				onError: function(errorType, extData){
					if(errorType == "html5Support"){
						//dialog.push('The File APIs are not fully supported in this browser.');
					}else if(errorType == "fileSize"){
						//trace(extData);
						alert("파일사이즈가 초과된 파일을 업로드 할 수 없습니다. 업로드 목록에서 제외 합니다.\n("+extData.name+" : "+extData.size.byte()+")");
					}else if(errorType == "fileCount"){
						alert("업로드 갯수 초과 초과된 아이템은 업로드 되지 않습니다.");
					}
				}
			});

			// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- s
			var url = "/cmm/file/selectFileInfs.json";
			//부모구분자(테이블명_key_key_...)
			var pars = "parntsSprtr="+parntsSprtr;
			 
			new AXReq(url, {pars:pars, onsucc:function(res){
				if(!res.error){
					//trace("res.fileList: " ,res.fileList);
					myUpload.setUploadedList(res.fileList);
				}else{
					alert(res.msg.dec());
				}
			}
			});
			// 서버에 저장된 파일 목록을 불러와 업로드된 목록에 추가 합니다. ----------------------------- e

		},
		printMethodReturn: function(method, type){
			
			var list = myUpload[method](type);
		    return list;
			}
    }
};

**Comment by hyunjun19** [comment]
음... 소스로 봐서는 원인을 모르겠네요.

일단 문제 해결을 위한 디버깅 방법을 알려드릴께요.
1. 크롬에서 해당 페이지를 열고 `F12`를 누르세요.
2. 원치않게 사라져버리는 `X` 표시를 우클릭 후 `요소검사`를 클릭
3. 나타난 개발자 도구 창에서 `X`에 해당되는 DOM 코드를 우클릭 후 `Break on...` > `Node removal`을 클릭하세요.
4. 이제 해당 증상을 다시 재현하세요.

위처럼 하시면 해당 `X`가 사라질때 js 소스에 브레이크 포인트가 걸릴꺼에요. 그 부분을 따라가 보세요.
