### ISSUE TITLE
그리드의 가로 길이 조절을 막을 수 있을까요??

### ISSUE THREAD

**Issue by freecatz** [axisj/axisj#712]
그리드의 헤더의  가로 사이즈 조절 기능을 막고 싶습니다.

여러모로 검색해 보다가 찾지 못해 질문 올리게 되었습니다.

깃헙에 글은 처음올려서 제가 조금 미숙 합니다.

**Comment by groovedk** [comment]
별도의 옵션값으로 지정된 내용은 없으나 헤더 리사이즈 이벤트를 제외하면 가능 할 것으로 보입니다. 
colHeadResizerMouseDown 
axgrid.js 에서 위 함수를 호출하는 부분을 찾아서 주석처리하고 오버시 커서 스타일을 변경해주시면 될것 같습니다.

**Comment by freecatz** [comment]
@groovedk 감사합니다. 알려 주신대로 실행 해보겠습니다. 깃헙이 처음이라 이렇게 쓰는게 맞는지 모르겠습니다.

**Comment by groovedk** [comment]
@freecatz 해당 이슈가 끝나신거면 아래 버튼으로 클로즈해주세요~

**Comment by freecatz** [comment]
@groovedk 아!! 알겠습니다. 이슈 종료 시키도록 하겠습니다. ^^
