### ISSUE TITLE
AXTab의 스크롤문제입니다

### ISSUE THREAD

**Issue by gadenia** [axisj/axisj#720]
안녕하세요. Axisj를 열심히 활용중인 개발자입니다.
AXTab을 사용하는데 문제가 있어 문의드립니다.
overflow옵션을 scroll로 설정하고 사용할 경우 최초 탭리스트의 너비가 클라이언트 너비를 벗어나면
좌우 스크롤버튼이 잘 생성이 됩니다.
하지만 addTabs를 이용하여 탭을 추가할 경우 탭리스트가 많아져도 스크롤버튼이 생기질 않네요.
현재는 addTabs할 때 더미탭을 같이 추가하고 이후 closeTab으로 더미탭을 삭제하는 식으로
스크롤버튼이 생기도록 유도하고 있습니다.
소스를 보면 addTabs는 initTab을 호출하지 않아 전체적인 조정이 이루어지지 못하는 것 같네요.
개선 부탁드립니다~ ^^;

**Comment by hyunjun19** [comment]
네 버그 리포트 감사합니다.
조만간 패치하도록 하겠습니다.

**Comment by hyunjun19** [comment]
수정되었습니다. 정식 릴리즈에 반영될껍니다.
