### ISSUE TITLE
SCRIPT5007: 정의되지 않음 또는 null 참조인 'left' 속성을 가져올 수 없습니다.

### ISSUE THREAD

**Issue by aaboo** [axisj/axisj#721]
IE(11)에서 아래처럼 body > div#content 에 html을 삽입할 경우, 
개발자도구 디버거에서 걸리는 현상이 있습니다.

```javascript
mask.open();
$.ajax({
	url: "그리드가 구현되어 있는 html 파일 경로 "
	, type : "post"
	, success:function(result){	
		$("#content").html(result);
		mask.close();
	}
});
```

>SCRIPT5007: 정의되지 않음 또는 null 참조인 'left' 속성을 가져올 수 없습니다.
>파일: AXJ.min.js, 줄: 11, 열: 8739

![default](https://cloud.githubusercontent.com/assets/3850967/10072491/0b92f958-62fd-11e5-90d3-7ccde14ca3e2.PNG)

![default](https://cloud.githubusercontent.com/assets/3850967/10072427/8c1085d8-62fc-11e5-9df3-a6c5ab243886.PNG)

grid 관련된 버그인것 같은데... 영 거슬리네요. 해결방법이 없을까요?

**Comment by hyunjun19** [comment]
일단 AJAX를 사용해서 HTML을 끌어다가 붙이는 방식으로 그리드를 사용하시면 예상치 못한 문제가 발생할 수도 있습니다.
그리고 저희가 소스를 볼 수 없기 때문에 원인을 파악하기도 불가능합니다.
이미 작성된 HTML을 사용해야 하신다면 `iframe`을 사용하시실 권합니다.
