### ISSUE TITLE
AXGrid에서 그리드 전체 Total Count 표시관련 문의

### ISSUE THREAD

**Issue by raeganja** [axisj/axisj#724]
안녕하세요?
문의사항이 있어서 문의드립니다.

AXGrid에서 그리드 전체 Total Count 표시관련해서 문의 드립니다.

Page 처리시 row 카운드와 별개로 조회된 전체 Count를 그리고 하단에 표시하고 싶습니다.

가능한지요?

**Comment by lhslive** [comment]
axdom("#" + myGrid.config.targetID + "_AX_gridStatus").html() 에 원하시는 포맷으로 출력하세요.

grid의 page 속성은 아래와 같습니다.
pageNo
pageSize
pageCount
listCount
