### ISSUE TITLE
AXInput.bindDate() 관련 문제제기

### ISSUE THREAD

**Issue by gadenia** [axisj/axisj#726]
안녕하세요. 
bindDate()관련해서 문제가 파악되어 글 남깁니다.
특정 엘리먼트에 bindDate할 경우 고정형 엘리먼트는 정상적으로 달력아이콘이 attach됩니다만
div를 이용한 모달(이를테면 jQueryUI.dialog()) 등에 끼워 넣은 html의 엘리먼트는 position관련 속성값이 정상적(?)이지 않아 달력아이콘이 제 위치에 생기질 않네요.
bindDate가 달력아이콘 위치를 결정하는 시점과 .AXanchor의 position:absolute가 맞물려 발생하고 있는데 이를 해결하기 위해 .AXanchor를 오버라이드하여 수정할 경우 달력은 정상적으로 보여집니다만 나머지 컴포넌트가 영향을 받습니다. (그리드의 페이지 이동 selector라던가 AXInput의 segment 등)
이 부분은 원본 레벨에서 수정이 되어야 할 것 같아서 건의드립니다.
(현재는 .ui-dialog .AXanchor {} 를 오버라이드하여 일단 해결해서 쓰고 있습니다)
개선좀 부탁드리겠습니다. ^^

**Comment by lhslive** [comment]
모달을 open 하신 다음에 binddate를 하시면 됩니다.
jQueryUI나 bootstrap등 이상없이 적용 완료했던 기억이 나네요..

**Comment by gadenia** [comment]
빠른답변 감사합니다. 테스트해보겠습니다. ^^
