### ISSUE TITLE
jquery 1.8 에서  Grid 사용시 에러 Uncaught TypeError 가 발생되는 문제에 대해서 문의드립니다.

### ISSUE THREAD

**Issue by hillfolk** [axisj/axisj#728]
jquery 1.8 에서  초기 예제 에서도 아래와 같은 에러가 발생하는 문제에 대해서 질문 드리고 싶은데요
저의 소견으로는 Jquery 버전의 문제일듯 합니다.  Axisj 는 jQuery 1.8 버전이 지원되는 것으로 문서를 봤는데 지원이 안되는 건지 버그인지 문의 드립니다. 

Uncaught TypeError: this.cachedDom.tbody.find(...).outerHeight(...).number is not a functionClass.create.printList @ AXGrid.js:4076Class.create.setList @ AXGrid.js:3279(anonymous function) @ wit-grid.js:11(anonymous function) @ wit-grid.js:15
wit-charisma.js:23 Initializing document

<pre>
var itemTrHeight = this.cachedDom.tbody.find("#" + cfg.targetID + "_AX_null_AX_0").outerHeight().number();

</pre>

**Comment by lhslive** [comment]
그리드 기본 페이지에서 무조건 에러가 난다는 말씀이신가요?..
샘플 코드 그대로 사용하시는게 아니라면 전체 페이지 소스를 부탁 드립니다.

샘플 페이지에 1.8x 버전을 전부 변경해 가며 돌려 봤지만 말씀하신 에러 메세지는 보지 못했습니다.
jquery-1.8b1
jquery-1.8b2
jquery-1.8rc1
jquery-1.8.0
jquery-1.8.1
jquery-1.8.2
jquery-1.8.3

**Comment by hillfolk** [comment]
제가 실수를 했네요 . 다른부분과 충돌한거 같습니다. 좀더 확인했어야 하는데 죄송합니다. 케이스 닫겠습니다.
