### ISSUE TITLE
grid에서 colHeader의 untitle 현상

### ISSUE THREAD

**Issue by cyi0630** [axisj/axisj#729]
![1](https://cloud.githubusercontent.com/assets/15047126/10390278/8b758d8c-6eb2-11e5-89e9-0eac70d34cf0.png)

컬럼이름이 untitle이라고 나타납니다.
어떻게 해야 rabel에 정의된대로 나타낼수 있는지...

소스는

colGroup : [
						{key:"가1", label:"가1", width:"50", align:"center", formatter: "radio", sort:false},
		                {key:"나1", label:"나1", width:"100",align:"center", sort : "desc"},
		                {key:"다1", label:"다1", width:"50",align:"center"},
		                {key:"라1", label:"라1", width:"50", align:"center"},
		                {key:"마1", label:"마1", width:"50", align:"center"},
		                {key:"바1", label:"바1", width:"50", align:"center"},
		                {key:"사1", label:"사1", width:"50", align:"center"},
		                {key:"아1", label:"아1", width:"50", align:"center"},
		                {key:"차1", label:"차1", width:"50", align:"center"},
		                {key:"카1", label:"카1", width:"50", align:"center"},
		                {key:"타1", label:"타1", width:"50", align:"center"},
		                {key:"파1", label:"파1", width:"50", align:"center"},
		                {key:"하1", label:"하1", width:"100", align:"center"},
		                {key:"가2", label:"가2", width:"100", align:"center"},
		                {key:"나2", label:"나2", width:"100", align:"center"},
		                {key:"다2", label:"다2", width:"100", align:"center"},
		                {key:"라2", label:"라2", width:"100", align:"center"},
		                {key:"마2", label:"마2", width:"100", align:"center"},
		                {key:"바2", label:"바2", width:"100", align:"center"},
		                {key:"사2", label:"사2", width:"100", align:"center"},
		                {key:"아2", label:"아2", width:"50", align:"center"},
		                {key:"차2", label:"차2", width:"100", align:"center"},
		                {key:"카2", label:"카2", width:"100", align:"center"},
		                {key:"타2", label:"타2", width:"100", align:"center"},
		                {key:"파2", label:"파2", width:"100", align:"center"},
		                {key:"하2", label:"하2", width:"100", align:"center"},
		                {key:"가3", label:"가3", width:"100", align:"center"},
		                {key:"나3", label:"나3", width:"100", align:"center"},
		                {key:"다3", label:"다3", width:"100", align:"center"},
		                {key:"라3", label:"라3", width:"100", align:"center"},
		                {key:"마3", label:"마3", width:"*", align:"center"}
		            ],
		            colHead : {
	            	    rows: [
	            	        [
	            	            {colSeq:0, rowspan:4},
	            	            {colSeq:1, rowspan:4, align:"center"},
	            	            {colSeq:null, colspan:10, rowspan:2, rabel:"가가가가", align:"center"}, 
	            	            {colSeq:null, colspan:19, rabel:"나나나나", align:"center"}
	            	        ],
	            	        [
	            	            {colSeq:null, colspan:8, rabel:"다다", align:"center"},
	            	            {colSeq:null, colspan:7, rabel:"라라", align:"center"},
	            	            {key:"가1", rowspan:3, align:"center"},
	            	            {key:"나1", rowspan:3, align:"center"},
	            	            {key:"다1", rowspan:3, align:"center"},
	            	            {key:"라1", rowspan:3, align:"center"}
	            	        ],
	            	        [
	            	            {key:"마1", rowspan:2, align:"center"},
	            	            {colSeq:null, colspan:3, label:"가가가가", align:"center"},
	            	            {colSeq:null, colspan:3, label:"가가가가", align:"center"},
	            	            {colSeq:null, colspan:2, label:"가가가가", align:"center"},
	            	            {key:"바1", rowspan:2, align:"center"},
	            	            {key:"사1", rowspan:2, align:"center"},
	            	            {colSeq:null, colspan:3, rable:"가가가각", align:"center"},
	            	            {colSeq:null, colspan:2, rable:"가가가각", align:"center"},
	            	            {key:"아1", rowspan:2, align:"center"},
	            	            {key:"차1", rowspan:2, align:"center"},
	            	            {key:"카1", rowspan:2, align:"center"},
	            	            {key:"타1", rowspan:2, align:"center"},
	            	            {colSeq:null, colspan:3, rable:"가가가각", align:"center"},
	            	            {key:"파1", rowspan:2, align:"center"},
	            	            {key:"하1", rowspan:2, align:"center"}
	            	        ],
	            	        [
								{key:"가2", lign:"center"},
								{key:"나2", lign:"center"},
								{key:"다2", align:"center"},
								{key:"라2", align:"center"},
								{key:"마2", align:"center"},
								{key:"바2", align:"center"},
								{key:"사2", align:"center"},
								{key:"아2", align:"center"},
								{key:"차2", align:"center"},
								{key:"카2", align:"center"},
								{key:"타2", align:"center"},
								{key:"파2", align:"center"},
								{key:"하2", align:"center"},
								{key:"가3", align:"center"},
								{key:"나3", align:"center"},
								{key:"다3", align:"center"}
	            	        ]         
	            	    ],            
	            	    onclick: function(){
// 						    toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, colHead:this.colHead, page:this.page}));
						    console.log(Object.toJSON({index:this.index, r:this.r, c:this.c, colHead:this.colHead, page:this.page}));
						}

		            },

**Comment by lhslive** [comment]
..?...label도 있고 rabel도 있네요..
커피 한잔 하시고 다시 해보세요.

**Comment by cyi0630** [comment]
아 정말 감사합니다. 이걸 못찾고 헤맸네요. ^^;;
