### ISSUE TITLE
안녕하세요 그리드 index 문제로 질문드립니다.

### ISSUE THREAD

**Issue by seo-jung** [axisj/axisj#730]
grid: {    	
            bind: function(){ 
                axGrid.setConfig({
                    targetID : "page-grid-box",
                    height:"470",
                    colHeadAlign: "center",                      
                    colGroup : [                            
                                        {key:"goodsCd",    label:"상품코드",       width:"100"},
                                        {key:"goodsNm",    label:"상품명",         width:"200"},
                                        {key:"stndrd",   label:"규격",       width:"80"},
                                        {key:"purchsQy",       label:"수량",       width:"80", align:"right", editor: {
                                        	type: "number"
                                        }},       
                                        {key:"purchsUntpc",       label:"단가",       width:"120", align:"right", editor: {
                                        	type: "number",
                                            updateWith: ["splpcAmt" , "vat"]
                                        }},
                                        {key:"splpcAmt",       label:"공급가액",       width:"120",align:"right", formatter: function(){
                                            return Number(this.item.purchsQy * this.item.purchsUntpc).money();
                                        }},
                                        {key:"vat",       label:"부가세",       width:"120",align:"right" ,  formatter: function(){
                                            return Number(this.item.purchsQy * this.item.purchsUntpc * 0.1).money();
                                        }},
                                        {key:"rmk",       label:"비고", width:"600",editor: {
                                            type: "text",
                                            updateWith: ["_CUD"]
                                        }},
                                        {key:"_CUD", label:"상태", width:"50", align:"center"}
                             ],
                    body : {
                        ondblclick: function(){
                            fnObj.modal.goodsOpen();
                        },
                    },
                    page:{
                        paging:false,                    
                    },
                 
                });            
            }, 
            setItem: function(item){
                item = $.parseJSON(item);
                axGrid.updateItem(0, 0, 1, item.goodsCd);
                axGrid.updateItem(0, 1, 1, item.goodsNm);
                axGrid.updateItem(0, 2, 1, item.stndrdCd);
            }
        },

팝업창에서 부모창에 있는 setItem 함수를 불러서 선택되있는 현재 row에 값을 넣고 싶은데요
this.index는 body 안에 있어야 되는거 같더라고요.
혹시 현재 선택되있는 row 인텍스를 가져올순 없을까요?

**Comment by aaboo** [comment]
axGrid.setConfig body에다가 아래와 같이 넣으면
더블클릭한 row의 this를 출력하게 되는데, 그 안에 여러가지 값들을 콘솔로 확인할 수 있어요
```javascript
body:{
	ondblclick : function(){
		console.log(this); //요렇게
		//여기서, index, item 안에서 goodsCd나 goodsNm등 정보들도 찾을 수 있을 겁니다.
		console.log(this.index);
		console.log(this.item.goodsCd);
	}
}
```

**Comment by seo-jung** [comment]
음 제질문은 그게 아니라.. 
저건 알고있는데..ㅠ 
body 안이 아니라 다른곳에서 현재 row의 index를 가져올수 있나 하는거였어요~

**Comment by aaboo** [comment]
음 제질문은 그게 아니라.. 
저건 알고있는데..ㅠ 
body 안이 아니라 다른곳에서 현재 row의 index를 가져올수 있나 하는거였어요~

라고 메일 보내주신 것을 늦게 보았네요...

```javascript
var fnObj = {
   grid : {
      target : new AXGrid(),
      bind : function(){

      }
   }
}
```
와 같이 정의 되어 있다면
```javascript
console.log(fnObj.grid.target.getSelectedItem()); 
```
참조 : http://jdoc.axisj.com/AXGrid.html#getSelectedItem
