### ISSUE TITLE
안녕하세요 그리드 row 삭제 문제로 글 남겨요~

### ISSUE THREAD

**Issue by seo-jung** [axisj/axisj#732]
remove: function(){
        	var item = axGrid.getSelectedItem();
        	alert(item.index);
        }

이렇게 index는 들고 오는데 index로 그리드 row를 삭제할순 없을까요?

아무데이터 없는 row를 삭제해야 하는 로직이 있어서요.

**Comment by lhslive** [comment]
http://jdoc.axisj.com/AXGrid.html#removeList
http://jdoc.axisj.com/AXGrid.html#removeListIndex

**Comment by seo-jung** [comment]
크어 감사합니다. 제가 꼼꼼히 못봤군요..ㅠ
