### ISSUE TITLE
그리드의 컬럼 숨김 문의입니다~

### ISSUE THREAD

**Issue by seo-jung** [axisj/axisj#737]
안녕하세요~ 수고가 많으십니다.

 axGrid.setConfig({
                    targetID : "page-grid-box",
                    height:"470",
                    colHeadAlign: "center",  
                    colGroup : [                            
                                        {key:"goodsCd",    label:"상품코드",       width:"100" , editor: {
                                            notEmpty: true, 
                                            disabled : function(){
                                             return (this.item.list.length > 0);
                                            }
                                        }},
                                        {key:"goodsNm",    label:"상품명",         width:"200", },
                                        {key:"stndrdCd",   label:"규격",   align:"center",    width:"80" , },
                                        {key:"purchsQy",       label:"수량",       width:"80", align:"right",formatter:"money", editor: {
                                        	type: "number",
                                        	updateWith: ["_CUD"],
                                        	maxLength: 7,
                                        	beforeUpdate: function(val){ // 수정이 처리된 후
                                        		  return (val).round(2);
                                            },
                                       		afterUpdate: function(val){ // 수정이 처리된 후
                                       			var item = axGrid.getSelectedItem();
                                                axGrid.updateItem(0, 5, item.index, Number(this.item.purchsQy * this.item.purchsUntpc).round(2));
                                                axGrid.updateItem(0, 6, item.index, Number(this.item.purchsQy * this.item.purchsUntpc * 0.1).round(2));
                                            },
                                        }},       
                                        {key:"purchsUntpc",       label:"단가",       width:"120", align:"right",formatter:"money", editor: {
                                        	type: "number",
                                        	updateWith: ["_CUD"],
                                            maxLength: 17,
                                            beforeUpdate: function(val){ // 수정이 처리된 후
                                            	return (val).round(2);
                                            },
                                            afterUpdate: function(val){ // 수정이 처리된 후
                                            	var item = axGrid.getSelectedItem();
                                                axGrid.updateItem(0, 5, item.index, Number(this.item.purchsQy * this.item.purchsUntpc).round(2));
                                                axGrid.updateItem(0, 6, item.index, Number(this.item.purchsQy * this.item.purchsUntpc * 0.1).round(2));
                                           }
                                        }},
                                        {key:"splpcAmt",       label:"공급가액",       width:"120",align:"right", formatter: "money"}, 
                                        {key:"vat",       label:"부가세",       width:"120",align:"right" ,   formatter: "money"},
                                        {key:"rmk",       label:"비고", width:"600",editor: {
                                            type: "text",
                                            updateWith: ["_CUD"]
                                        }},
                                        {key:"_CUD", label:"상태", width:"50", align:"center" , colHeadTool : false},
                                        {key:"seq", label:"순번", width:"50", align:"center" , colHeadTool : false},  
                                        {key:"bQy", label:"수정전값", width:"100", align:"center" , colHeadTool : false}  
                             ],

상태,순번,수정전값을 그리드에서 안보이게 하고싶은데  colHeadTool : false 이게 안먹히던데 쓰는방법이 틀린건가요?

**Comment by lhslive** [comment]
```
{key:"_CUD", label:"상태", width:"50", align:"center" , display: false},
 {key:"seq", label:"순번", width:"50", align:"center" , display: false},

 {key:"bQy", label:"수정전값", width:"100", align:"center" , display: false}
```
이렇게 해 보세요.

**Comment by seo-jung** [comment]
흐어 감사합니다~ 잘되네요

**Comment by hyunmoo** [comment]
그리드의 컬럼 숨김 문의

감사합니다. 덕분에 해당기능을 사용하게되었습니다.
