### ISSUE TITLE
그리드에서 오른쪽 하단에 카운드 설정?

### ISSUE THREAD

**Issue by cyi0630** [axisj/axisj#745]
1. 그리드에 데이터를 set할때
myGrid.setList({Array}); <-- 이렇게 setList를 하는데({Array}는 ajax로 따로 가져옵니다.)
이렇게 하면 오른쪽 하단에 카운트는 항상 0이여서 이걸 Array 길이만큼 카운트 되게 하고 싶은데
어떻게 해야 될지 모르겠습니다.

비동기방식으로 setList하면 잘 되긴하지만 위에처럼 직접 데이터를 setList해야 되서요.

2. myGrid.setList({Array}) <-- 이렇게 selList를 하게 되면 가로 스크롤이 생성되지 않습니다.(일단 데이터가 없긴 한데... 다시 검색눌렀을때(검색 누르면 다시 setConfig 하고 myGrid.setList({Array}) 를 하게 됨) 는 가로 스크롤이 생성됩니다.  버그인가요? 아니면 제가 뭘 잘못설정해서 인가요?

**Comment by lhslive** [comment]
setList 하실때 
onLoad 옵션을 주셔서 해당 함수에서 
myGrid.setStatus(myGrid.List.length) 
해보세요.

**Comment by cyi0630** [comment]
myGrid.setList(({Array}, onLoad:function(){
myGrid.setStatus(myGrid.List.length) 
}); 
이런식으로 하는 건가요?

**Comment by lhslive** [comment]
Array를 따로 주실거면

myGrid.setList(Array);
이후에 
myGrid.setStatus(myGrid.List.length) ; 
이렇게 호출해 보세요.



onLoads는 ajax관련 옵션입니다.

**Comment by cyi0630** [comment]
myGrid.setStatus(myGrid.List.length) ;  썼는데 계속 안돼서 
최신버전의 AXgrid.js  다운받아서 사용하니까 잘 되네요 ^^;;
감사합니다.
