### ISSUE TITLE
fixedColSeq 설정시 픽스된 영역에 콤보박스가 작동하지 않는군요.

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#746]
fixedColSeq.html 일부 수정해서 테스트 했습니다. 

    var fnObj = {
        pageStart: function(){

            myGrid.setConfig({
                targetID : "AXGridTarget",
                theme : "AXGrid",
                fixedColSeq:3,
                colGroup : [
                    {key:"no", label:"번호", width:"50", align:"right"},
                    {key:"title", label:"제목", width:"150"},
                    {
                        key:"writer", label:"combobox", width:"100",
                        editor: {
                            type: "select",
                            optionValue: "CD",
                            optionText: "NM",
                            options:[
                                {CD:1, NM:"김기영"},
                                {CD:2, NM:"장기영"},
                                {CD:3, NM:"장서우"}
                            ],
                            beforeUpdate: function(val){ // 수정이 되기전 value를 처리 할 수 있음.
                                // 선택된 값은
                                console.log(val);
                                return val;
                            },
                            afterUpdate: function(val){ // 수정이 처리된 후
                                // 수정이 된 후 액션.
                                console.log(this);
                            }
                        }
                    },
                    {key:"regDate", label:"작성일", width:"100", align:"center"},
                    {key:"price", label:"가격", width:"100", align:"right", formatter:"money"},
                    {key:"amount", label:"수량", width:"80", align:"right", formatter:"money"},
                    {key:"cost", label:"금액", width:"100", align:"right", formatter:function(){
                        return (this.item.price.number() * this.item.amount.number()).money();
                    }},
                    {key:"desc", label:"비고", width:"500"}
                ],
                
                colHead : {
                    rows: [
                        [
                            {colSeq:0, rowspan:2},
                            {colSeq:null, colspan:3, label:"표현식", align:"center"},
                            {colSeq:4, rowspan:2},
                            {colSeq:5, rowspan:2},
                            {colSeq:6, rowspan:2},
                            {colSeq:7, rowspan:2}
                        ],
                        [
                            {colSeq:1},
                            {colSeq:2},
                            {colSeq:3}
                        ]
                    ]
                },
                
                body : {
                    marker: function(){
                        
                    },
                    onclick: function(){
                        toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item}));
                        //alert(this.list);
                        //alert(this.page);
                    },
                    ondblclick: function(){
                        //toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item}));
                        //alert(this.list);
                        //alert(this.page);
                    }
                },
                page:{
                    paging:false
                }
            });
            
            var list = [
                {no:1, title:"AXGrid 첫번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:10}, // item
                {no:2, title:"AXGrid 두번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12300, amount:7},
                {no:3, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12000, amount:5},
                {no:4, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:13000, amount:4},
                {no:5, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:3000, amount:3},
                {no:6, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:2},
                {no:7, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:129500, amount:1},
                {no:8, title:"AXGrid 첫번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:10},
                {no:9, title:"AXGrid 두번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12300, amount:7},
                {no:10, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12000, amount:5},
                {no:11, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:13000, amount:4},
                {no:12, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:3000, amount:3},
                {no:13, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:2},
                {no:14, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:129500, amount:1},
                {no:15, title:"AXGrid 두번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12300, amount:7},
                {no:16, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:12000, amount:5},
                {no:17, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:13000, amount:4},
                {no:18, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:3000, amount:3},
                {no:19, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:123000, amount:2},
                {no:20, title:"AXGrid 세번째 줄 입니다.", writer:"장기영", regDate:"2013-01-18", desc:"myGrid.setList 의 첫번째 사용법 list json 직접 지정 법", price:129500, amount:1}
            ];
            myGrid.setList(list);
        }
    };

**Comment by thomasJang** [comment]
해결되었습니다. dev브랜치에 커밋되었습니다.
