### ISSUE TITLE
안녕하세요 그리드 모양때문에 문의드립니다.

### ISSUE THREAD

**Issue by seo-jung** [axisj/axisj#747]
axGrid.setConfig({
                    targetID : "page-grid-box",
                    height:"300",
                    colHeadAlign: "center",                
                    colGroup : [
                                {key:"brcd",      label:"바코드",       width:"270",},
                                {key:"strCd",      label:"매장코드",     width:"10",display:false},
                                {key:"purchsDe",      label:"구매일자",       width:"10",display:false},
                                {key:"seq",      label:"순번",       width:"10",display:false},
                                {key:"wrhousCd",      label:"창고코드",       width:"10",display:false},
                                {key:"goodsCd",      label:"상품코드",       width:"10", display:false}
                    ],
![default](https://cloud.githubusercontent.com/assets/15008667/10810497/f20ac1d8-7e44-11e5-9a18-13b1a9aa24e0.PNG)

보시면 그리드의 저기 끝쪽여백을 없애고 싶은데요 ㅠ 항상 남더라고요 사이즈를 맞춰도..
도움좀 부탁드립니다.

**Comment by thomasJang** [comment]
저 영역은 세로스크롤바를 위한 자리인데요. 조만간 스크롤바가 조금 바뀔 예정입니다.
