### ISSUE TITLE
행을 여러행으로 표시할때 질문입니다.

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#750]
데이터는 1줄이고 3열로 분리했습니다. 첫번재 줄은 편집이 되는데 2번째 줄은 편집이 안되는군요?
원래 이런거 맞나요?

![default](https://cloud.githubusercontent.com/assets/12386521/10902797/a0c1c2a4-8245-11e5-98e0-4c4cd4da884f.png)

    var getColGroup = function(){
      var buf = [];
      buf.push({key:"sapSupyBiznm", label:"협력사", width:"100", align:"center"});
      buf.push({key:"sapItemCd", label:"P/N", width:"100", align:"center"});
      buf.push({key:"sapStd", label:"사양", width:"100", align:"center"});
      buf.push({key:"puhInchgnm", label:"구매담당자", width:"100", align:"center"});
      buf.push({key:"date", label:"Date", width:"100", align:"center"});
      
      for (var i=1;i<=clday ;i++){
        var day = i.toString().LPad(2,'0');
        var dw = (cyear+"-"+cmon+"-"+day).date().print("dw");
        buf.push({key:"scctCnt"+day, label:i+"<br>"+dw, width:"50", align:"right",editor: {type: "number",updateWith: ["_CUD"],disabled:function(){return fn_disabled(this.item)}}});
      }
      buf.push({key:"subTotal", label:"소계", width:"80", align:"center"});
      return buf;
    };

    var getBody = function(){
      var buf1 = [];
      var buf2 = [];
      var buf3 = [];
      buf1.push({key:"sapSupyBiznm", rowspan:3, align:"center"});
      buf1.push({key:"sapItemCd", rowspan:3, align:"center"});
      buf1.push({key:"sapStd", rowspan:3, align:"center"});
      buf1.push({key:"puhInchgnm", rowspan:3, align:"center"});
      buf1.push({key:"t1", align:"center"});
      buf2.push({key:"t2", align:"center"});
      buf3.push({key:"t3", align:"center"});

      for (var i=1;i<=clday ;i++){
        var day = i.toString().LPad(2,'0');
        var dw = (cyear+"-"+cmon+"-"+day).date().print("dw");
        buf1.push({key:"scctCnt"+day, align:"right",editor: {type: "number",updateWith: ["_CUD"],disabled:function(){return fn_disabled(this.item)}}});
        buf2.push({key:"scctCnt"+day, align:"right",editor: {type: "number",updateWith: ["_CUD"],disabled:function(){return fn_disabled(this.item)}}});
        buf3.push({key:"scctCnt"+day, align:"right",editor: {type: "number",updateWith: ["_CUD"],disabled:function(){return fn_disabled(this.item)}}});
      }
      buf1.push({key:"totalScctCnt", align:"center"});
      buf2.push({key:"", align:"center"});
      buf3.push({key:"", align:"center"});

      return {
                rows: [
                  buf1,
                  buf2,
                  buf3
                ],
                marker: {},
                onclick: function(){
                }
      }
    };

    tpmsGrid.setConfig({
      targetID : "AXGridTarget",
      theme : "AXGrid",
      colHeadAlign: "center", 
      height:$("#AXPage").height()-200,
      //fitToWidth  : false,
      //mergeCells: true,
      //mergeCells: [1,2,3,4],
      //fixedColSeq:2,
      //passiveMode:true,
      //passiveRemoveHide:false,
      colGroup : getColGroup(),
      colHead : {
        heights : [50]
      },
      body : getBody(),

**Comment by thomasJang** [comment]
현재 inline edit기능은 body 에 rows가 추가된 경우를 지원하지 않습니다.
