### ISSUE TITLE
AXGrid inline-edit 사용시 정렬이 되지 않아 질문드립니다.

### ISSUE THREAD

**Issue by bewoo** [axisj/axisj#756]
아래와 같이 그리드 컬럼에 대하여 옵션을 부여 한 후 
```javascript
{key:"incoming_due_qty", label:"수량", width:"60", align:"right", formatter:"money",
    editor: {type: "number"}
},
```

그리드 정렬 기능을 이용하는데 아래 첨부이미지와 같이 정상적인 정렬이 되지 않습니다. 
inline-edit의 샘플 코드를 보면 정렬 옵션이 false로 되어 있는데 지원을 하지 않는 부분인지 아니면
혹시 제가 실수한 부분이 있는지 궁금합니다.
![image](https://cloud.githubusercontent.com/assets/8958516/11026451/76097fd2-86ed-11e5-8b76-2ab0b33600fd.png)

**Comment by panic910** [comment]
소스를 보지 못하는 관계로 정확하지는 않지만
sort=true; 로 변경하시면 되는걸로 알고 있습니다.
또한 위 컬럼에 sort:"asc" 추가 하시구요

**Comment by bewoo** [comment]
답변 감사드립니다. 그리드 옵션에 sort옵션과 컬럼 옵션에 sort 옵션 둘다 부여해보았으나
본글의 이미지와 같이 숫자정렬이 아닌 문자정렬이 되고 있습니다. 해당 부분에 대한 옵션이
있는지 궁금합니다.

**Comment by hyunjun19** [comment]
JSON에서 해당 값이 숫자인지 문자인지 확인해 보세요.

**Comment by bewoo** [comment]
답변 감사드립니다.
