### ISSUE TITLE
CDN 서비스 종료 안내

### ISSUE THREAD

**Issue by thomasJang** [axisj/axisj#768]
그동안 액시스제이 코드에 대해 CDN을 제공하고 있었습니다.
금액이 대단하지는 않지만 매달 100여달러 정도 돈을 내고 있는데요.
특정 몇개의 사이트에서만 트래픽 80%를 차지 하고 있어 부득이 하게 
CDN서비스를 정리하고자 합니다.

이글을 보시는 분은 혹시 코드에 cdn주소를 넣어두셨다면 제거 하시고 소스를 직접받아 경로를 변경하시기 바랍니다.
안정적으로 서비스 하지 못해 죄송합니다.

이달까지만 CDN주소가 살아있고 다음달 부터는 사용하실 수 없게 됩니다.

**Comment by hyunjun19** [comment]
오픈소스 CDN이 있는것 같은데 대안으로http://hacks.mozilla.or.kr/2014/03/jsdelivr-the-advanced-open-source-public-cdn/ 사용해보면 어떨까요.

**Comment by thomasJang** [comment]
네~ 다시 추진해봐야 하겠습니다.
