### ISSUE TITLE
그리드 엑셀 변환시 머지 기능

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#769]
getExcelFormat('html')

으로 html 로 변환했는데 헤더등은 머지가 잘되는데

mergeCells 옵션으로 머지된 row에 내용은 머지가 안되는거 같습니다.
```js
Grid.setConfig({
      targetID : "AXGridTarget",
      theme : "AXGrid",
      colHeadAlign: "center", 
      height:$("#AXPage").height()-120,
      //fitToWidth  : false,
      //mergeCells: true,
      mergeCells: [1,2,3],
      //fixedColSeq:1,
      colGroup : getColGroup(),
      colHead : getColHead(),
      body : getBody(),
      page:{ paging:false }
    });
```

**Comment by hyunjun19** [comment]
예제는 정상적으로 작동하고 있습니다.
http://dev.axisj.com/samples/AXGrid/mergeCells.html

데이터를 보여주세요.

**Comment by cococl** [comment]
화면은 잘되구요 화면을 엑셀로 저장할때 머지가 안되는거 같습니다.

왼쪽이 엑셀 오늘 쪽이 화면입니다.

![default](https://cloud.githubusercontent.com/assets/12386521/11644355/9f0258b6-9d8e-11e5-8d66-3982738402ba.png)

**Comment by hyunjun19** [comment]
아... 아직 해당 기능에 머지 부분이 반영이 안된거 같습니다.
반영을 해야 하는데 요즘 바쁜 시즌이라 기능 업데이트가 늦어질 수도 있습니다. ^^;;

**Comment by thomasJang** [comment]
https://github.com/axisj/axisj/commit/e065b52604d51dba72ced32cd8fc10da6d72ac95

에서 수정하였습니다.
