### ISSUE TITLE
검색시 문의사항

### ISSUE THREAD

**Issue by showaging** [axisj/axisj#770]
안녕하세요

문의사항이 있어 질문드립니다.

![asdfzxxcv](https://cloud.githubusercontent.com/assets/12963877/11617335/96a585d0-9cd0-11e5-8849-3112fbb9b300.png)

위에 첨부사진처럼 검색 조건에 달력필드가 있으면 enter키로 검색이 안되는데 이유가 먼지 모르겠습니다

달력필드를 주석처리하면 검색이 됩니다.

**Comment by hyunjun19** [comment]
일단 AXSearch는 스크립트를 이용해서 생성하는 방법과 HTML로 생성하는 방법등 다양하게 사용할 수 있습니다.
코드를 보여주셔야 판단이 가능할 것 같아요
