### ISSUE TITLE
Axicon 서비스 문의

### ISSUE THREAD

**Issue by karfca** [axisj/axisj#772]
AxiJ와 Axicon을 같이 개발중에 있는데요, Axicon에서 Material Icon만 화면에 출력이 안됩니다. 

CDN으로 사용할때는 되길래 Axicon은 CDN으로 사용하고있었는데, CDN이 종료되고 나서
다시 이 문제를 해결하려고 하니 도저히 모르겠네요. 

다른 아이콘들은 잘 나오는데, Material Icon만 안나오는데 혹시 어떤 문제일지 추측 되시는게 있으실까요?

**Comment by zeroty** [comment]
흠 엑시콘관련 fonts와 svg파일들을 다운로드 받아 CDN으로 링크 걸어놓은 것들을 내부링크로 변경해보세요.
