### ISSUE TITLE
AXUpload5 setUploadedList 호출 시 대표이미지 표시

### ISSUE THREAD

**Issue by panic910** [axisj/axisj#782]
AXUpload5를 이용해서 파일 업로드 전에 "대표이미지"를 설정하고 저장후에 해당 업로드 파일들을 불러올 경우 기존에 설정한 대표이미지에 대표이미지 아이콘이 표시 되는게 맞는건지 궁금합니다.

제가 해본 경우로는 setUploadedList()를 호출 하더라도 설정된 대표이미지에 표시가 되지 않는 듯하여
AXUpload5.js 를 조금 건드렸습니다.

```
if(cfg.onClickUploadedItem){
	itembox.find(".AXUploadDownload").bind("click", function(){
		onClickFileTitle(itemID);
	});
}

아래에 (line 2554 아래)

if(f['mainImage']){
	$("#"+f['id']+"_AXUploadLabel_mainImageFile").show();
}
```

위 소스를 추가 하였습니다.

원래 기능이 있는건지 아니면 구현을 해야 하는건지 궁금합니다

**Comment by thomasJang** [comment]
:+1:

**Comment by thomasJang** [comment]
그냥 한번 모임에 나오셔요 ^^;;

**Comment by panic910** [comment]
ㅎㅎ 시간이 허락된다면 꼭 한 번 나가겠습니다 ^^
