### ISSUE TITLE
Grid에서 클릭시 모달로 전달한 parameter 사용방법

### ISSUE THREAD

**Issue by newkie** [axisj/axisj#786]
안녕하세요.

제목대로 Grid에서 클릭시 모달로 전달한 parameter 사용방법을 찾고 있습니다.
```js
body : {
	onclick : function() {
		var params = "sw_no="+this.item.sw_no;
		myModal.open({
			url:"SE_SUB.do",
			pars:params.queryToObject(),
			top:100,
			closeByEscKey:true
		});
		//fnObj.grid.target.checkedColSeq(0, null, this.index); 
		//toast.push(Object.toJSON({index:this.index, item:this.item}));
		//alert(this.list);
		//alert(this.page);
	}
},
```
이렇게 Grid에서 아무 행을 클릭하면 특정 칼럼의 값을 parameter로 넘겨주는 modal을 띄웁니다.

그런데 해당 모달에서도 axisj를 사용한 gridview를 띄우는데

```jsp
<%System.out.println(request.getParameter("sw_no"));%>
```
이렇게 하면 콘솔에 넘겨진 파라미터가 찍히는 것이 확인됩니다만 
```js
ajaxUrl : "&lt;c:url value='/SE_SUB1.json' /&gt;",
ajaxPars : "",
onLoad : function() {
	trace(this);
}
```
저기 ajaxPars에 받아온 parameter를 전달할 수 있는 방법을 찾지 못해 문의드립니다.

태그를 넣고 axdom("#sw_no").html() 도 해보았지만 undefined라고 나오네요.

**Comment by newkie** [comment]
죄송합니다 글이 두개가 올라갔는데 삭제가 안되네요;;

**Comment by hyunjun19** [comment]
아래처럼 해보세요.

```jsp
ajaxUrl : "<c:url value='/SE_SUB1.json' />",
ajaxPars : "sw_no=${params.sw_no}",
onLoad : function() {
    trace(this);
}
```

**Comment by newkie** [comment]
2016-01-07 08:00:20,755 DEBUG [java.sql.PreparedStatement] {pstm-100139} Parameters: [undefined]

undefined로 지정되네요.

**Comment by newkie** [comment]
params 가 아니고 param.sw_no하니까 되네요.ㅎㅎ 감사합니다.
