### ISSUE TITLE
AXEditor with AXUpload5 에서 파일삭제시 파라미터가 안넘어가는데요?

### ISSUE THREAD

**Issue by jeunhaksun** [axisj/axisj#787]
버전 1.0.21 입니다.
실제 upload5.html을 가지고 구현
바꾼건 
uploadUrl, deleteUrl 부분만 실제 경로로 변경
일단 업로드 부분은 이상없이 작동하는것을 확인 하였습니다.
그러나 업로드후에 파일을 삭제 할려고 하니 파라미터값이 예제와는 달리 안넘어가는데요

예제에서는 
id	                MF_AX_0
name    	        AX_1355503482.png
saveName	AX_1355503482.png
type	                file
fileSize      	1944
uploadedPath	/samples/AXUpload5/files/
thumbUrl	        files/AX_1355503482.png
mainImage	true
_id_	                MF_AX_0
userID	        tom
userName	액시스

상단에 값과 같이 삭제시에 파라미터로 값이 넘어가는것을 확인 하였으나
실제해보니 다음과 같이 넘어가기만 하는데 어디가 잘못된것인지 알수가 없어서 하루종일 
고생중입니다. ㅠㅠ
_id_	             AXA002628198_AX_0
files	             [object Object]
userID	     tom
userName    액시스

도움 부탁 드리겠습니다.

**Comment by hyunjun19** [comment]
음... 보통 이런 경우는 여러 요소가 복합적으로 작용하면서 발생하는 버그이기 때문에 뭔가 저희가 볼 수 있는 샘플 URL을 주셔야 확인이 가능합니다.

**Comment by jeunhaksun** [comment]
샘플에있는 upload5.html을 말씀드린건데요
바꾼건 url만 바꾸었구요
웹프록시툴로 보니데이타가 말한거와같습니다
