### ISSUE TITLE
AXUpload 커스텀 입력 질문입니다.

### ISSUE THREAD

**Issue by llois** [axisj/axisj#790]
먼저 번 질문에 자세하고 친절한 답변 정말 감사 드립니다.

다름이 아니라,

AxUpload에 파일업로드 버튼으로 업로드하는것에 더하여

ctrl+v를 이용한 클립보드이미지를 업로드 하는 기능을 구현 하고자 합니다.

클립보드 이미지를 자바스크립트를 통하여 서버단의 코드로 실제 업로드가 되는 부분은 쉽게 구현이 되었습니다. (샘플이 많아서)

그런데 이 업로드 되는 부분을 AXupload의 업로드 화면 부분에 넣어야 하는데,

그 부분을 어떻게 구현해야할 지 조언을 부탁 드립니다.

제가 시도해본 결과는

1. 클립보드업로드 소스에서 Complete 후 실행시킬 수 있는 자바스크립트 메소드 부분에 AXUpload 업로드 트리거를 삽입

2. 그냥 클립보드로 업로드 하고 Axupload에서 업로드된 이미지 목록 새로고침 해서 나타나게.

정도인데 둘 다 잘 안되네요 ㅠㅠ

스스로 개발완료하지못하고 자꾸 여쭤봐서 죄송합니다만 그래도 제품을 더 좋게 함께 만들자는 취지(?) 아닌 변명에 다시 여쭈어 봅니다.

새해 복 많이 받으세요!

클립보드 업로드 샘플 Site : http://llois.pe.kr:8080/File

**Comment by llois** [comment]
찾아보고 있는데, 

AXUpload5.js 파일 내에

//큐박스에 아이템 추가
	if(cfg.queueBoxAppendType == "prepend") quebox.prepend(this.getItemTag(itemID, f));
	else quebox.append(this.getItemTag(itemID, f));
	quebox.find("#"+itemID).fadeIn();
}else{
	cfg.onError("fileCount");
	break;
}

이 부분인 것같은데, 이걸 어떻게 핸들링 해야 하는걸까요 ㅠㅠ

클립보드에 있는 데이터를 ajax로 서버에 업로드 하고 업로드에서 리턴된 파일데이터를 가지고 이 코드를 사용해서 넣으면 될거 같은데, 여기서 막히네요...

부탁 드립니다!

**Comment by llois** [comment]
자답입니다.

```javascript
        myUpload.setUploadedList([{ "id": "AXA230749949_AX_0", "name": "1.jpg", "type": ".jpg", "saveName": "0010E170732380001.jpg", "fileSize": "34828", "uploadedPath": "%2fApp_Data%2fuploads%2fBrand%2f1%2f", "thumbUrl": "%2fApp_Data%2fuploads%2fBrand%2f1%2f%2fthumb%2fT_0010E170732380001.jpg" }]);
...

이런식으로 넣어주면 되네요.
이리 간단한걸... 거진 일주일을 찾았네요.

**Comment by hyunjun19** [comment]
답변이 너무 늦었네요...
완벽하진 않지만 http://jdoc.axisj.com 문서도 참고해 주세요.
