### ISSUE TITLE
업로드 드래그 드롭 에러 관련 버그..

### ISSUE THREAD

**Issue by david80** [axisj/axisj#792]
![1111](https://cloud.githubusercontent.com/assets/11273651/12259480/7a0eb25c-b959-11e5-9b89-6ebd4ed5869e.png)

샘플사이트에서도 동일 에러 발생..

**Comment by llois** [comment]
경험상 이런경우는 거의 대부분 ID값이 안맞으면 저런 에러가 뜨더라구요.
100% 확실한건 아니지만 js소드 내에 #아이디 값이랑 실제 div의 아이디값 확인 해보셔요

**Comment by david80** [comment]
샘플사이트도 작동안해요

**Comment by panic910** [comment]
제 생각에는 버그로 보입니다.
AXUpload 를 load 할 때 보면 기존에 저장된 이미지를 로드 해서
```
myUpload.setUploadedList(res);
```

위 함수를 호출을 합니다.

AxUpload5.js 를 살펴보니

```
2522 line
quebox.empty();
````

부분이 있는데요, setUploadedList 를 호출하면서 quebox 내에 있던 dropbox 도 같이 사라져서 생긴 문제로 보입니다.

위 부분을
```
quebox.remove('.AXUploadItem');
````

우선은 이렇게 수정해서 사용하시면 됩니다.

버그로 보이니 수정해주실 겁니다.

물론 정답이 아닐 수 있습니다 ^^;

**Comment by thomasJang** [comment]
:+1:  @panic910
