### ISSUE TITLE
AXupload id값을 얻는 법을 알고 싶습니다.

### ISSUE THREAD

**Issue by llois** [axisj/axisj#798]
AXuploads[1].setUploadedList([{ "id": "AXA230749949_AX_0", "name": "1.jpg", "type": ".jpg", "saveName": "0010E170732380001.jpg", "fileSize": "34828", "uploadedPath": "%2fApp_Data%2fuploads%2fBrand%2f1%2f", "thumbUrl": "%2fApp_Data%2fuploads%2fBrand%2f1%2f%2fthumb%2fT_0010E170732380001.jpg" }]);

이런식으로 큐박스에 직접 데이터를 넣으려고 합니다.
그런데 id값을 공란으로 두니 데이터가 입력되지않고 아무값이나 임의로 넣어주면 데이터가 입력 되더라구요.

그래서 질문입니다.
(1) ID값을 저 위의 예처럼 AXA로 시작되는 일정한 규칙이 아닌 임의의 랜덥값을 입력해도 상관이 없을까요?

(2) 저 ID값을 OnStart시 trace해보니 업로드 하기전에 id값을 생성해서 받아오는거 같은데 생성하는 부분을 알고 싶습니다.

감사합니다.

**Comment by panic910** [comment]
AXUpload5.js 파일내에 보시면

onFileSelect 함수 내에

```
1859 line 
var itemID = 'AX'+AXUtil.timekey()+'_AX_0';

1875 line 
var itemID = 'AX'+AXUtil.timekey()+'_AX_'+i;

1907 line
var itemID = 'AX'+AXUtil.timekey()+'_AX_'+i;
```

이상 세 부분에서 id가 생성 되는걸로 알고 있습니다.

해당 부분을 수정하시면 원하시는 랜덤값으로 입력 되도록 구현 가능할 것 같습니다.

**Comment by llois** [comment]
정말 감사 드립니다!!!!
