### ISSUE TITLE
Axtree 테이블 여백 질문 입니다.

### ISSUE THREAD

**Issue by llois** [axisj/axisj#802]
안녕하세요?

AXTree에서 질문이 있습니다.

공식 샘플사이트도 그렇고 실제로 제가 적용한 곳도 그런데

![image](https://cloud.githubusercontent.com/assets/10164454/12541248/ae3f5cae-c357-11e5-8fa4-c9c1bfe5d5b0.png)

다음과 같은 여백? 이 생깁니다.

이걸 없앨 수 있는 방법이 있을까요?

감사합니다!!

**Comment by dkswjdals89** [comment]
저 여백이 세로 스크롤이 생겼을 경우, 스크롤바가 나타나는 위치라 여백처리가 되는것으로 보이는데요, 현재로써는 저 여백을 없애는 방법은 fitToWidth 설정을 false 로 설정하시고, 각 칼럼 Width를 Tree의 전체 Width에 맞게 조정하시는 방법밖에 없을것 같습니다. 이럴경우 가로 스크롤이 생기게 됩니다. 가로 스크롤은 xscroll 옵션을 false로 주시면 됩니다.

**Comment by llois** [comment]
안녕하세요? 답변을 늦게 봤네요.

말씀 하신대로 적용하였는데, 브라우저 크기에 따라서 가변을 하려면 % width로 해야할텐데

소스상에 %로는 width가 적용이 안되는것 같습니다 ㅠㅠ

그래서 그냥 여백있는 채로 두어야 될 것 같습니다 ㅠㅠ

답변 감사합니다!
