### ISSUE TITLE
AXGrid 데이터에 따른 colspan 

### ISSUE THREAD

**Issue by KisunHong** [axisj/axisj#804]
데이터에 따라.. colspan을 정하고 싶은데.. 안되는 지요??
사용하다 보면 종종 이런 경우 있는데요..
marker를 사용하려면 그 위의 칼럼을 하나 숨기는 기능이 있어도 좋겠고요..
removeList는 아예 없어져 버려서.. 마커도 안나오네요..

**Comment by hyunjun19** [comment]
불행히도 `colspan`은 숫자만 받을 수 있게 프로그래밍되어 있네요.
