### ISSUE TITLE
axisj 관련한 버그가 아닌 소스상 궁굼한점등은 어디에서 질문하면 좋을까요?

### ISSUE THREAD

**Issue by SinnoriTeam** [axisj/axisj#809]
안녕하세요.

axisj 관련한 버그가 아닌 소스상 궁굼한점등은 어디에서 질문하면 좋을까요?

액시스제이에서 모바일용 메뉴를 만들고자 합니다.
아래 소스를 보면 menu 라는 객체(?)를 만드는데,
menu:[{menuID:"1", label:"menu 1", ac:"Dashboard", url:"http://www.axisj.com"},
에서 ac 라는것이 있는데 이것이 무엇인지 궁굼해서 질문하고 싶은데요.
이런 질문은 어디에서 하면 좋을까요?

**Comment by lhslive** [comment]
http://jdoc.axisj.com/AXMobileMenu.html#setConfig

ac : 메뉴 아이템에 추가하고 싶은 클래스 네임 addClass의 약자 이군요.

**Comment by SinnoriTeam** [comment]
// lhslive 
lhslive 님 답변 감사합니다. 하지만 ac(=addClass) 그 쓰임 용도를 알고자 하는겁니다.
label 은 메뉴에서 메뉴명이고 url 는 메뉴 클릭시 이동할 url 주소 를 뜻하는데
ac(=addClass) 는 모하는건지 잘모르겠네요.
언뜻 키보드 결합과 관련된것 같은데 정말로 모하는걸까요?

**Comment by lhslive** [comment]
css class와 연결됩니다.
소스를 열어보시거나 예제 파일을 수정해 보시면 되겠지요?
예제 파일에

```
	<style>
	.Dashboard{
		color:red !important;
	}
	</style>
```

이 구문을 추가해 보시면 이해 되실 겁니다.

**Comment by SinnoriTeam** [comment]
// lhslive 
답변 감사합니다. 그런 의미 였군요. ^^
