### ISSUE TITLE
그리드가 안나와요 (익스플로러 10)

### ISSUE THREAD

**Issue by yongjun0213** [axisj/axisj#813]
SCRIPT1006: ')'가 필요합니다. 
AXJ.min.js, 줄 7 문자 3571
SCRIPT5009: 'Class'이(가) 정의되지 않았습니다. 
AXGrid.js, 줄 97 문자 1
SCRIPT5009: 'Class'이(가) 정의되지 않았습니다. 
AXGrid.js, 줄 97 문자 1

이런 에러가 발생하는데요 왜그런걸까요 ㅠ

**Comment by thomasJang** [comment]
어느버전을 쓰시는지 알려주세요 배포된버전이 문제일 수 있습니다

**Comment by yongjun0213** [comment]
"2015-06-10 tom : https://github.com/axisj/axisj/issues/603 버그픽스 " 이버전입니다

**Comment by thomasJang** [comment]
<img width="1792" alt="capture 2016-02-24 20 41 10" src="https://cloud.githubusercontent.com/assets/5884902/13284340/fde9420a-db36-11e5-9f1e-33cc2139342f.png">

현재 최신버전으로 IE 10에서 문제가 없습니다. 최신버전을 받아 사용 하세요
