### ISSUE TITLE
AXGrid.printList에서 오류

### ISSUE THREAD

**Issue by choiseungmun** [axisj/axisj#814]
안녕하세요? 이번에 AXISJ를 업무에 도입해보고자 이것저것 검토를 해보고 있습니다.
매우 훌륭한 프레임워크 인것 같습니다.

다름이 아니라, 반응형 관련해서 확인해보고자 이리저리 테스트해보는 도중
첨부한 그림과 같은 오류가 발생합니다.

항상 발생하는 것은 아니고, 10번중 7번중 발생하는 것 같습니다.
AXGrid.printList()에서
```javascript
            /// console.log(cfg.height, this.list.length);
            if (cfg.__height != "auto" && this.list.length > 0) {
                //아이템 한줄의 높이는?
                var itemTrHeight = this.cachedDom.tbody.find("#" + cfg.targetID + "_AX_null_AX_0").outerHeight().number();
```

부분에서 발생하는 것 같습니다.
Axisj 릴리즈 버전은 1.0.22를 사용하고 있으며, 크롬에서 테스트 하고 있습니다. 

![_022616_011246_pm](https://cloud.githubusercontent.com/assets/17488277/13342982/a27b7ad2-dc8a-11e5-84d1-ae8fdef3e08f.jpg)

추신:
그리드의 클릭(더블클릭포함해서) 이벤트 핸들러를 사용하는 중에, 키보드와 마우스의 조합을 판정할 수 없는 문제가 있습니다. (특히 FF에서는 꼼수로 처리하는 방법밖에는 없습니다.)
때문에, 이벤트 핸들러 시그니처에 이벤트객체도 같이 전달이 되도록 해주시면 큰 도움이 될 것 같습니다.

키보드 이벤트를 확인하기 위해 아래와 같은 꼼수를 사용했습니다.
```javascript
body : {
	ondblclick: function(numRow, objRow, event){	
		var event = event || window.event;		
		if(!event)
		{
			 //FF에선 event가 argument로 전달되지 않은채 바로 사용할 수 없다.
			 //AXISJ의  ondblclick 함수에는 event argument가 정의되어 있지 않으나, FF를 위해 편법으로 사용했다.
			 //FF에서는 키보드 이벤트에 상관없이 처리하도록 한다.			
			doTest();
			return true;
		}		
		if (event.altKey) {
			doModalTest();
		}
		else {
			doTest();
		}
	},
},
```

**Comment by thomasJang** [comment]
알려주신 버그는 지금 예상되는 돔이 없어서 생기는 문제 인데요.
만약 특정 브라우저에서 돔 처리 속도가 느려서 문제라면 좀 더 많이 고쳐야 가능할 수 있습니다.

**Comment by choiseungmun** [comment]
안녕하세요?
적절한 방법인지는 모르겠지만, 아래 그림처러 처리해서 다양하게 테스트해보았는데
일단 제 컴환경에서는 큰 문제가 없는 것으로 보여 글을 남깁니다.

컴 환경 : 
- Win 7, IE8이상, 크롬, FF, 윈도우용 사파리, 
-  맥레티나 : 크롬, FF, 사파리

모바일 디바이스에서는 테스트 못해 봤습니다.
![_031016_104816_am_031016_105114_am](https://cloud.githubusercontent.com/assets/17488277/13656955/b0e80b2a-e6ae-11e5-9186-862b0c645bfa.jpg)

----
![_031016_104939_am](https://cloud.githubusercontent.com/assets/17488277/13656958/b4d7d6d4-e6ae-11e5-9523-caad48d02399.jpg)

----
![_031016_104625_am_031016_105036_am](https://cloud.githubusercontent.com/assets/17488277/13656966/b8205f96-e6ae-11e5-82df-bf6ba27d78b7.jpg)

**Comment by thomasJang** [comment]
:+1:
