### ISSUE TITLE
AXGrid 9번째 페이지에서 오류

### ISSUE THREAD

**Issue by babuky** [axisj/axisj#815]
안녕하세요? 지인의 소개로 약 1개월 정도 사용하고 있습니다. 감사합니다.
그런데 원인을 알수없는 오류가 발생을 하였습니다.

페이징을 하다가 페이지당 20개씩 지정하고 9번째 페이지 조회 하려면 화면에 풍차가 지속적으로
나오면서 더이상 지행하지를 않습니다.
처음엔 너무 빨리 페이지 이동을 눌러서 발생하는지 알았는데 그것도 아니고 
무조건 9번째 페이지에서 멈춤니다.

무엇을 제가 잘못 했는지 조언 좀 부탁드립니다.

grid 설정 내용
------------------------------------------------------------------------------------------------------------------------
```js
this.target.setConfig({
		targetID : "portfolioGrid",
		theme : "AXGrid",
		mediaQuery: {
			mx: {min:0, max:767}, dx: {min:767, max:1024}
		},
		fitToWidth:true,
		emptyListMSG: msgConfig.GRID_EMPTY_MSG,
		sort : true,
		mergeCells: [[1],[2]],
		colHeadAlign: "center",
		colGroup : selectColGroup,
		colHead : {
			rows: [selectRows],
			onclick: function(){
				//toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, colHead:this.colHead, page:this.page}));
			}
		},
		body : {
			onclick: function() {

			},
			ondblclick: function() {
				
			}
		},
		page:{
			paging: true,
			pageNo:1,
			pageSize:20,
			status:{formatter: null}
		}
	})
},
```
------------------------------------------------------------------------------------------------------------------------------
감사합니다.

**Comment by thomasJang** [comment]
부라우저에 콘솔을 열어 네트워크의 결과를 확인하세요 그페이지에서만 잘못된 데이터를 응답하는 문제입니다

**Comment by lhslive** [comment]
9번째 페이지의 json을 확인해 보세요. 특수문자(ex:개행문자) 등이 포함된게 아닐까 싶은데요
