### ISSUE TITLE
mergeCells 버그같습니다.

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#819]
![default](https://cloud.githubusercontent.com/assets/12386521/13489146/ab1782b6-e168-11e5-8c3c-3f0d234f559f.png)

두번째 머지값에서 그리드가 깨지는 현상이 발생합니다.
머지값이 작으면 발생하지 않는데. 첫번째 열 머지값이 큰경우 발생하는것
같습니다. ie, chrome 모두 발생합니다.

<script id="jscode">
		/**
		 * Require Files for AXISJ UI Component...
		 * Based        : jQuery
		 * Javascript   : AXJ.js, AXGrid.js, AXInput.js, AXSelect.js
		 * CSS          : AXJ.css, AXGrid.css, AXButton.css, AXInput.css, AXSelector.css
		 */
		var pageID = "fixedColSeq";
		var myGrid = new AXGrid();
		var itemSum = 0;

		var fnObj = {
			pageStart: function() {

				myGrid.setConfig({
					targetID: "AXGridTarget",
					theme: "AXGrid",
					fixedColSeq: 3,
					mergeCells: [0,1,2],
					colGroup: [
						{key: "no", label: "번호", width: "50", align: "right"},
						{key: "title", label: "제목", width: "150"},
						{key: "writer", label: "작성자", width: "100", align: "center"},
						{key: "regDate", label: "작성일", width: "100", align: "center"},
						{key: "price", label: "가격", width: "100", align: "right", formatter: "money"},
						{key: "amount", label: "수량", width: "80", align: "right", formatter:"number", editor: {type: "number"}},
						{
							key: "cost", label: "금액", width: "100", align: "right", formatter: function() {
							return (this.item.price.number() * this.item.amount.number()).money();
						}
						},
						{key: "desc", label: "비고", width: "500"}
					],

					colHead: {
						heights: [30, 30],
						rows: [
							[
								{colSeq: 0, rowspan: 2},
								{colSeq: null, colspan: 3, label: "표현식", align: "center"},
								{colSeq: 4, rowspan: 2},
								{colSeq: 5, rowspan: 2},
								{colSeq: 6, rowspan: 2},
								{colSeq: 7, rowspan: 2}
							],
							[
								{colSeq: 1},
								{colSeq: 2},
								{colSeq: 3}
							]
						]
					},

					body: {
						marker: function() {

						},
						onclick: function() {
							toast.push(Object.toJSON({index: this.index, r: this.r, c: this.c, item: this.item}));
							//alert(this.list);
							//alert(this.page);
						},
						ondblclick: function() {
							//toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item}));
							//alert(this.list);
							//alert(this.page);
						}
					},
					page: {
						paging: false
					}
				});

				var list = [];
				var j = 0;
				for (var i=0;i<400 ;i++ ){
					if (i%100 ==0){
						j++;
					}
					list.push({
						no: j,
						title: "AXGrid "+i+"째 줄 입니다.",
						writer: "장기영",
						regDate: "2013-01-18",
						desc: "myGrid.setList 의 첫번째 사용법 list json 직접 지정 법",
						price: 129500,
						amount: 1
					}
					);
				}
				myGrid.setList(list);
			}
		};

**Comment by thomasJang** [comment]
```js
body : {
    heights: [30],
    onclick: function(){

    }
},
```

처럼 해보세요. 높이 계산에 좀 문제가 있습니다.
바디에 여러줄을 쓰시는 경우엔 [30,30] 처럼 각 줄의 높이를 설정해야 합니다.

**Comment by cococl** [comment]
감사합니다.~
