### ISSUE TITLE
액시스제이 사용자 교육 안내

### ISSUE THREAD

**Issue by thomasJang** [axisj/axisj#826]
액시스제이 사용자 교육에 대한 의견을 30분 넘게 주셨습니다.
의견을 토대로 다음과 같이 교육일정을 정하였습니다.
다음의 링크로 이동 하셔서 참가 신청 해주세요.
감사합니다.
http://goo.gl/forms/z7tuJSj576
교육일시 : 3월 24일 오후 4시 ~ 6시까지
교육장소 : 강남토즈(예약이 진행해보고 변경 될 수도 있습니다. 참가신청 하신분들에게 자세한 사항을 안내하겠습니다.)
교육인원 : 선착순 20명(입금하신순으로 하겠습니다.)
참가비 : 1만원 (교육에 오시면 만원을 다시 돌려드리도록 하겠습니다.)
* 많은 참가 바람니다.

![2016-03-13_01-36-49](https://cloud.githubusercontent.com/assets/5884902/13735502/d0a54706-e9ed-11e5-9535-54e8bf69e1d0.png)
![2016-03-13_01-36-24](https://cloud.githubusercontent.com/assets/5884902/13735504/d4b4ec3e-e9ed-11e5-89d9-0dad0cb7e315.png)
![2016-03-13_01-36-06](https://cloud.githubusercontent.com/assets/5884902/13735506/d9820b20-e9ed-11e5-8cca-16a4f1277945.png)

**Comment by hyunjun19** [comment]
@thomasJang 진행요원이 필요하지 않으신가요? ; )

**Comment by panic910** [comment]
:+1:

**Comment by thomasJang** [comment]
@hyunjun19 진행요원 필요하지요~ 
@panic910 이럴 때 한번 만나서 맥주라도

**Comment by Happy2You** [comment]
아.. 이런 좋은 기회를 놓치다니.. ㅠㅠ 깃허브를 한동안 안들어왔는데.. 아쉽네요 ~
