### ISSUE TITLE
AXISJ API에 대한 한글 파일.

### ISSUE THREAD

**Issue by kangsangyong** [axisj/axisj#830]
안녕하세요.

현재 중국에 있는 한국 개발자입니다.

대단합니다. 해외에만 이런 UI프레임웍이 있는줄 알았는데, 한국에도 이런좋은 프레임웍이 있다니요.

최근 자바로 웹개발중 AXISJ를 알게되어 지금 연구중에 있습니다.

조금 불편한것이 AXISJ API를 보려면 인터넷에 접속해야만 볼수 있던지 아님,

필요한 부부만 스크렙하든지 하거든요.

여기는 인터넷 사정이 그리 좋지 않아 항상 상황이 여의치 않습니다.

그래서 혹시 AXISJ API 관련해서 doc 파일을 제공할 수 있는지 궁금해서리...☞☜

같은 개발자로써 염치가 없네요..근데..앞으로 자주 보게 될것 같은 Feel이....

혹시 API문서 제공 가능 한가요?

**Comment by thomasJang** [comment]
음 베스트는 
https://github.com/axisj/axisj-about
https://github.com/axisj/axisj-jsdoc

에가서 소스를 클론(또는 다운로드) 하시고 로컬에서 실행 하시면 되겠습니다.
특별한 환경을 타지 않으니 APM등을 이용하여 셋팅 하시거나 톰캣에 하나 연결 해두셔도 좋겠습니다.

**Comment by kangsangyong** [comment]
감사합니다.
