### ISSUE TITLE
AXGrid 에서 스크롤 변경시 데이터 변경 문의

### ISSUE THREAD

**Issue by ParkJunHyeung** [axisj/axisj#834]
AXgrid 상에서 데이터를 변경시 한페이지 이상 변경건이라 스크롤을 내리면서 변경을 하고 있습니다
스크롤을 내리고 다시 올리면 변경한 값이 다시 원상복귀가 되어있는데..
혹시 이 옵션을 제어할수 있는 방법이 있을까요?
빠른 답변 부탁드리겠습니다.

**Comment by hyunjun19** [comment]
옵션이 아니라 가상 스크롤 때문에 발생하는 문제인것 같습니다.
한 페이지 이상 스크롤을 내리면 기존 내용(HTML)을 지워버렸다가 해당 내용을 다시 조회하는 경우 
AXGrid가 내부적으로 가지고 있는 값을 가지고 다시 내용(HTML)을 뿌리게 됩니다.

현재 말씀하신 버그는 내용을 변경시 AXGrid가 내부적으로 가지고 있는 값을 업데이트 하지 않아서
발생하는 문제로 보입니다.

관련 소스를 올려주시면 문제가 되는 부분을 도와드릴 수 있을 것 같습니다.

**Comment by gilminjong** [comment]
저도 같은 현상으로 해결방법 공유 드릴게요.
제가 파악한게 정확하게 맞는지는 아닐수 있으니 참조하세요.

AXGrid.js 파일을 보면  
35번째줄  this.config.listCountMargin = 12;
로 되어 있습니다.
이건  스크롤시 그리드안에 리스트가 위부터 12번째가 넘어갈경우 리로드를 하는것 같습니다.
저는 이값을 2배수하여 사용중입니다.
