### ISSUE TITLE
AXGRID에서 컬럼의 넓이를 자동으로 조절되게 하고 싶습니다. 

### ISSUE THREAD

**Issue by bloodiel** [axisj/axisj#835]
그리드 컬럼 설정 중에  {key:.... width:..}에서
width 항목을 지정된 숫자가 아닌 그리드에서 보여줄 값에 따른 넓이를 자동으로 조절해줄수있는 변수 같은게 있나요? 예를들어 auto 같은

**Comment by hyunjun19** [comment]
`width: '*'` 이렇게 해보셨나요?

**Comment by bloodiel** [comment]
큰따옴표로하면 칸이 엄청작아져서 다른게 있나 했더니 ....

작은 따옴표를 하니 해결됐네요^^ 감사합니다.
