### ISSUE TITLE
fixedColSeq display:false 사용시 화면 밀림..

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#837]
수고하십니다.~
번호를 display:false 처리하니 스크롤시 밀리네요~

				myGrid.setConfig({

					targetID: "AXGridTarget",
					theme: "AXGrid",
					fixedColSeq: 3,
					mergeCells: [1,2],
					colGroup: [
						{key: "no", label: "번호", width: "50", align: "right", display:false},
						{key: "title", label: "제목", width: "150"},
						{key: "writer", label: "작성자", width: "100", align: "center"},
						{key: "regDate", label: "작성일", width: "100", align: "center"},
						{key: "price", label: "가격", width: "100", align: "right", formatter: "money"},
						{key: "amount", label: "수량", width: "80", align: "right", formatter:"number", editor: {type: "number"}},
						{
							key: "cost", label: "금액", width: "100", align: "right", formatter: function() {
							return (this.item.price.number() * this.item.amount.number()).money();
						}
						},
						{key: "desc", label: "비고", width: "500"}
					],

					colHead: {
						heights: [30, 30],
						rows: [
							[
								{colSeq: 0, rowspan: 2},
								{colSeq: null, colspan: 3, label: "표현식", align: "center"},
								{colSeq: 4, rowspan: 2},
								{colSeq: 5, rowspan: 2},
								{colSeq: 6, rowspan: 2},
								{colSeq: 7, rowspan: 2}
							],
							[
								{colSeq: 1},
								{colSeq: 2},
								{colSeq: 3}
							]
						]
					},

					body: {
						marker: function() {

						},
						onclick: function() {
							toast.push(Object.toJSON({index: this.index, r: this.r, c: this.c, item: this.item}));
							//alert(this.list);
							//alert(this.page);
						},
						ondblclick: function() {
							//toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item}));
							//alert(this.list);
							//alert(this.page);
						}
					},
					page: {
						paging: false
					}
				});

![default](https://cloud.githubusercontent.com/assets/12386521/14071817/319f3c54-f4f4-11e5-8579-ec4807de8f56.png)

**Comment by thomasJang** [comment]
샘플이 오래되서 조금 문제인데요..
```
colHead: {
	heights: [30,30],
	rows: [
		[
			{
				key:"no",
				rowspan: 2
			},
			{
				colspan: 3,
				label: "표현식",
				align: "center"
			},
			{
				key:"price",
				rowspan: 2
			},
			{
				key:"amount",
				rowspan: 2
			},
			{
				key:"cost",
				rowspan: 2
			},
			{
				key:"desc",
				rowspan: 2
			}
		],
		[
			{
				key:"title"
			},
			{
				key:"writer"
			},
			{
				key:"regDate"
			}
		]
	]
}
```

이런식으로 한번 해보시겠어요? 안되시면. 디버그 해보겠습니다.

**Comment by cococl** [comment]
적용해봤는데 똑같습니다.
