### ISSUE TITLE
AXJ.min.js 로딩 문제

### ISSUE THREAD

**Issue by jaehongchung** [axisj/axisj#838]
안녕하세요?
액시스 제이 정말 잘쓰고있는데요

AXJ.min.js 불러오는데 속도 이슈가 조금 있어 문의 드립니다.

저희 서버쪽에 파일 놔두고 불러와도 로딩이 거의 한 7초정조 걸리는 편이고

아래와 같이 해도 조금 로딩이 걸리는 편인것 같습니다..
<script type="text/javascript" src="http://cdno.axisj.com/axisj/dist/AXJ.min.js"></script>

해결책이 없는지 여쭙고 싶습니다.

**Comment by lhslive** [comment]
테스트 하는 페이지 소스를 볼 수 있을까요? 
다른 문제가 있어 보입니다.
