### ISSUE TITLE
AXSearch 객체 이용시 바인드 방법 문의

### ISSUE THREAD

**Issue by weleek** [axisj/axisj#847]
API에 나와있는 방법은 html 태그를 먼저 작성한 뒤에 폼에다 아이디 속성을 추가하여 AXSearch 객체를 바인딩 하는경우와 div 태그만 작성한뒤 자바스크립트로 아예 만들어주는 경우 2가지가 나와있는데요

저같은 경우는 html 태그로 먼저 작성을 한뒤 AXSearch 객체 바인딩을 하고 싶습니다. 
그런데 이경우에 상세검색 버튼 클릭시 안보이던 검색 항목이 보여지게 하는 이벤트등을 발생하려고 하면 어떤식으로 작성하여야 동작할까요?

**Comment by thomasJang** [comment]
http://dev.axisj.com/samples/AXSearch/nonScript.html 이 페이지 샘플을 보시면 될 것 같아요
