### ISSUE TITLE
라이센스 문의

### ISSUE THREAD

**Issue by aaboo** [axisj/axisj#849]
Axisj 사용을 하기 위해선, 100% 오픈이라고 알고 있었는데...

L머시기, M머시기... 잘 모르겠거든요 ㅠㅠ
좀 쉽게 설명해 주세요.

링크로 알려주시지 말고, 아시는 범위내에서 간단하게 유료다 무료다 이런식으로만 알려주시면 감사하겠습니다.

**Comment by thomasJang** [comment]
무료라고 이야기 하면 섭하지만 아쉽게도 무료네요
단, AXISJ소스코드를 수정할 경우에 axisj에 pull request 등의 방법으로 알려주셔야 합니다.
