### ISSUE TITLE
fixedColSeq display:false 사용시 화면 밀림(2) #837

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#851]
디버그 한번 해봤는데요.  아래부분에서 문제가 있을거 같긴한데요
한번 봐주시죠.

getItem: function (itemIndex, item, isfix, hasTr) {
....
                    if (isfix == "fix" && colCount < (cfg.fixedColSeq + 1)) {
                        printOk = true;
                        if (typeof CH.colSeq == "undefined" || CH.colSeq == null) {
                            if (r > 0 && cfg.body._maps[r][CHidx] && cfg.body._maps[r][colCount].r != r) {
                                printOk = false;
                            }
                        }
                        else {
                            var _postion = cfg.body._maps[r][CH.colSeq];
                            // display:false 처리한 컬럼을 계산을 해야할듯합니다.
                            if (CH.colSeq > (cfg.fixedColSeq)) {
                                printOk = false;
                            }
                        }
....
}

**Comment by thomasJang** [comment]
버그 픽스 되었습니다. 릴리즈는 아직 안햇으니 깃 소스 받으셔야 합니다.

**Comment by cococl** [comment]
감사합니다.
