### ISSUE TITLE
그리드 헤더를 클릭하여 정렬할때....

### ISSUE THREAD

**Issue by jeongjaehong** [axisj/axisj#857]
데이터 베이스에서 select한 resultset을 json형태로 포맷팅 하면서 순번을 _id라는 키값을 이용해 레코드에 순번을 부여해서 그리드에 표시하려고 할때 컬럼 키값에 의해서 정렬기능이 오동작 합니다. 

![capture 22](https://cloud.githubusercontent.com/assets/859932/14780363/8a713ede-0b17-11e6-8a3e-dfe440585ab8.png)

컬럼 키값을 seq_no로 되어 있는 부분을 "_id" 로 해서 그리드를 생성하면 헤더 클릭시 숫자컬럼이 문자형태로 정렬이 됩니다.

1
10
2
3
4 

형태로 정렬이 됩니다.

**Comment by thomasJang** [comment]
데이터가 number 이면 됩니다. string 타입을 정렬해서 그렇습니다. 

데이터를 바꾸기에 부담되시면. Formatter: function(){ return this.value.number(); } 해주시면 될 거 에요

**Comment by jeongjaehong** [comment]
![image](https://cloud.githubusercontent.com/assets/859932/14802515/4e5aec40-0b8c-11e6-87bc-054691be7179.png)

money 포멧을 적용했더니 중간에 콤마가 있어서 그랬는지 문자열로 인식해서 그랬나 봅니다.
해결방안으로 제시해 주신데로 number로 적용하니 원하는 데로 정렬이 됩니다.
감사합니다.

![image](https://cloud.githubusercontent.com/assets/859932/14802520/5b84cf1c-0b8c-11e6-934b-88a373638471.png)

**Comment by jeongjaehong** [comment]
그런데 format을 money로 하더라도 컬럼명을 seq_no처럼 맨 앞에 _ 가 들어가지 않을 경우에는 원하는 대로 정렬이 되더라구요.. 

그래서 말인데 혹시나 다른 컬럼들 금액 같은경우... format을 money로 지정할 경우 제대로 정렬이 안되는건 아닐까요?
