### ISSUE TITLE
호환성보기 모드에서 그리드의 팝업Div가 일그러져 보입니다.

### ISSUE THREAD

**Issue by jeongjaehong** [axisj/axisj#859]
사이트에서 사용중인 인증서 관련 모듈때문에 호환성 보기를 사용하도록 권고를 하고 있습니다.

axGrid를 적용하고 보니 호환성보기 모드에서는 div 레이어가 첨부한 캡쳐화면과 같이 깨져 보입니다.

호환성보기 옵션을 off시키면 정상적으로 표시됩니다. 다른 해결방법이 있을까요? 

![capture 25](https://cloud.githubusercontent.com/assets/859932/14802417/99ea751e-0b8b-11e6-9934-58e45f5a7845.png)

![capture 24](https://cloud.githubusercontent.com/assets/859932/14802418/99ea9cba-0b8b-11e6-9ece-5da2a2b76edd.png)

**Comment by lhslive** [comment]
axisj는 아니지만 다른 프레임워크 (jqueryui)를 이용해 서비스중인 사이트에서도 같은 현상이 있었는데요..
저같은 경우에는 호환성보기에서 Microsoft 호환성 목록 사용을 체크 해제하고 나서 문제를 해결 했던적이 있습니다.

**Comment by jeongjaehong** [comment]
사이트에 사용중인 솔루션중 일부가 호환성보기를 설정한 상태에서만 정상 동작하는 녀석이 있어서 문의 드렸습니다.
일단은 HeadTool은 사용하지 않는 방향으로 해야할듯 합니다. ^^;

호환성보기를 지정하거나 지정하지 않았을 때도 설정값과 무관하게 화면이 제대로 표시되게 할수 없을까요?
