### ISSUE TITLE
setDataSet 적용이 되지 않습니다.

### ISSUE THREAD

**Issue by parkhr120** [axisj/axisj#860]
` grid: {
            target: new AXGrid(),
            bind: function(){
                window.myGrid = fnObj.grid.target;

                myGrid.setConfig({
                    targetID : "AXGridTarget",
                    sort:true,
                    theme : "AXGrid",
                    remoteSort: true,
                    fitToWidth  : true,
                    //viewMode: "grid", // ["grid","icon","mobile"]
                    // 브라우저 사이즈에 따른 changeGridView 설정
                    mediaQuery: {
                        mx:{min:0, max:600}, dx:{min:600}
                    },
                    colGroup : [
                        { key: "idx", label: "checkbox", width: "30", align: "center", formatter: "checkbox", display:false },
                        { key: "up_company_name", label: "상차지", width: "200", align: "center", formatter: "dec" },
                        { key: "down_company_name", label: "하차지", width: "200", align: "center" },
                        { key: "item_type", label: "상품종류", width: "150", align: "center" },
                        { key: "package_weight", label: "중량", width: "150", align: "center", formatter: "dec" },
                        { key: "driver_name", label: "운송인이름", width: "200", align: "center" },
                        { key: "start_date", label: "상차일", width: "150", align: "center" },
                        { key: "end_date", label: "하차일", width: "150", align: "center" },
                        { key: "up_purchase_price", label: "매입금액", width: "150", align: "center", formatter:"money" },
                        { key: "down_purchase_price", label: "납품금액", width: "150", align: "center", formatter:"money" }
                        //{key: "edit_package", label: "수정하기", width: "100", align: "center", formatter:function(){
                        //    return '<button type="button" class="AXButton Blue W50" onclick="editButton(' + this.index + ');">수정</button>';
                        //}},
                        //{key: "delete_package", label: "삭제하기", width: "100", align: "center", formatter:function(){
                        //    return '<button type="button" class="AXButton Red W50" onclick="deleteButton(' + this.index + ');">삭제</button>';
                        //}}
                    ],
                    colHeadAlign: "center", // 헤드의 기본 정렬 값 ( colHeadAlign 을 지정하면 colGroup 에서 정의한 정렬이 무시되고 colHeadAlign : false 이거나 없으면 colGroup 에서 정의한 속성이 적용됩니다.
                    body : {
                       onclick: function(){
                            package_view(this.item);
                        }
                    },
                    foot : {
                        rows: [
                            [
                                {colSeq:null, colspan:8, formatter:function(){
                                    return "계";
                                }, align:"center"},
                                {colSeq:4, formatter:function(){
                                    var sum = 0;
                                    $.each(this.list, function(){
                                        sum += this.up_purchase_price;
                                    });
                                    return sum.money();
                                }},
                                {colSeq:5, formatter:function(){
                                    var sum = 0;
                                    $.each(this.list, function(){
                                        sum += this.down_purchase_price;
                                    });
                                    return sum.money();
                                }},
                                {colSeq:7}
                            ]
                        ]
                    },
                    page: {
                        paging:true
                    }
                });

                myGrid.setList({
                    ajaxUrl: "/admin/package_com/package_list/?package_status=1",
                    onLoad: function () {
                        //if (myGrid.list.length == 0) {
                        //    alert("검색된 결과가 없습니다.");
                        //}
                    }

                });
                myGrid.setDataSet({});
                editButton = function(index){
                    $.Event(event).stopPropagation();
                    package_edit_btn(myGrid.list[index]);
                }
                deleteButton = function(index){
                    $.Event(event).stopPropagation();
                    package_delete(myGrid.list[index]);
                }

            }
        }`

foot부분에서 매입금액과 납품 금액을 합쳐서 보이게 하고 싶은데 처음에 화면에 들어가면 계 부분에서 0으로 나오고 크롬에서 f12를 누르고 다시 취소하면 계산 식이 적용되어서 보입니다. 혹시 화면을 띄웠을때 바로 계산되어서 보이게 하는 방법은 없나요?

**Comment by lhslive** [comment]
```
            myGrid.setList({
                ajaxUrl: "/admin/package_com/package_list/?package_status=1",
                onLoad: function () {
                    //if (myGrid.list.length == 0) {
                    //    alert("검색된 결과가 없습니다.");
                    //}
                }

            });
            myGrid.setDataSet({});
```
위 소스를 
```

            myGrid.setList({
                ajaxUrl: "/admin/package_com/package_list/?package_status=1",
                onLoad: function () {
                    myGrid.setDataSet({});
                    //if (myGrid.list.length == 0) {
                    //    alert("검색된 결과가 없습니다.");
                    //}
                }

            });
 ```

이런 형태로 변경해 보시고 테스트 해 보시면 어떠실런지요?..

**Comment by parkhr120** [comment]
lhslive님// onload할때 실행해 보는 것을 생각을 못했었네요 ㅜㅜ 변경하니 잘 적용 됩니다. 감사합니다!
