### ISSUE TITLE
grid 헤더 없애는 옵션 같은것 없나요?

### ISSUE THREAD

**Issue by lspclass** [axisj/axisj#869]

**Comment by lspclass** [comment]
grid 옵션에서 label에 값을 안주거나 null값일 경우 untitle로 나오는데 이때 그냥 값없이 표시되게 하는 방법이랑  두번째는 grid헤더 자체를 아예 없이 controler단에서 받은 리스트만 뿌려주는 방법 2가지 좀 문의드립니다. 수고하십시오

**Comment by lhslive** [comment]
해더 출력을 빈칸으로 하고 싶으시면 colhead 구성시에 label:" " 이런식으로 빈칸을 주시면 됩니다.
해더를 없애고 싶으실 경우 저는 그냥 myGrid.colHead.hide() 로 해결합니다.
물론 해더 높이만큼 자리를 차지하니 이후 처리도 해 주셔야 하고요.

**Comment by lspclass** [comment]
감사합니다. 헤더 없애는 옵션 적용해보겠습니다.답변주셔서 감사합니다. ~ ^^
------ Original Message ------
Date: Monday, May 2, 2016 04:01:56 PM
