### ISSUE TITLE
AXGrid의 클릭이벤트에서 현재 선택된 컬럼 정보를 확인하려면...

### ISSUE THREAD

**Issue by jeongjaehong** [axisj/axisj#875]
this.c 속성밖에 사용할수 없나요?

colGroup에 정의한 key값을 이용하는 방법이 있는지 궁금합니다.

if (this.key == 'empt_code') { ....이나

this.c 의 index값을 대체해서 사용할 수 있는 방법이 있나요?

가령 컬럼순서가 바뀌거나 했을경우 onClick이벤트의 해당 부분을 다시 작업해야 하는 번거로움이나 오류를 예방할 수 있도록 컬럼 key값을 사용하고자 합니다.

**Comment by lhslive** [comment]
myGrid.config.colGroup[this.c].key

**Comment by thomasJang** [comment]
```js
onclick: function(){
  console.log(this);
  // this.item, this.value, this.key, this.list, this.r, this.c 등등등
}
```
해보시면 오브젝트를 확인 할 수 있습니다.
만약 console.log 가 제대로 지원되지 않는 브라우저(IE)라면
`trace(this);` 해보세요

**Comment by jeongjaehong** [comment]
감사합니다.
