### ISSUE TITLE
AX Grid 우측 스크롤 영역 관련 문의 드립니다.

### ISSUE THREAD

**Issue by rain0448** [axisj/axisj#876]
![grid](https://cloud.githubusercontent.com/assets/19299605/15170864/ce79dcd4-1784-11e6-9b56-87f0c0acfee0.png)

오른쪽 빨간 박스 영역 관련 문의 입니다.

스크롤이 안생겨도될 상황에서 또는 설정을 통하여 스크롤 영역을 감출순 없을까요?

설정들을 보았을때 찾지를 못한거같아서 문의 드립니다.

**Comment by thomasJang** [comment]
http://dev.axisj.com/samples/AXGrid/index.html 아마 이런 그리드 같습니다.

아래 코드에 보면

```
AXConfig.AXGrid.fitToWidthRightMargin = -1;
```
라고 있습니다. 테스트 해보세요

**Comment by rain0448** [comment]
네 확인하였습니다 그옵션이 맞습니다.

감사합니다.
