### ISSUE TITLE
AXTwinDate, selector 리사이즈 관련 버그

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj/axisj#883]
아래 소스코드로 AXTwinDate, Selector를 바인딩해서 사용하고 있습니다.
그런데 리사이즈 할때 버튼 및 아이콘이 엉뚱한곳으로 가버리는 버그가 발생하고 있네요....
아래 이미지를 보시면 맨 아래에 아이콘이 가있는 것을 볼 수 있습니다.......
해결방안이 필요할 거 같네요.
![default](https://cloud.githubusercontent.com/assets/8294689/15413968/abfed2d4-1e70-11e6-98b7-18149c2bccb5.PNG)

`$(".AXTwinDate").each(function(){
		$(this).css("width","40%");

		var sDateId = $(this).data("start");

		$("#" + sDateId).css("width","40%");
		
		$(this).bindTwinDate({
	        align:"right",
	        valign:"top",
	        startTargetID: sDateId, 
	        onChange:function(){
               //toast.push(Object.toJSON(this));
	        }
		});
	});
	
	//$(".searchUserInput").after("<button type='button' class='AXButton'><i class='axi axi-ion-close-circled'></i></button>");
	$(".searchUserInput").bindSelector({
		reserveKeys : {options: "userList", optionValue: "userOid", optionText: "userName"},
        optionPrintLength :"all",
        onsearch : function(objID, objVal, callBack) {
        	
        	if(objVal.indexOf("[")  > 0){
        		objVal = objVal.substring(0, objVal.indexOf("[") -1);
        	}
        	
       		ajaxCallServer("/Windchill/esolution/user/searchUserAutoComplete", "userName=" + objVal, function(data){
           		callBack({
   					options:data.userList
   				});
           	});
        },
        onChange : function(){
        	
        	var value = "";
       		if(this.selectedOption != null){
           		value = this.selectedOption.userOid;
           	}
       		
       		var targetID = this.targetID;
       		
       		if(targetID == null){
       			targetID = this.id;
       		}
       		
       		var target = $("#" + targetID ).data("target");
       		
       		if( $("#" + target).length > 0 ){
       			$("#" + target).val(value);
       		}else{
       			$("#" + targetID).after("<input type='hidden' name='" + target + "' id='" + target + "' /> ");
       			$("#" + target).val(value);
       		}
     	},
		finder:{
			onclick: function(){
				
				var targetID = this.targetID;
				
				
				var target = $("#" + targetID ).data("target");
	       		
	       		if( $("#" + target).length == 0 ){
	       			$("#" + targetID).after("<input type='hidden' name='" + target + "' id='" + target + "' /> ");
	       		}
				
				openPopup("/Windchill/esolution/user/searchUserInfo?tempName=" + targetID + "&targetName=" + target,800,500);
				//AXUtil.alert(this);
				//$("#" + this.targetID).setValueInput("wt.org.WTUser:11");
			}
		}
	});`

**Comment by thomasJang** [comment]
UI 바인딩 후에 타켓포지션이 틀어지면 이런 현상이 생길 수 있습니다.
$(window).resize(); 를 호출해주면 다시 제 위치를 찾아가게 됩니다.

**Comment by DaeHyeon-Kim** [comment]
되네요 감사합니다.
