### ISSUE TITLE
그리드 2개 이상 한페이지에 사용시 paging 문제 발생

### ISSUE THREAD

**Issue by gosumdochi** [axisj/axisj#889]
그리드 2개를 사용하는 상황에서 상단 그리드의 페이징 버튼 ▶을 클릭하면 하단 그리드의
내용이 변합니다. 하단 그리드의 페이징 버튼 ▶버튼을 클릭하면 정상적으로 나오는데
api를 봐도 그리드를 식별하는 id 값같은게 없는 것 같습니다. 어찌 해결을 해야 하는지요?

이미지 반출이 안되어 글로 설명합니다.

◆◆◆◆화면◆◆◆◆
---------------------------------------
그리드 1
|◀ 1/154 ▶ ▶|
---------------------------------------
그리드 2
|◀ 1/2 ▶ ▶|
---------------------------------------

◆◆◆◆javascript 파일◆◆◆◆
grid1 과 grid2의 setConfig() 속
body : { 속
page:{
				paging:true,
				pageNo:1,
				pageSize:5,
				onchange: function(pageNo){}
			}
으로 그리드 1과 그리드 2가 동일합니다.

◆◆◆◆ html 파일 소스 현황 ◆◆◆◆

/////////////////////////////////////////////////////////////////////////

<div class="gridFolder">
			<div id="grid1" class="gridTit" onclick="javascript:openClose('gridPolicySetting');"><strong id="menu1">Grid1 </strong> </div>
			<div id="gridPolicySetting" class="gridBtLine"></div>
		</div>

		<div class="paging">
			<div class="pageCount">
				<select id="pageSize1" name="pageSize1" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
		
		<div class="gridFolder">
			<div id="grid2" class="gridTit" onclick="javascript:openClose('gridPolicySetting2');"><strong id="menu2">Grid2 </strong> </div>
			<div id="gridPolicySetting2" class="gridBtLine"></div>
		</div>
		
		<div class="paging">
			<div class="pageCount">
				<select id="pageSize2" name="pageSize2" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>

답변 기다리겠습니다
부탁드립니다 !

**Comment by gosumdochi** [comment]
위의 html 잘린 부분입니다
<div class="gridFolder">
			<div id="grid1" class="gridTit" onclick="javascript:openClose('gridPolicySetting');"><strong id="menu1">MD5: </strong> </div>
			<div id="gridPolicySetting" class="gridBtLine"></div>
		</div>

**Comment by groovedk** [comment]
html 이 아니라 js를 올려줘야 할텐데 엄한걸 올려주셨네요
일단 그리드 페이징을 따로 구현 하신거같은데 데모에 보시면 페이징이 되어있는 소스가 있습니다. 

그리고 그리드를 식별하는 아이디는 config에 targetID 로 구분합니다. 
올려주신 html 에서 연결되는 해당 타겟 아이디는 "gridPolicySetting" 입니다.

**Comment by gosumdochi** [comment]
groovedk 님 먼저 답변 달아 주셔서 감사드립니다

groovedk님께서 말씀하신 js 파일현황입니다.

var fnObjPolicySetting = {
	pageStart: function(){
		myGrid.setConfig({
			targetID : "gridPolicySetting",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key: _상기 부분은 보안 상 생략_			},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_}
			],
			body : {
				marker: [
				{
					display: function () { return this.item.subTit ? true : false; },
					rows: [
						[{
							colSeq  : null, colspan: 6, formatter: function () {
								return this.item.subTit.name;
							}
						}]
					]
				}],
				onclick: function(){ fnObjModal._상기 부분은 보안 상 생략_(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5,
			}
		});
		myGrid.setList({
		    ajaxUrl:"_상기 부분은 보안 상 생략_",
		    headers:_headers,
			onLoad:function(){
//				$('#menu1').text(myGrid.page.listCount.number().money());
				$("#menu1").html("_상기 부분은 보안 상 생략_" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid.page.pageNo = 1;
		myGrid.page.pageSize = $("#pageSize1").val().number();
		myGrid.setList({
			ajaxUrl : "_상기 부분은 보안 상 생략_",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu1").html("_상기 부분은 보안 상 생략_" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

var myGrid2 = new AXGrid();
var fnObjPolicySetting2 = {
	pageStart: function(){
		myGrid2.setConfig({
			targetID : "gridPolicySetting2",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key: _상기 부분은 보안 상 생략_			},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_},
				{key:_상기 부분은 보안 상 생략_}
			],
			body : {
				marker: [
							{
								display: function () { return this.item.subTit ? true : false; },
								rows: [
									[{
										colSeq  : null, colspan: 6, formatter: function () {
											return this.item.subTit.name;
										}
									}]
								]
							}],
				onclick: function(){fnObjModal._상기 부분은 보안 상 생략_(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5
			}
		});
		myGrid2.setList({
		    ajaxUrl:"_상기 부분은 보안 상 생략_",
		    headers:_headers,
			onLoad:function(){
				$("#menu2").html("_상기 부분은 보안 상 생략_:" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid2.page.pageNo = 1;
		myGrid2.page.pageSize = $("#pageSize2").val().number();
		myGrid2.setList({
			ajaxUrl : "_상기 부분은 보안 상 생략_",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu2").html("_상기 부분은 보안 상 생략_" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

**Comment by groovedk** [comment]
body에 page 구조가 아래와 같습니다. 
```
page:{
        paging  : true, // {Boolean} -- 페이징 사용여부를 설정합니다.
        pageNo  : 1,    // {Number} -- 현재 페이지 번호를 설정합니다.
        pageSize: 100,  // {Number} -- 한 페이지장 표시할 데이터 수를 설정합니다.
        onchange: function(pageNo){} // {Funtion} -- 페이지 변경 이벤트입니다.
    },
```
onchange 부분을 수정해서 어떻게 이벤트가 전달되는지 확인해보세요

**Comment by gosumdochi** [comment]
AXGrid.js를 수정하여 문제를 자체 해결함
예시 : this.pagingUnit.find(".AXgridPagingPrev").unbind("click");
[AxisJ Grid는 다중으로 사용 시 원활한 작동을 보장할 수 없음]
