### ISSUE TITLE
AxisJ 그리드 2개 이상 사용 시 치명적인 버그 발생에 관한 이슈요청

### ISSUE THREAD

**Issue by gosumdochi** [axisj/axisj#890]
AxisJ 그리드를 한페이지에서 2개를 사용할 경우

■■■■■ 뷰 배치 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
---------------------------------
Grid 1
---------------------------------
Grid 2
---------------------------------

■■■■■ html 소스 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

<body tiles:fragment="body">

	<form id="form" name="form" method="post">
		<div class="floatArea">
			<div class="fl">
				<input class="w250" type="text"  placeholder="검색어 입력" id="searchText"/>
				<a href="javascript:search();"><img src="_보안생략_" title="검색" /></a>
			</div>
		</div>
		
		<div class="floatArea">
			<div class="fl">
				<div id="tool-bar" class="toolBar"></div>
			</div>
			
		</div>

		<div class="gridFolder">
			<div id="grid1" class="gridTit" onclick="javascript:openClose('gridPolicySetting');"><strong id="menu1">_보안생략_: </strong> </div>
			<div id="gridPolicySetting" class="gridBtLine"></div>
		</div>

		<div class="paging">
			<div class="pageCount">
				<select id="pageSize1" name="pageSize1" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
		
		<div class="gridFolder">
			<div id="grid2" class="gridTit" onclick="javascript:openClose('gridPolicySetting2');"><strong id="menu2">_보안생략_: </strong> </div>
			<div id="gridPolicySetting2" class="gridBtLine"></div>
		</div>
		
		<div class="paging">
			<div class="pageCount">
				<select id="pageSize2" name="pageSize2" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
		
		<div class="gridFolder">
			<div id="grid3" class="gridTit" onclick="javascript:openClose('gridPolicySetting3');"><strong id="menu3">URL/IP: </strong> </div>
			<div id="gridPolicySetting3" class="gridBtLine"></div>
		</div>
		
		<div class="paging">
			<div class="pageCount">
				<select id="pageSize3" name="pageSize3" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
	</form>

</body>
	<script type="text/javascript" th:inline="javascript">
	$(document.body).ready(function() {
		/*<![CDATA[*/
			
		/*]]>*/
		});
	</script>
</html>

■■■■■ JS 소스 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

var delImg = "<img src=\"보안생략" title=\"삭제\"  />";
var fnObjMneu = {
	pageStart: function(){this.toolbar.init();},
	toolbar: {
		target: new AXToolBar(),
		init: function(){
			var menu = [
				{
					label   : "추가", 
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}},
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}},
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}}
					],
					filter: function(){
						return true;
					}
				} ,
				{
					label   : "삭제",
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){delAll('1','보안생략','보안생략');}},
						{label: "보안생략", onclick: function(){delAll('2','보안생략','보안생략');}},
						{label: "보안생략", onclick: function(){delAll('3','보안생략','보안생략');}}
					]
				},
				{
					label   : "보안생략", 
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){EVENT.save();}},
						{label: "보안생략", onclick: function(){}},
						{label: "보안생략", onclick: function(){}}
					]
				},
				{
					label   : "보안생략",
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}},
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}},
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}}
					]
				}
			];

			var type = 0;
			this.target.setConfig({
				targetID: "tool-bar",
				theme   : "AXToolBar",
				menu    : menu,
				width: 100,
				reserveKeys: {
					subMenu: "menu"
				}
			});
		}
	}
};

//Grid - [MD5]
var myGrid = new AXGrid();
var fnObjPolicySetting = {
	pageStart: function(){
		myGrid.setConfig({
			targetID : "gridPolicySetting",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:delImg, width:"40",  align:"center", sort:false, formatter: function () {
						var delFormatter = "<img src=\"보안생략" title=\"삭제\" onclick = \"javascript:delPolicy('1','보안생략','" + this.item.name + "')\"  />";
	                    return delFormatter;
	                }
					},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
				{
					display: function () { return this.item.subTit ? true : false; },
					rows: [
						[{
							colSeq  : null, colspan: 6, formatter: function () {
								return this.item.subTit.name;
							}
						}]
					]
				}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5,
			}
		});
		myGrid.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
//				$('#menu1').text(myGrid.page.listCount.number().money());
				$("#menu1").html("보안생략:" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid.page.pageNo = 1;
		myGrid.page.pageSize = $("#pageSize1").val().number();
		myGrid.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu1").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Grid - [보안생략]
var myGrid2 = new AXGrid();
var fnObjPolicySetting2 = {
	pageStart: function(){
		myGrid2.setConfig({
			targetID : "gridPolicySetting2",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:delImg, width:"40",  align:"center", sort:false, formatter: function () {
						var delFormatter = "<img src=\"보안생략\" title=\"삭제\" onclick = \"javascript:delPolicy('2','보안생략','" + this.item.name + "')\"  />";
	                    return delFormatter;
	                }
					},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
							{
								display: function () { return this.item.subTit ? true : false; },
								rows: [
									[{
										colSeq  : null, colspan: 6, formatter: function () {
											return this.item.subTit.name;
										}
									}]
								]
							}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5
			}
		});
		myGrid2.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
				$("#menu2").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid2.page.pageNo = 1;
		myGrid2.page.pageSize = $("#pageSize2").val().number();
		myGrid2.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu2").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Grid - [보안생략]
var myGrid3 = new AXGrid();
var fnObjPolicySetting3 = {
	pageStart: function(){
		myGrid3.setConfig({
			targetID : "gridPolicySetting3",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:"<img src=\"보안생략"  />", width:"40",  align:"center", sort:false,
					tooltip: "삭제",
					formatter: function () {
							var aStr = '<a href="javascript:fnObj.deleteItem(' + this.index + ');">'
									+ '<img src="보안생략" /></a>';
							return aStr;
					}
				},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
				{
					display: function () { return this.item.subTit ? true : false; },
					rows: [
						[{
							colSeq  : null, colspan: 6, formatter: function () {
								return this.item.subTit.name;
							}
						}]
					]
				}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5,
		//		onchange:function(pageNo){}
			}
		});
		myGrid3.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
				$("#menu3").html("보안생략:" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid3.page.pageNo = 1;
		myGrid3.page.pageSize = $("#pageSize3").val().number();
		myGrid3.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu3").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Modal Popup
var pageID = "AXModal";
var myModal = new AXModal();
var fnObjModal = {
	pageStart: function(){
		myModal.setConfig({
			windowID:"myModalCT"
		});
	},
	denyEditMd5: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyEditCnc: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyEditUrl: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyAddMd5: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyAddCnc: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyAddUrl: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyImpt: function(){myModal.open({url:"보안생략", width:465, pars:"", closeByEscKey:true});},
	importModal: function(type) {
		myModal.open({
			url:"보안생략",
			width:432,
			pars:"type=".concat(type).queryToObject(), 
			closeByEscKey:true
		});
	}
};

$(document.body).ready(function(){
	setTimeout(fnObjPolicySetting.pageStart, 1); 
	setTimeout(fnObjPolicySetting2.pageStart, 1);
	fnObjModal.pageStart();
	fnObjMneu.pageStart();
	
	$("#searchText").keydown(function (event) {
		if(event.keyCode == 13){
			fnObjPolicySetting.search();
			fnObjPolicySetting2.search();
//			fnObjPolicySetting3.search();
		}
	});

	$( "#searchBtn" ).click(function() {
		fnObjPolicySetting.search();
		fnObjPolicySetting2.search();
//		fnObjPolicySetting3.search();
	});

	$( "#pageSize1" ).change(function() {
		fnObjPolicySetting.search();
	});
	
	$( "#pageSize2" ).change(function() {
		fnObjPolicySetting2.search();
	});
	
	$( "#pageSize3" ).change(function() {
		fnObjPolicySetting3.search();
	});
	
});

function delPolicy(index, gubun, name){
	if(confirm("삭제하시겠습니까?")){
		$.Event(event).stopPropagation(); // 버튼클릭 이벤트가 row click 이벤트를 발생시키지 않도록 합니다.
		var dataParam = Object.toJSON({"name" : name});
		var url = "보안생략" + gubun;
		$.ajax({
			url : url,
			type : "POST",
			dataType : "json",
			data :dataParam,
			contentType : "application/json; charset=UTF-8",
			success : function(data) {
				//data.result
				if(data.result == "fail"){
					alert(data.resultMessage);
				}else{
					if(index == '1'){
						fnObjPolicySetting.search();
					}else if(index == '2'){
						fnObjPolicySetting2.search();
					}else if(index == '3'){
						fnObjPolicySetting3.search();
					}
				}
			},
			error : function(request, status, error) {
				//console.log("request = "+JSON.stringify(request));
				alert($.fieldErrorMessage(request));
			}
		});
	}
}

function delAll(index, gubun, name){
	if(confirm(name+" 항목을 모두 삭제하시겠습니까?")){
		var dataParam = Object.toJSON({"name" : name});
		var url = "보안생략" + "보안생략"+ gubun;
		$.ajax({
			url : url,
			type : "POST",
			dataType : "json",
			data :dataParam,
			contentType : "application/json; charset=UTF-8",
			success : function(data) {
				//data.result
				if(data.result == "fail"){
					alert(data.resultMessage);
				}else{
					if(index == '1'){
						fnObjPolicySetting.search();
					}else if(index == '2'){
						fnObjPolicySetting2.search();
					}else if(index == '3'){
						fnObjPolicySetting3.search();
					}
				}
			},
			error : function(request, status, error) {
				alert($.fieldErrorMessage(request));
			}
		});
	}
}

function openClose(gridId){
	var grid = $("#"+gridId);
	if(grid.css("display") == "none"){
		grid.show();
	} else {
		grid.hide();
	}
}

var EVENT = {
		save : function(){
			$.ajax({
				url: '보안생략',
				type : 'post',
				data : JSON.stringify($("#form").serialize().queryToObject()),
				dataType : 'json',
				contentType : "application/json",
				success : function(result){
					if(result.result != "success"){
						alert(result.resultMessage);
					}
				},		
			});
		}
}

○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○

Grid1의 첫번째 row 와 loading bar 가 사라지는 현상이 발견되었습니다.
Grid2는 정상인데 유독 첫번째 Grid1만 다음과 같은 현상이 발견됩니다.
확인 부탁 드립니다!

**Comment by groovedk** [comment]
확인을 할 수 있는 소스를 주셔야지 확인이 가능합니다. 
이미지 반출이 어렵다고 하셨는데  아무것도 없으면 저희도 확인하기가 어렵습니다.
재현할 수 있는 시나리오라도 부탁드립니다.

**Comment by thomasJang** [comment]
아마도 그리드에 데이터를 채우실때 사용하는 변수가 참조가 양쪽에서 되면서 생기는 문제가 아닐까 싶습니다.

http://codepen.io/thomasJang/pen/reyNPZ 이런곳에서 코드 복제하신 후 샘플 코드를 작성해주시면 금방 문제를 해결 할 것 같습니다.

**Comment by gosumdochi** [comment]
groovedk 님 본문의 내용을 수정하도록 하겠습니다 !

**Comment by gosumdochi** [comment]
이거 본문에 js도 넣었는데 내용이 생략이 되네요

**Comment by gosumdochi** [comment]
■■■■■ 뷰 배치 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
---------------------------------
Grid 1
---------------------------------
Grid 2
---------------------------------

■■■■■ html 소스 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

<body tiles:fragment="body">

	<form id="form" name="form" method="post">
		<div class="floatArea">
			<div class="fl">
				<input class="w250" type="text"  placeholder="검색어 입력" id="searchText"/>
				<a href="javascript:search();"><img src="/static/images/_보안생략_" title="검색" /></a>
			</div>
		</div>
		
		<div class="floatArea">
			<div class="fl">
				<div id="tool-bar" class="toolBar"></div>
			</div>
			
		</div>

		<div class="gridFolder">
			<div id="grid1" class="gridTit" onclick="javascript:openClose('gridPolicySetting');"><strong id="menu1">_보안생략_: </strong> </div>
			<div id="gridPolicySetting" class="gridBtLine"></div>
		</div>

		<div class="paging">
			<div class="pageCount">
				<select id="pageSize1" name="pageSize1" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
		
		<div class="gridFolder">
			<div id="grid2" class="gridTit" onclick="javascript:openClose('gridPolicySetting2');"><strong id="menu2">_보안생략_: </strong> </div>
			<div id="gridPolicySetting2" class="gridBtLine"></div>
		</div>
		
		<div class="paging">
			<div class="pageCount">
				<select id="pageSize2" name="pageSize2" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
		
		<div class="gridFolder">
			<div id="grid3" class="gridTit" onclick="javascript:openClose('gridPolicySetting3');"><strong id="menu3">URL/IP: </strong> </div>
			<div id="gridPolicySetting3" class="gridBtLine"></div>
		</div>
		
		<div class="paging">
			<div class="pageCount">
				<select id="pageSize3" name="pageSize3" class="selBox">
					<option value="5">5개씩 보기</option>
					<option value="50">50개씩 보기</option>
					<option value="100">100개씩 보기</option>
				</select>
			</div>
		</div>
	</form>

</body>
	<script type="text/javascript" th:inline="javascript">
	$(document.body).ready(function() {
		/*<![CDATA[*/
			
		/*]]>*/
		});
	</script>
</html>

■■■■■ JS 소스 현황■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■

var delImg = "<img src=\"보안생략" title=\"삭제\"  />";
var fnObjMneu = {
	pageStart: function(){this.toolbar.init();},
	toolbar: {
		target: new AXToolBar(),
		init: function(){
			var menu = [
				{
					label   : "추가", 
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}},
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}},
						{label: "보안생략", onclick: function(){fnObjModal.denyAdd보안생략();}}
					],
					filter: function(){
						return true;
					}
				} ,
				{
					label   : "삭제",
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){delAll('1','보안생략','보안생략');}},
						{label: "보안생략", onclick: function(){delAll('2','보안생략','보안생략');}},
						{label: "보안생략", onclick: function(){delAll('3','보안생략','보안생략');}}
					]
				},
				{
					label   : "보안생략", 
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){EVENT.save();}},
						{label: "보안생략", onclick: function(){}},
						{label: "보안생략", onclick: function(){}}
					]
				},
				{
					label   : "보안생략",
					onclick : function (menu, event) {
						trace("1", menu);
					},
					menu    : [
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}},
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}},
						{label: "보안생략", onclick: function(){fnObjModal.importModal('보안생략');}}
					]
				}
			];

			var type = 0;
			this.target.setConfig({
				targetID: "tool-bar",
				theme   : "AXToolBar",
				menu    : menu,
				width: 100,
				reserveKeys: {
					subMenu: "menu"
				}
			});
		}
	}
};

//Grid - [MD5]
var myGrid = new AXGrid();
var fnObjPolicySetting = {
	pageStart: function(){
		myGrid.setConfig({
			targetID : "gridPolicySetting",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:delImg, width:"40",  align:"center", sort:false, formatter: function () {
						var delFormatter = "<img src=\"보안생략" title=\"삭제\" onclick = \"javascript:delPolicy('1','보안생략','" + this.item.name + "')\"  />";
	                    return delFormatter;
	                }
					},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
				{
					display: function () { return this.item.subTit ? true : false; },
					rows: [
						[{
							colSeq  : null, colspan: 6, formatter: function () {
								return this.item.subTit.name;
							}
						}]
					]
				}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5,
			}
		});
		myGrid.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
//				$('#menu1').text(myGrid.page.listCount.number().money());
				$("#menu1").html("보안생략:" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid.page.pageNo = 1;
		myGrid.page.pageSize = $("#pageSize1").val().number();
		myGrid.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu1").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Grid - [보안생략]
var myGrid2 = new AXGrid();
var fnObjPolicySetting2 = {
	pageStart: function(){
		myGrid2.setConfig({
			targetID : "gridPolicySetting2",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:delImg, width:"40",  align:"center", sort:false, formatter: function () {
						var delFormatter = "<img src=\"보안생략\" title=\"삭제\" onclick = \"javascript:delPolicy('2','보안생략','" + this.item.name + "')\"  />";
	                    return delFormatter;
	                }
					},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
							{
								display: function () { return this.item.subTit ? true : false; },
								rows: [
									[{
										colSeq  : null, colspan: 6, formatter: function () {
											return this.item.subTit.name;
										}
									}]
								]
							}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5
			}
		});
		myGrid2.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
				$("#menu2").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid2.page.pageNo = 1;
		myGrid2.page.pageSize = $("#pageSize2").val().number();
		myGrid2.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu2").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Grid - [보안생략]
var myGrid3 = new AXGrid();
var fnObjPolicySetting3 = {
	pageStart: function(){
		myGrid3.setConfig({
			targetID : "gridPolicySetting3",
			emptyListMSG: "항목이 존재하지 않습니다..",
			height:"auto",
			colGroup : [
				{key:"del",label:"<img src=\"보안생략"  />", width:"40",  align:"center", sort:false,
					tooltip: "삭제",
					formatter: function () {
							var aStr = '<a href="javascript:fnObj.deleteItem(' + this.index + ');">'
									+ '<img src="보안생략" /></a>';
							return aStr;
					}
				},
				{key:"보안생략",label:"보안생략", width:"260",sort:false},
				{key:"보안생략",label:"보안생략", width:"220",sort:false},
				{key:"보안생략",label:"보안생략", width:"120",sort:false},
				{key:"보안생략",label:"보안생략", width:"*",sort:false}
			],
			body : {
				marker: [
				{
					display: function () { return this.item.subTit ? true : false; },
					rows: [
						[{
							colSeq  : null, colspan: 6, formatter: function () {
								return this.item.subTit.name;
							}
						}]
					]
				}],
				onclick: function(){ fnObjModal.보안생략(this.c,this.item.name);}
			},
			page:{
				paging:true,
				pageNo:1,
				pageSize:5,
		//		onchange:function(pageNo){}
			}
		});
		myGrid3.setList({
		    ajaxUrl:"보안생략",
		    headers:_headers,
			onLoad:function(){
				$("#menu3").html("보안생략:" +"&nbsp;"+ this.page.listCount);
			}
		 });
	},
	search: function () {
		var ajaxPars = {searchText:$.trim($("#searchText").val())};
		myGrid3.page.pageNo = 1;
		myGrid3.page.pageSize = $("#pageSize3").val().number();
		myGrid3.setList({
			ajaxUrl : "보안생략",
			ajaxPars: ajaxPars,
			onLoad:function(){
				$("#menu3").html("보안생략" +"&nbsp;"+ this.page.listCount);
			}
		});
		return false;
	}
};

//Modal Popup
var pageID = "AXModal";
var myModal = new AXModal();
var fnObjModal = {
	pageStart: function(){
		myModal.setConfig({
			windowID:"myModalCT"
		});
	},
	denyEditMd5: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyEditCnc: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyEditUrl: function(c, name){
		if(c != 0) {
			myModal.open({url:"보안생략", width:462, pars:{id : name}, closeByEscKey:true});
		}
	},
	denyAddMd5: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyAddCnc: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyAddUrl: function(){myModal.open({url:"보안생략", width:432, pars:"", closeByEscKey:true});},
	denyImpt: function(){myModal.open({url:"보안생략", width:465, pars:"", closeByEscKey:true});},
	importModal: function(type) {
		myModal.open({
			url:"보안생략",
			width:432,
			pars:"type=".concat(type).queryToObject(), 
			closeByEscKey:true
		});
	}
};

$(document.body).ready(function(){
	setTimeout(fnObjPolicySetting.pageStart, 1); 
	setTimeout(fnObjPolicySetting2.pageStart, 1);
	fnObjModal.pageStart();
	fnObjMneu.pageStart();
	
	$("#searchText").keydown(function (event) {
		if(event.keyCode == 13){
			fnObjPolicySetting.search();
			fnObjPolicySetting2.search();
//			fnObjPolicySetting3.search();
		}
	});

	$( "#searchBtn" ).click(function() {
		fnObjPolicySetting.search();
		fnObjPolicySetting2.search();
//		fnObjPolicySetting3.search();
	});

	$( "#pageSize1" ).change(function() {
		fnObjPolicySetting.search();
	});
	
	$( "#pageSize2" ).change(function() {
		fnObjPolicySetting2.search();
	});
	
	$( "#pageSize3" ).change(function() {
		fnObjPolicySetting3.search();
	});
	
});

function delPolicy(index, gubun, name){
	if(confirm("삭제하시겠습니까?")){
		$.Event(event).stopPropagation(); // 버튼클릭 이벤트가 row click 이벤트를 발생시키지 않도록 합니다.
		var dataParam = Object.toJSON({"name" : name});
		var url = "보안생략" + gubun;
		$.ajax({
			url : url,
			type : "POST",
			dataType : "json",
			data :dataParam,
			contentType : "application/json; charset=UTF-8",
			success : function(data) {
				//data.result
				if(data.result == "fail"){
					alert(data.resultMessage);
				}else{
					if(index == '1'){
						fnObjPolicySetting.search();
					}else if(index == '2'){
						fnObjPolicySetting2.search();
					}else if(index == '3'){
						fnObjPolicySetting3.search();
					}
				}
			},
			error : function(request, status, error) {
				//console.log("request = "+JSON.stringify(request));
				alert($.fieldErrorMessage(request));
			}
		});
	}
}

function delAll(index, gubun, name){
	if(confirm(name+" 항목을 모두 삭제하시겠습니까?")){
		var dataParam = Object.toJSON({"name" : name});
		var url = "보안생략" + "보안생략"+ gubun;
		$.ajax({
			url : url,
			type : "POST",
			dataType : "json",
			data :dataParam,
			contentType : "application/json; charset=UTF-8",
			success : function(data) {
				//data.result
				if(data.result == "fail"){
					alert(data.resultMessage);
				}else{
					if(index == '1'){
						fnObjPolicySetting.search();
					}else if(index == '2'){
						fnObjPolicySetting2.search();
					}else if(index == '3'){
						fnObjPolicySetting3.search();
					}
				}
			},
			error : function(request, status, error) {
				alert($.fieldErrorMessage(request));
			}
		});
	}
}

function openClose(gridId){
	var grid = $("#"+gridId);
	if(grid.css("display") == "none"){
		grid.show();
	} else {
		grid.hide();
	}
}

var EVENT = {
		save : function(){
			$.ajax({
				url: '보안생략',
				type : 'post',
				data : JSON.stringify($("#form").serialize().queryToObject()),
				dataType : 'json',
				contentType : "application/json",
				success : function(result){
					if(result.result != "success"){
						alert(result.resultMessage);
					}
				},		
			});
		}
}

○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○○

Grid1의 첫번째 row 와 loading bar 가 사라지는 현상이 발견되었습니다.
Grid2는 정상인데 유독 첫번째 Grid1만 다음과 같은 현상이 발견됩니다.
확인 부탁 드립니다!

**Comment by gosumdochi** [comment]
thomasJang 님 답변 감사드립니다 알려주신 주소의 코드를 복사해서 테스트 해보는 것은 제가 처음 해보는 것이라서 시간이 조금 걸릴 것 같습니다 ! 답변 감사합니다 !

**Comment by gosumdochi** [comment]
AXGrid.js를 수정하여 문제를 자체 해결함
예시 : this.pagingUnit.find(".AXgridPagingPrev").unbind("click");
[AxisJ Grid는 다중으로 사용 시 원활한 작동을 보장할 수 없음]
