### ISSUE TITLE
AXGrid 에서 mergeCells 예제에서 셀 병합시 배경색이 전부 채워지지 않음

### ISSUE THREAD

**Issue by hyunmoo** [axisj/axisj#893]
AXGrid 에서 mergeCells 예제 에서

    <style type="text/css">
  		.gridcolor {background-color:#FFE08C;font-weight:bold;}
    </style>

css 추가

{key:"writer", label:"작성자", width:"100"} 을 다음으로 변경

{key:"writer", label:"작성자", width:"100", addClass: function (){return "gridcolor";}}

mergeCells: [2] 로 설정

https://dl.dropboxusercontent.com/u/171216501/12321321321321321321.JPG

변경하면 병합된 셀에 배경색이 전부 채워지지 않는 현상이 있습니다.

병합되면 문자가 있는 한줄만 배경색이 변경됨...

병합된 셀에 전부 색을 채우려면 어떻게 해야합니까?

**Comment by lhslive** [comment]
뭔가 확실한 해결책은 아니지만.. 저는 css에 
height:99%;를 줘서 그냥 쓰고 있습니다.
```
<style type="text/css">
    .gridcolor {background-color:#FFE08C;font-weight:bold;height:99%;}
</style>
```

**Comment by hyunmoo** [comment]
좋은 정보 감사합니다.
