### ISSUE TITLE
AXGrid 에서 스타일 추가시 글자색 변경문의

### ISSUE THREAD

**Issue by hyunmoo** [axisj/axisj#896]
css 추가
.gridcolor {color:red;font-weight:bold;}

AXGrid  초기화시

colGroup:[
{key:"PRO_NM", label:"공정", width:"50", align:"center", addClass: function (){return "gridcolor ";}}]

구문을 추가하여

글자색을 변경하려고 하였으나 글자색 변경이 반영되지 않았습니다.

font-color:red; 로 바꿔보아도 글자색 변경이 되지 않았습니다.

스타일 추가시 글자색 변경 문의 합니다.

**Comment by lhslive** [comment]
그리드 생성시 우선되는 클래스에 의해서 color 속성이 무시되어서 그런데요..
```
.gridcolor {
  color:red !important;
  font-weight:bold;
}
```
이처럼 속성을 강제 해 주세요.

**Comment by hyunmoo** [comment]
감사합니다. 잘되네요!
