### ISSUE TITLE
AXGrid 에서 ajaxPars 에 값 전달 안되는 현상 문의

### ISSUE THREAD

**Issue by freecatz** [axisj/axisj#900]
myGrid.setList({
	                ajaxUrl : "/AM/course/operate/list/search",
	                ajaxPars: {
	                    "si":  $("#si ").val(),
	                    "gungu": $('#gungu').val(),
	                    "start_date": $('#start_date').val(),
	                    "end_date": $('#end_date').val()
	                },
	                onLoad  : function(){
	                }
	            });

조회시 UI 개체의 값을 바로 참조 하여 조회를 하고 싶은데, "si":  $("#si ").val() 와 같이 사용 하면 안되는 것인지 궁금 하니다. 특히 Date 형식의 UI 개체의 경우 값을 변경 하여도 도큐먼트가 로드된 당시의 값을 참조 하여 서버로 전송 합니다.

조언 부탁 드리겠습니다.

**Comment by lhslive** [comment]
#895  여기 답변을 참고 해 보세요..

다른 형태의 문제이면 다시 답글 남겨 주세요

**Comment by freecatz** [comment]
lhslive 님, 더운 날씨에 답변 감사합니다.

![grid](https://cloud.githubusercontent.com/assets/14190414/17312817/9bbdb08e-5890-11e6-8561-74134effca42.png)

우선 위의 그림과 같이 파란색 영역이 html 폼 요소 이며, 조회 조건에 해당 합니다.

아래의 붉은 영역은 그리드 영역 입니다. 조회 조건 영역의 값들을 서버에 던져주고 싶은 마음에 

myGrid.setList({
                ajaxUrl : "/AM/course/operate/list/search",
                ajaxPars: {
                    "si":  $("#si ").val(),                           // 서버에 던져줄 조회 조건(html폼의 값)
                    "gungu": $('#gungu').val(),              // 서버에 던져줄 조회 조건(html폼의 값) 
                    "start_date": $('#start_date').val(),    // 서버에 던져줄 조회 조건 (html폼의 값)
                    "end_date": $('#end_date').val()      // 서버에 던져줄 조회 조건 (html폼의 값)
                },
                onLoad  : function(){
                }
            });

위와 같이 작성 하였습니다. 조회 조건의 UI 개체에서 조회 조건의 값을 선택 하고 조회를

하였습니다. 그리고 서버의 스프링 컨트롤러의 받은 파라메터의 값을 찍어 보면 아래와 같이 

나타납니다.


===================>CourseListSDto(pageNo=1, listCount=0, pageSize=100, si=, gungu=, manager=, category_name=, sort=on, status=on, start_date=2016-07-26, end_date=2016-08-02)


값들이 안가려고 한다면 모두다 안가는게 정상이라고 생각 됩니다만...

어떤 값들은 서버에 전달이 되고, 어떤 값들은 전달이 되지 않은 상태 입니다.

그리고 조회 조건의 날짜 부분은 서버로 전송이 되었지만,  제가 선택한 값이 아닌 초기에 설정된

값이 전달이 되었습니다.


위와 같은 현상에 있습니다. 조언 부탁 드리겠습니다.

더운 날씨에 고생이 많으십니다.

**Comment by lhslive** [comment]
아 제가 다른 문제로 잘못 이해 했나 봅니다.

질문 주신걸 보니까.. 위 검색 옵션 지정하는  부분은 다른 컴포넌트를 쓰시는 건가요?..

해당 컨트롤 들의 값이 혹시 페이지 렌더링 시에 서버쪽에서 디폴트로 박아 주는 값들이 있나요?..

화면상의 값을 못가져 가는거 같고 그 값들만 들고 가는거 같네요.

브라우저 f12 를 누르셔서 콘솔 메세지나 각 요소들의 id나 name등을 확인 해 보시는것도 좋을 것 같습니다.

**Comment by freecatz** [comment]
lhslive 님, 답변 주셔서 감사합니다.

말씀 주신 부분을 확인해 보았습니다.

랜더링시 서버쪽에서 값을 박아 주는 부분이 있었습니다.

myGrid.setList() 를 외부로 빼 내어 해결을 하였습니다.


var myGrid = new AXGrid();
	var fnObj = {
	        pageStart: function(){
	            myGrid.setConfig({
                      .... 중략...
	    };  // var fnObj 

/* ajax를 이용하여 그리드 내용 조회 */
	function ajaxSearch(){
		myGrid.setList({
	        ajaxUrl : "/AM/course/operate/detail_st/search",
	        ajaxPars: {
	            "status": $(':radio[name="status"]:checked').val(),
	            "stype":  $('#stype option:selected').val(),
	            "stext":  $('#stext').val()
	        }
	    });
    } // function ajaxSearch

깃헙 사용이 익숙지 않아 코드를 이쁘게 넣고 싶은데 잘 안네요.

우선 해결 완료 처리 하도록 하겠습니다.

감사합니다.

**Comment by freecatz** [comment]
메일 주셔서 감사합니다. 
 
어제 저녁에 문제가 해결 되었습니다. 오늘 아침에 이슈 클로즈 시켰는데, 맞게 했는지 모르겠습니다.
 
깃헙을 자주 이용하지 않아 아직 많이 부족 합니다.
 
조회 영역은 다른 컴포넌트가 아닌 순수 html 을 이용한 개체들 입니다.
 
그리고 문제가 된 부분은 말씀하신것과 같이 서버쪽에서 값을 박아 내려 주는 부분이 일차적으로 문제가 되었습니다.
 
이 부분을 인지 하지 못하고 저의 경우 fnObj 내부에 정의된 myGrid.setList() 를 외부로 빼 내어 해결을 하였습니다.
 
	&lt;script type="text/javascript"&gt;	
	
	var myGrid = new AXGrid();
	var fnObj = {
	        pageStart: function(){
	            myGrid.setConfig({
                           .... 중략 ...
      }; // var fnObj 
 
 
	/* ajax를 이용하여 그리드 내용 조회 */
	function ajaxSearch(){
		myGrid.setList({
	        ajaxUrl : "/AM/course/operate/detail_st/search",
	        ajaxPars: {
	            "status": $(':radio[name="status"]:checked').val(),
	            "stype":  $('#stype option:selected').val(),
	            "stext":  $('#stext').val()
	        }
	    });
    } // function ajaxSearch
 
 
 
    $(document).ready(function (){		
		fnObj.pageStart();
		ajaxSearch();
    });
	
     &lt;/script&gt; 
 
 
 
 
-----Original Message-----

**Comment by lhslive** [comment]
이슈는 close 됐습니다. 
잘 쓰시네요~
코드는 
위 아래를 요 글자 "```" 로 감싸시면 됩니다.
