### ISSUE TITLE
AXGrid 안에 포함된 AXdate의 separator를 일괄적으로 변경하는 방법?

### ISSUE THREAD

**Issue by misocap** [axisj/axisj#901]
![default](https://cloud.githubusercontent.com/assets/20658983/17314491/d3ee14ee-589f-11e6-9cc1-7be8514dd35b.PNG)

기존에 올려진 이슈에서도 찾아보고, API도 보았는데 방법을 못 찾아서ㅠㅠ 올려봅니다. 

AXGrid에서 AXInput의 AXdate 형태를 사용할때, separator를 '.'으로 일괄변경하고 싶은데...
어떻게 변경할 수 있는지요?
bindDate 함수를 쓰면 되는 것은 알겠는데, AXGrid 안에 포함된 경우에 일괄적으로 셋팅할 수 있는 방법이 있는 지요?

감사합니다!!!

**Comment by lhslive** [comment]
http://dev.axisj.com/samples/AXGrid/misc.html 여기를 참조해서 진행 하고 계시는 건가요?..

아래는 해당 페이지의 소스 일부분 입니다.

여기서도 각 요소에 bindDate를 해 주고 있습니다. 
```
                    onchangeScroll: function(){
                        //trace(this);
                        for(var i=this.startIndex;i<this.endIndex+1;i++){
                            $("#AXdate_"+i).bindDate({align:"right", valign:"top",
                                onchange:function(){
                                    trace(this.objID);
                                    var myi = this.objID.substr(this.objID.lastIndexOf("_").number()+1);
                                    myGrid.list[myi].regDate = this.value;
                                }
                            });
                        }
                    }
```
http://jdoc.axisj.com/jQueryExtends.html#.bindDate 여기를 참고 해 보시구요
```
                    onchangeScroll: function(){
                        //trace(this);
                        for(var i=this.startIndex;i<this.endIndex+1;i++){
                            $("#AXdate_"+i).bindDate({align:"right", valign:"top",separator : ".", 
                                onchange:function(){
                                    trace(this.objID);
                                    var myi = this.objID.substr(this.objID.lastIndexOf("_").number()+1);
                                    myGrid.list[myi].regDate = this.value;
                                }
                            });
                        }
                    }
```
이런 형태가 되겠네요.

**Comment by thomasJang** [comment]
```js
$("#AXInputDate").bindDate({align:"right", valign:"bottom", separator:"/", defaultSelectType:"m", onchange:function(){
                toast.push(Object.toJSON(this));
            }});
```

에서와 같습니다.

**Comment by misocap** [comment]
네! 빠르게 답변해 주셔서 너무 감사드려요. 
그런데 올려주신 방법으로도 이미 해봤고, API도 다 찾아보기는 했어요..
 
제 소스가 잘못된 건가 싶어서... 
다운로드받은 sample 예제 misc.html 소스에서 
onchangeScroll 부분에 separator만 추가해서 돌려봤는데...
바뀌지 않더라구요. ㅠㅠ  무엇이 잘못된 것일까요? 

따로 함수를 만들어서 bindDate를 해줘도 날짜형식이 안 바뀌는 것 같아요. 

` 
setAXDate : function() {
      for(var i=0;i<20+1;i++){
          $("#AXdate_"+i).bindDate({align:"right", valign:"top", seperator:"."}).val(print("yyyy.mm.dd") );
          trace("test" + i);
      }
`

이렇게 함수를 만들어서 호출해줘도 형식이 바뀌지는 않더라구요. 
AXGrid안에 포함된 AXdate 말고, 독립으로 AXdate를 만들어주고, 형식을 바꾸면 잘되는데...
AXGrid안에 포함된 경우에는 형식이 바뀌지 않는 것 같아서요...

(최대한 찾아본다고 찾았는데, 
이것과 비슷한 케이스를 찾지를 못해서 이렇게 글을 올리게 되었네요ㅠㅠ)

**Comment by lhslive** [comment]
```
                    onchangeScroll: function(){
                        //trace(this);
                        for(var i=this.startIndex;i<this.endIndex+1;i++){
                            $("#AXdate_"+i).bindDate({align:"right", valign:"top", separator: ".",
                                onchange:function(){
                                    trace(this.objID);
                                    var myi = this.objID.substr(this.objID.lastIndexOf("_").number()+1);
                                    myGrid.list[myi].regDate = this.value;
                                }
                            });
							  
                        }
                    }
```
그리고.. list에서 던져 주실때 ("yyyy.mm.dd") 형태로 주셔야 합니다.

가지고 오실때 힘드시면 Grid colGroup 선언 시 formatter 로 지정 해 주세요..
![k-005](https://cloud.githubusercontent.com/assets/7547764/17318018/07b7149c-58be-11e6-87af-387272f5292f.jpg)

**Comment by misocap** [comment]
빠르고 친절한 답변 너무 감사드려요. 

가르쳐주신대로 변경하여서 화면처럼 나오기는 했는데, 
문제는 달력아이콘을 눌러서 날짜를 세로 셋팅하려고 하면 
다시 yyyy-mm-dd 형태로 형식이 바뀐다는 것이에요. 

![default](https://cloud.githubusercontent.com/assets/20658983/17351525/690253b8-596a-11e6-956f-3f06f5cccdd2.PNG)

misc.html 소스에서 list내용과 말씀해주신 onchangeScroll에 onchange 함수 부분을 변경했습니다.

**Comment by lhslive** [comment]
...그리드 셋팅하신부분이랑 list 데이터 일부분을 좀 볼 수 있을까요?

**Comment by misocap** [comment]
코트 첨부하는 것이 제대로 안 나와서..(제가 방법을 제대로 모르나봐요..)
ㅠㅠ 압축을 했어요. 

[misc.zip](https://github.com/axisj/axisj/files/398652/misc.zip)

**Comment by lhslive** [comment]
...이제보니 오타가 있었네요
separator 가 아니라 seperator
아이고...ㅠㅠ

**Comment by misocap** [comment]
아... 근데 저는 seperator로 했어요. 
올려드린 소스도 seperator로 했는데도 형식이 잘 안 바뀌던데...
제가 뭔가 잘 모르고 하고 있는 것일까요? ㅠㅠ

**Comment by lhslive** [comment]
반대로 말씀드렸네요

소스에 열어 보시구요 seperator - > separator  로 변경하고 해보세요.

날씨가 많이 덥네요. 제 뇌도 써멀 구리스를 좀 쳐야겠습니다.

**Comment by misocap** [comment]
아~~~~~~~~~~~~~~~~~~~~~~~~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ㅠㅠㅠㅠ
날씨가 너무 더워서 그런가요...ㅠㅠ
정말 감사하고 죄송합니다!ㅠㅠㅠㅠㅠㅠㅠㅠㅠ
