### ISSUE TITLE
AXTree 에서 각 node마다 글자색을 다르게 주고 싶습니다. 

### ISSUE THREAD

**Issue by minami87** [axisj/axisj#902]
AXTree를 이용하여 Tree 기능을 제공할 때, 모든 node의 글자색이 기본색으로 출력되고 있습니다.
조건에 따라서 어느 경우에는 빨강색, 파랑색 등의 다른 글자색으로 출력해주고 싶습니다.

formatter function으로 출력되는 node 명의 앞뒤에 <font color="red">this.item.treeName</font> 와 같이 조합하여 return시켜보았으나, 해당 태그가 적용되지 않음을 확인하였습니다.

적용할 수 있는 방안이 있을까요?

**Comment by lhslive** [comment]
colGroup 설정 할때 
```
{key:"no", label:"코드", width:"60", align:"left",formatter:function(){ return "<u class='red'>" + this.item.no + "</u>";}},
```
이런 형태로 선언 해 주시고 ..

css 클래스를 적용 해 주세요.
![k-006](https://cloud.githubusercontent.com/assets/7547764/17321630/8bad7fa0-58d4-11e6-8a59-0aba4c12fe32.jpg)

**Comment by hyunjun19** [comment]
colGroup과 body에 addClass 함수를 사용하실 수 있습니다.

colGroup
```js
{
    key:"no",
    label:"코드",
    width:"60",
    align:"left",
    addClass: function(){ return "red";}},
    ...
},
```

body
```js
body: {
    addClass: function(){ return "red";}}
}
```
