### ISSUE TITLE
AXUpload5에서 삭제한 첨부파일을 다시 올릴 경우 선택이 안됩니다.

### ISSUE THREAD

**Issue by DaeHyeon-Kim** [axisj/axisj#903]
AXUpload5에서 삭제한 첨부파일을 다시 올릴 경우 선택이 안됩니다.
해결 방법이 있나요?

**Comment by thomasJang** [comment]
버그 패치 되었습니다. 깃에 있는 소스를 받으시면 해결됩니다.

https://github.com/axisj/axisj/commit/32300d357fe22c731655070a47b2e5841da498b1

**Comment by DaeHyeon-Kim** [comment]
다중업로드는 정상적으로 작동합니다.
그런데 single Mode로 하면 파일 첨부하면서 삭제 확인창이 뜹니다....
확인좀 해주실 수 있나요?

**Comment by DaeHyeon-Kim** [comment]
일단 소스 분석해보고 수정했는데 이렇게 해도 되는건가요?
아래 수정된 부분이라는 곳에 추가한 파일이 0개일 경우 리턴하도록 해놓았습니다.
정상 작동은 되는거 같은데 다른곳에 영향이 갈 수도 있을거 같아서 여쭤봅니다.

onFileSelect: function (evt) {
        var cfg = this.config, _this = this;
        if (this.supportHtml5) {
            var files = evt.target.files; // FileList object
            if (cfg.isSingleUpload) {

                var myFile = this.uploadedList.first();
                
                console.log("files ==== " , files);
                console.log("myFile ==== " , myFile);
                //수정된 부분============
                if(files.length == 0) return;
                //수정된 부분============
                if (myFile) {
                    this.__tempFiles = files[0];
                    if (!confirm(AXConfig.AXUpload5.deleteConfirm)) return;

**Comment by thomasJang** [comment]
코드 주신 부분 적용 했습니다. 감사합니다.
