### ISSUE TITLE
AXModal.openNew 새창이 안뜨네요.

### ISSUE THREAD

**Issue by cococl** [axisj/axisj#905]
http://dev.axisj.com/samples/AXModal/index.html 에서 새창열기하면

빈창이 하나 뜨고 탭형식으로 처리됩니다. ie11에서 테스트 했구요

**Comment by thomasJang** [comment]
AXModal 내부에서 
```
window.open("", (http.name || this.winID), http.options);
```

후에 
```
"<form target='" + (http.name || this.winID) + "'>"
```
을 서브밋 하고 있습니다.
ie11 에서 이 구문이 작동 하는지 확인이 필요한데요. 개발환경이 없어서. 한번 해보실 수 있을까요?

**Comment by lhslive** [comment]
열리긴 합니다.

에러난 창으로 열릴뿐이에요.

win10 + ie11 입니다.

![k-022](https://cloud.githubusercontent.com/assets/7547764/17577789/ce273daa-5fbc-11e6-8070-a233b47fe3a2.jpg)

**Comment by cococl** [comment]
리부팅하니 돼네요. PC가 맛탱이 갔었나봐요~
