### ISSUE TITLE
AXGrid 행 높이 수정

### ISSUE THREAD

**Issue by jasonseok** [axisj/axisj#910]
안녕하세요  AXGrid 를 적용해보고 있는데 header 의 경우에는 colHead 에서 height 속성을 줄 수 있는 것  같은데 혹시 body의 경우에도 height 를 설정할 수 있는지 문의드립니다. 감사합니다.

**Comment by thomasJang** [comment]
body의 높이는 CSS를 변경하여 조절할 수 있습니다.
