### ISSUE TITLE
AXGrid 페이징에 콤보박스가 동작하지 않습니다.

### ISSUE THREAD

**Issue by hodong-seok** [axisj/axisj#915]
예제 페이지 http://dev.axisj.com/samples/AXGrid/ajax.html에 
페이징 부분에 콤보박스가 동작하지 않습니다.

**Comment by thomasJang** [comment]
버그 리포트 감사합니다. 최신버전에 수정반영 했습니다.
AXSelect의 탭 포커스 관련 하여 이벤트처리 방식을 변경 하여 발생한 문제 였습니다.
릴리즈를 올렸으니 최신버전을 사용하시면 문제가 발생하지 않겠습니다.
