### ISSUE TITLE
div width 값 및 위치가 동적으로 변경될 시, selector 위치가 고정됨으로 인해 발생하는 문제 

### ISSUE THREAD

**Issue by minami87** [axisj/axisj#921]
bindSelector 를 이용해 select 데이터를 출력합니다. 

첨부한 이미지 파일과 같이 화면이 좌우로 분할되어 drag 기능을 통해 
좌우의 영역을 조정할 수 있습니다.
최초의 화면 loading 시에는 첨부한 테스트절차 이미지와 같이 정상 적으로 select 데이터가 출력되나,

drag 기능을 통해 화면의 좌측 영역을 늘린 후에는 
테스트결과 이미지와 같이 select 데이터가 최초 loading 시에 지정된 위치에서 출력됩니다.

해당 issue에 대한 답변 부탁드립니다. 
 
![_](https://cloud.githubusercontent.com/assets/20788908/18043604/e21a43e8-6e03-11e6-9a47-3aa8ee559e27.jpg)

![_](https://cloud.githubusercontent.com/assets/20788908/18043574/be1483a0-6e03-11e6-92a1-a9c320f2788d.jpg)

**Comment by thomasJang** [comment]
레이 크기가 변경될 때 마다
```js
AXSelect.alignAllAnchor();
// 또는
$(window).resize();
```
하세요.
