### ISSUE TITLE
AXGrid 에서 height: auto 일때 IE에서 선택은 되지만, 포커스는 그리드 맨 위로 올라갑니다.

### ISSUE THREAD

**Issue by Happy2You** [axisj/axisj#926]
가. IE에서 발생 (크롬은 잘 됨) ,

나. 그리드 height: auto 이고, 리스트가 좀 많을때 다 보려면 휠로 좀 내려야 할 정도..

다. inline-edit 에서 해당 값을 수정 하려고 클릭하면..

라. 크롬에서는 해당 값을 수정할수 있도록 텍트스박스가 선택되지만.. 

마. IE에서는 해당 인라인 텍스트박스가 선택은 되지만, 포커스가 그리드 맨 상단으로 가버립니다. 

바. 그래서 선택한 값을 수정하려면 휠을 내려서 해당 텍스트박스를 확인후에 수정을 하여야 합니다.

사. height: auto 를 삭제하고 스크롤 모드로 그리드를 바꾸면 이런 증상은  IE에서도 나오지 않습니다. 

고생하시는데....작은 도네이션도 못 해드리니.. 늘 마음의 짐을 안고 가는것 같습니다. ㅠㅠ 
도움은 못 드리고 문의와 버그제보만 드리네요..

늘 감사하는 마음으로 엑시스제이를 쓰고 있습니다.
감사합니다.

**Comment by ryuda** [comment]
AXGrid.js 파일 

        //keydown 이벤트 방식 변경
        this.target.bind("click.axgrid", (function (e) {
            if (this.editorOpend || this.inline_edit) return;
            var e = e || window.event;
            if (e.target.tagName == "INPUT" || e.target.tagName == "SELECT" || e.target.tagName == "TEXTAREA" || e.target.tagName == "BUTTON") return;
            //this.gridFocus.focus();
        }).bind(this));

this.gridFocus.focus();
주석처리하시면 되십니다.

**Comment by Happy2You** [comment]
고맙습니다!! ^^
