### ISSUE TITLE
footer 에 addClass 적용

### ISSUE THREAD

**Issue by jasonseok** [axisj/axisj#938]
안녕하세요 footer 의 특정 셀에 addClass 를  적용하려 하는데 혹시 방법이 있을까요?

**Comment by lhslive** [comment]
addClass 는 footer에는 적용이 안될듯 합니다.

'gridid'_AX_footText_AX_'rowindex'_AX_'colseq'  로 아이디가 생성되니 접근해서 활용 해 보세요.

**Comment by jasonseok** [comment]
넵 감사합니다.
