### ISSUE TITLE
차트 DB연동 관련 질문드립니다

### ISSUE THREAD

**Issue by HyeyeonLee** [axisj/axisj#947]
안녕하세요!! 차트 연동하던 중 문의남깁니다

일단 차트는 chart.js 다운받아 사용하고 있습니다 

그리드는 json 형식에 맞추어 list 에 담으면 setlist 에서 출력해주잖아요~~

차트는 어떤식으로 출력해야할까요.. ㅠㅠ 관련 함수가 있는지요

확인부탁드려요!!!

환절기 감기 조심하세요~~

**Comment by lhslive** [comment]
http://www.chartjs.org/docs/#getting-started

여기서 보시고 필요한 차트 표현식에 맞는 데이터를 직접 가공하세요.

**Comment by HyeyeonLee** [comment]
데이터는 직접 가공했고

chart:{
			Doughnut: function(){
		        var pars = fnObj.search.target.getParam();
		        
				new AXReq("list_data_doug.jsp", {
	                method: "POST", 
	                pars: pars,
	                onsucc:function(res){
	                    var data = {
	                    		dataD: res.dataD
	                    };
	                  
						trace(res.dataD);	                    
	                    var ctx = document.getElementById("chart-canvas-doughnut").getContext("2d");
	    				var chart = new Chart(ctx).Doughnut(res.dataD
	    						, {
	    					responsive : true
	    				});    
	                    
	                    
	                }
	            });

		        
	            return false;
			}

이 방식으로 연동했습니다~~ 잘되는거같은데 맞는거겠죠? 답변감사드립니다^_^

**Comment by lhslive** [comment]
원하시는 결과물이 보인다면 잘 하신거겠죠 ?

chart.js는 외부 컴포넌트입니다~.

axisj내부 기능이 아니에요~
