### ISSUE TITLE
grid 에서 행을 추가하고 저장시 오류 관련

### ISSUE THREAD

**Issue by jasonseok** [axisj/axisj#948]
안녕하세요 
grid 에서 행을 추가하고 Save  버튼 클릭시 ReferenceError: obj is not defined 스크립트 오류가 나고 서버 쪽 요청이 되지 않습니다. 
AXGrid.js 의 8698~8705 라인에 해당하는 아래 내용을 주석처리하면 서버 쪽으로 요청이 정상적으로 이루어지는데 어떤 이유 때문인지 궁금합니다. 
            /*

```
        if (Object.isString(obj.ajaxPars)) {

            formPars.push(obj.ajaxPars);

        }

        else if (Object.isObject(obj.ajaxPars)) {

            formPars.push(axdom.param(obj.ajaxPars));

        }

        */
```

**Comment by hyunjun19** [comment]
호출하는 코드를 보여주세요.

**Comment by jasonseok** [comment]
코드는 아래와 같습니다. 
appendGrid 메소드 호출시 입력화면 레이어에서 값을 입력하고 Save버튼을 누르면 스크립트 에러가 뜹니다. request,response 설정을 아예 빼면  스크립트 오류는 없으나 목적이 건 단위로 Save 할때 마다 서버에 요청하여 저장하는 것입니다. 

<script>
    var page34Grid1 = new AXGrid();
    var objPage34 = {
    	appendGrid: function(){
            var data = {emp_nm:"","cst_nm":"","con_mon":"","col_mon":"","pkg_nm":"","con_amt":0,"cancel_amt":0,"cancel_desc":""};
            page34Grid2.appendList(data);
      },
      pageStart: function(){
        page34Grid2.setConfig({
           targetID : "page34_grid2",
           height:"auto",
           theme : "AXGrid",
           colHeadAlign: "center",
           colGroup : [
               {key:"emp_nm",label:"담당자",width:"100"},
               {key:"cst_nm",label:"거래처",width:"150"},
               {key:"con_mon",label:"계약월",width:"100"},
               {key:"col_mon",label:"수금월",width:"100"},
               {key:"pkg_nm",label:"제품명",width:"150"},
               {key:"con_amt",label:"계약금액",width:"80",align:"right"},
               {key:"cancel_amt",label:"취소금액",width:"80",align:"right"},
               {key:"cancel_desc",label:"취소사유",width:"300"}
           ],
           colHead : {
             heights: [30],
               rows: [
                       [
                         {key:"emp_nm"},
                         {key:"cst_nm"},
                         {key:"con_mon"},
                         {key:"col_mon"},
                         {key:"pkg_nm"},
                         {key:"con_amt"},
                         {key:"cancel_amt"},
                         {key:"cancel_desc"}
                       ]
                    ],
               onclick: function(){
                   //toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, colHead:this.colHead, page:this.page}));
               }
           },
           body : {
               marker: function(){
                   
               },
               onclick: function(){
                   //toast.push(Object.toJSON({index:this.index, r:this.r, c:this.c, item:this.item}));
                   //alert(this.list);
                   //alert(this.page);
               }
           },
           page:{
               display:false
           },
           editor:{
             rows:[
               [
                 {colSeq:0,form:{type:"text",value:"itemValue",validate:function(){return true;}},AXBind:{type:"selector"}},
                 {colSeq:1,form:{type:"text",value:"itemValue"}},
                 {colSeq:2,form:{type:"text",value:"itemValue"},AXBind:{type:"date",config:{selectType:"m"}}},
                 {colSeq:3,form:{type:"text",value:"itemValue"},AXBind:{type:"date",config:{selectType:"m"}}},
                 {colSeq:4,form:{type:"text",value:"itemValue"}},
                 {colSeq:5,form:{type:"text",value:0},AXBind:{type:"money"}},
                 {colSeq:6,form:{type:"text",value:0},AXBind:{type:"money"}},
                 {colSeq:7,form:{type:"text",value:"itemValue"}}
               ]
             ],
             request:{
               ajaxUrl : "/data/append.do",
               ajaxPars : ""
             },
             response:function(){

             }
           }
       });
     }
 };
</script>

**Comment by hyunjun19** [comment]
https://github.com/axisj/axisj/tree/issue-948
https://github.com/axisj/axisj/commit/ecc5d6dea93a0df75627f18c82936ed4e20d5d1c

제가 커밋한 부분을 적용해서 테스트 해보시겠어요?

만약 해결되면 꼭 알려주세요. ;)

**Comment by jasonseok** [comment]
안녕하세요... 답변 감사합니다. 우선 위에 수정하신 내역대로 적용을 하니 서버쪽으로 정상적으로 요청이 되었습니다.  다만 request 설정을 하지 않았을 때 처럼 그리드에 행이 추가되지는 않던데 response 의 메소드에서 별도로 처리를 해줘야 하는 것이겠지요? 다시 한번 감사드리며 편안한 주말 보내시기 바랍니다.

**Comment by hyunjun19** [comment]
그리드에 행 추가는 response에서 그리드의 데이터를 새로 갱신하시면 됩니다.
`page34Grid2 .reloadList();`를 한 번 호출해 주세요.

**Comment by jasonseok** [comment]
넵 감사합니다.

**Comment by jasonseok** [comment]
안녕하세요 한가지 문제가 더 생겨서 다시 오픈을 했습니다. 
그리드의 파라미터는 넘어오는데 ajaxPars 로 넘긴 파라미터가 받아지지 않는것 같습니다. ㅜㅜ

**Comment by jasonseok** [comment]
죄송합니다. 브라우저에서 refresh 가 제대로 안되었던 것 같습니다. 다시 확인해 보겠습니다.
