### ISSUE TITLE
AXGrid (misc) 경우, 스크롤을 내리면 데이터가 사라지는 현상

### ISSUE THREAD

**Issue by misocap** [axisj/axisj#952]
![image](https://cloud.githubusercontent.com/assets/20658983/19877421/75b05f34-a022-11e6-8d80-11966a65eabf.png)

이러한 화면을 만들었는데, 
[체크] 열과 [사유] 부분에 데이터를 입력하고 스크롤을 내렸다가 올리면 초기상태 그대로 됩니다. 

샘플예제를 살펴보니... 
달력 칼럼은 onchangeScroll 부분에서 bindDate를 해줘서 스크롤을 내렸다 올려도 값이 남아 있는데..
그외의 텍스트상자라, 라디오버튼으로 조합해서 하려고 하는 경우... 
스크롤에 따라 어떻게 바인딩을 해줘야할지 몰라서요... 
고민고민 하다가... 올려봅니다... 

*코트첨가가 깔끔하게 안 돼서..ㅠㅠ 첨부파일로 올립니다. 
[a.txt](https://github.com/axisj/axisj/files/563220/a.txt)

**Comment by lhslive** [comment]
input 문자열을 생성하는 과정에서 onchange 등으로 이벤트를 직접 걸어주세요.
예제에서 onchangeScroll에 따로 bindDate를 적용해 준 이유는 각 아이템마다 bindDate를 적용해야 해서 그런거구요..
이런 경우에는 myGrid.list[idx].A_CHK , myGrid.list[idx].A_BIGO 에 값을 업데이트 해 주시면 됩니다.

http://jdoc.axisj.com/AXGrid.html#updateItem 이걸 참고 하셔도 되구요.

아래 코드는 그냥 끄적거려 본겁니다.. 참고만 하세요.

```
{key:"A_BIGO", label:"사유", width:"150", formatter: function(){
                        return '<input type="text" name="" id="bigo_'+this.index+'" class="AXInput" value="'+ this.value +'"  style="width:100%;box-sizing:border-box;height:23px;" onchange="change_value("+this.index+",'A_BIGO',"+this.value+")" />';
                    }},

function change_value(idx,key,value){
   myGrid.list[idx][key]  = value
}
```

**Comment by misocap** [comment]
감사합니다!!!! 알려주신 것 응용해서 적용해봤는데 매우 잘 돼요. ㅠㅠ 정말 감사합니다. 

radio 버튼의 경우는 
**onclick="fnObj.grid.changeRValue(...)"**
이런식으로 값을 셋팅해주는 함수를 호출했고, 

text의 경우는 알려주신 것처럼.. 
**onchange="fnObj.grid.changeValue(....)"**
이렇게 호출해주고, 해당 List에 해당되는 컬럼명에 값을 업데이트 해주니까.. 
스크롤해도 안 날아가네요. 

감사합니다.
