### ISSUE TITLE
AXSELECT 컨트롤 그리드말고 그냥컨트롤 Disabled 이안되는데 도와주세요 ㅜㅜ

### ISSUE THREAD

**Issue by DomaPark** [axisj/axisj#953]
$(document).ready(function() {
$("#CBOTEST").bindSelectDisabled(false);  
}
	<select name="" class="AXSelect W100" id="CBOTEST" disabled="disabled"></select>
이렇게 처리했는데 안되는 이유를 모르겠습니다.
어떻게 해야할까요 ㅠㅠ

**Comment by lhslive** [comment]
http://jdoc.axisj.com/jQueryExtends.html#.bindSelectDisabled

```
$("#CBOTEST").bindSelectDisabled();
$("#CBOTEST").bindSelectDisabled(true);
```
이렇게 하셔야 할거 같은데요

**Comment by DomaPark** [comment]
지금 확인해본 결과 코드가 안먹히고 있습니다...
AXSelect.js 에서 this.object 이 변수의 길이값이 0 인데 this.object가 증가되는 기준좀 알려줄수있을까요??

일단 바인딩된 소스를 올려볼게요

$(document).ready(function() {
   	CboSetting("S050", $("#CBOTEST"),"10");
});

function CboSetting(code, ControlID,DefaultValue) {
	var PARAM = new Object();
	PARAM.MAIN_CODE = code;

	PARAM = JSON.stringify(PARAM);

	$.ajax({
		url : "PCSTEST.do",
		type : "post",
		contentType : 'application/json',
		data : PARAM,
		dataType : "json",
		crossDomain : true,
		success : function(data) {

			$.each(data, function(idx, key) {

				if (code == "B001" || code == "B301") {
					ControlID.bindSelect({
						options : data.list
					  , setValue: DefaultValue
					});
				} else {
					ControlID.bindSelect({
						isspace : true,
						isspaceTitle : "선택하세요",
						options : data.list
					  , setValue: DefaultValue
					});
				}
			});
		},
		error : function(request) {
			alert("실패");
		}
	});
}

<div class="tdRel">
								<div class="tag-result">
									<select name="" class="AXSelect W100" id="cbodept_code_q" disabled="disabled"></select>
								</div>
							</div>

이렇게 바인딩 시켯는데 Object값에 아무것도 안들어오네요 ..

**Comment by lhslive** [comment]
ajax 로 가져오는 예제는 
http://dev.axisj.com/samples/AXSelect/index.html 에서 참고 해 보시고요..

F12 누르셔서 데이터가 정상적으로 들어오는지도 테스트 해 보세요.

콘솔에 찍히는 에러메세지는 없는지도 보시고요.

가져오는 데이터는 따로 reserveKeys 옵션을 지정하지 않았을 경우에는 아래처럼 options로 담겨 와야 합니다.
```
{
	result:"ok",
	options:[
		{optionValue:1, optionText:"Seoul"},
		{optionValue:2, optionText:"대구"},
		{optionValue:3, optionText:"대전"},
		{optionValue:4, optionText:"창원"},
		{optionValue:5, optionText:"마산"},
		{optionValue:6, optionText:"구례"},
		{optionValue:7, optionText:"제주도"},
		{optionValue:8, optionText:"전주"},
		{optionValue:4, optionText:"창원"},
		{optionValue:5, optionText:"마산"},
		{optionValue:6, optionText:"구례"},
		{optionValue:7, optionText:"제주도"},
		{optionValue:8, optionText:"전주"},
		{optionValue:9, optionText:"Gwangju"}
	],
	etcs:""
}
```

**Comment by DomaPark** [comment]
감사합니다. 
사랑합니다. 
응원하겠습니다. 
최고가 되는  날까지 기도하겠습니다 ♥♥♥♥♥♥
