### ISSUE TITLE
colHead의 checkbox를 클릭 했을 경우 event 인지

### ISSUE THREAD

**Issue by gosumdochi** [axisj/axisj#957]
안녕하세요

https://github.com/axisj/axisj/issues/590
답변을 통해서

colHead의 checkbox 클릭 할 경우 이벤트를 실행시키는 것은 알았습니다.

이벤트 제어시 colHead의 checkbox

> 체크 이벤트

인지 

> 체크 해제 이벤트

인지
구분 할 수 있는 방법이 있을까요?

**Comment by gosumdochi** [comment]
올리고 보니 
https://github.com/axisj/axisj/issues/590
여기에 답변이 올라 왔네요.
깃 허브 글 올린것은 삭제가 안되나요? ㅎ
잘못올린 글을 어떻게 삭제하는지 잘 모르겠네요 ㅜ.ㅜ

**Comment by lhslive** [comment]
```
oncheck: function(){
    if(this.checked){} -- 체크 일때

```

**Comment by gosumdochi** [comment]
@lhslive 님 답변 감사드립니다.
저의 경우는 해당 코드로는 제대로 동작을 안해서
하기와 같이 작업을 진행하였습니다.

```
oncheck: function(){
    if(this.list[0].___checked[0]==true) {
	alert('check');
    }else {
	alert('uncheck');
    }
```

다른 분들께도 도움이 되었으면 좋겠습니다.
