### ISSUE TITLE
AXGrid 헤더만 유지하고 하단 List는 제거하는 방법

### ISSUE THREAD

**Issue by gosumdochi** [axisj/axisj#958]
안녕하세요

AXGrid 사용중 헤더만 유지하고 헤더 하단 리스트를 제거 혹은 숨기는
방법이 있는지요?

흔치 않은 경우인데 제가 처한 상황에서 꼭 해결해야만 해서 이렇게 질문드립니다.

감사합니다.

**Comment by lhslive** [comment]
f12 누르고 그리드 body 부분을 보시면 해당 dom에 대한 정보가 보입니다.
id던 class 가 되었던 접근 하시면 될거 같네요.

**Comment by gosumdochi** [comment]
@lhslive  님
고수님의 답변으로 오늘 문제를 2가지나 해결 할 수 있게 되어 너무 감사드립니다 !

**Comment by gosumdochi** [comment]
해결 방법 공유 드립니다.
```
AXGrid.setConfig({
     height : 38
```
과 같이 높이를 강제로 컬럼 크기만 지정해줍니다.

컬럼 오른쪽 끝에 생기는 스크롤바 잔상은
`$("#colHeadGrid_AX_scrollTrackY").remove();`
를 추가해주면 사라집니다.
