### ISSUE TITLE
inline-edit 비활성화 관련

### ISSUE THREAD

**Issue by jasonseok** [axisj/axisj#964]
안녕하세요 
editor 속성을 설정한 grid 에 대해서 특정 상황(예를 들면 권한,마감 등)에서 inline-edit 상태를 비활성화 하고 싶은데 어떤 방법이 있는지 문의 드립니다.

**Comment by groovedk** [comment]
myGrid.editCellClear()

**Comment by jasonseok** [comment]
죄송합니다. 제가 질문을 명확하게 하지 않았던 것 같습니다. 셀에 더블클릭을 해도 input 형태로 바뀌지 않게 하려는 의도였습니다.

**Comment by jasonseok** [comment]
myGrid.config.control_lock_status=2 이걸로 해결했습니다.
