### ISSUE TITLE
새 창에 Post로 Form Submit시 새 탭이 열려요

### ISSUE THREAD

**Issue by david80** [axisj/axisj#965]
myModal.openNew 매서드 

IE11에서 새 창으로 팝업을 열고, 열린 팝업에 Post로 Form Submit을 하면 팝업엔 아무런 반응이 없고, 
새 탭이 열리는 현상이 있습니다..

Post로 Form Submit이 필요한 경우, LocalStorage를 이용하여 별도의 루틴으로 처리한다라고 하는데..

참고
http://www.php5.me/blog/ie-ie11-%EC%97%90%EC%84%9C-%ED%8C%9D%EC%97%85%EC%9C%BC%EB%A1%9C-%ED%8F%AC%EC%8A%A4%ED%8A%B8-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EC%86%A1-%EC%8B%9C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%EC%B1%85/

**Comment by thomasJang** [comment]
window.name 이 있어서 그럴겁니다. form submit 할 때 타겟이 없고, openNew로 열린 창은 name이 있구요
