### ISSUE TITLE
AXModal IE에서 문제가 발생하는데 도움을 부탁드려도 될런지요?

### ISSUE THREAD

**Issue by JONGHWALEE** [axisj/axisj#968]
정의되지 않음 또는 null 참조인 'body' 속성을 가져올 수 없습니다 문구와 함께

AXModal.js 의  부분이 정상동작 하지 않는군요 ...개발 완료인데 모든걸 뒤집을수도없구 흑흑..살려주십시오

var bodyHeight = axdom(myIframe.document).innerHeight();

**Comment by thomasJang** [comment]
잘 돌아가서 개발완료에 문제 없으시길 바랍니다.

**Comment by JONGHWALEE** [comment]
해당부분은 어떻게 대체코드를 삽입하여 해결하였습니다만...
close 에서 삭제된 스크립트에 대한 문구가 랜덤하게 발생하는군요...
